### PR TITLE
Double click/ENTER to join a room in lobby

### PR DESCRIPTION
**Pull request by poixen**
[REVIEW]
Can now double click on a room in the lobby to join.
Can now press ENTER on a room in the lobby to join.

### CODE REVIEW

**Comment by woasha** [comment]
@ZeldaZach  - I think the best UI would be instead to have it prompt that the room is full and ask the user if they would want to join as a spectator. Further development could be considered to add an option in settings to "automatically join full game as spectator Y/N"

My $.03.

**Comment by ZeldaZach** [comment]
A whole 3 cents? wow, that's getting rich! xD
I like the idea of asking for, if it's a full game, to join as a spectator. If it's on restriction mode, it should just bounce back "This game is full and no spectators are allowed"

**Comment by woasha** [comment]
Well, I'm just a random QA who's lurking on your github instead of doing his real work. My insight is only worth $.03. Canadian at that, which is actually what, $0.224 cents US? ;)

I'm not a UX guy my any means, but I do believe that a prompt approach by default with a selectable auto-join option is the cleanest, logical way to do it.

**Comment by tooomm** [comment]
@woasha 100% agree. :+1:

**Comment by Daenyth** [comment]
I strongly dislike adding modal dialogs unless the software has no intelligent action available - I think in this case the cost to being wrong is low, so it should just join rather than prompt. If that's not what the user wanted, it's not hard to close the window. Allowing it without interruption smooths out the user flow.

**Comment by anoda9** [comment]
I strongly agree with Daenyth - pop-ups are annoying, and it's very easy to close games you are spectating (crtl-q). Also, it seems more convenient in general for "enter" to both join open games and spectate full games (a catch-all "I want to get involved with this game" shortcut) rather than having separate shortcuts for either. There is the rare corner case where a user might want to spectate a game that is not full, but in that case the spectate button could be used.

**Pull request merged**
