### PR TITLE
add more precise rules to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ebbit1q**
Add extra rules that clang-format enforces, like the order of includes and the way single line comments should be formatted.
Correct some grammar ( what is up with the translation section ordering steps out of order?? ).
This is a web edit.

### CODE REVIEW

**Comment by ebbit1q** [comment]
The translation section lists five steps but when explaining the five steps they are listed as 1, 2, 3, 5, 4; likely to separate them over different roles (dev, maintainer, translator) but it's just confusing.

**Comment by tooomm** [comment]
Ahh, got you now! And you are right in your assumption, that was the idea behind it.
If we order it by numbers the process for maintainers will be split up and the reader might think he is done already without - realizing after a step not relevant for him - sometime else has to be done.

But I'll look into improving that and at least add some linking.
Maybe I've some other idea, too. Any suggestion from your side?

**Comment by ebbit1q** [comment]
I say ditch the step numbers in the explanation and see them as guides per target user, it should mention in the maintainer guide that translators do something in between the last two steps of course.

**Comment by tooomm** [comment]
For now I added links to the ordered structure and a jumplist per "user type":
https://github.com/Cockatrice/Cockatrice/blob/tooomm-contributing/.github/CONTRIBUTING.md#translations

Will look further and consider your input in the next days. 👍

**Comment by ebbit1q** [comment]
I created a different pr from the web ui to show how I think the translating chapter would be more readable #3424 , feel free to close it if you want to preserve the current step layout.

**Comment by ZeldaZach** [comment]
Conflicts will need to be resolved b4 i can merge this

**Pull request merged**
