### PR TITLE
Update project to C++11 compilation.

### LINKED ISSUE #127: Update for C++11 compatibility
Currently the project mandates C++98 mode. 13 years is a long time...

### PR DESCRIPTION
**Pull request by Daenyth**
Fix #127

### CODE REVIEW

**Comment by Daenyth** [comment]
Fixes #127

**Comment by woogerboy21** [comment]
This compiled on windows using VS2010 express but keep in mind if C++11 code is added we may need a newer version of VS to compile properly.

**Comment by woogerboy21** [comment]
Cockatrice and Oracle fail to build in VS2013 with the following error:
```
1>------ Build started: Project: cockatrice, Configuration: Release Win32 ------
1>qtmain.lib(qtmain_win.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1700' doesn't match value '1800' in abstractcounter.obj
1>C:\Cockatrice\build\cockatrice\Release\cockatrice.exe : fatal error LNK1319: 1 mismatches detected
```

**Comment by woogerboy21** [comment]
Just tested compiling using VS2013 with Qt 5.5.0 and cmake 3.2.3.  Built fine.

**Comment by woogerboy21** [comment]
@Daenyth Also one thing to mention.  VS2013 has the supported operating systems:
```
System Requirements:

Supported operating systems

    Windows 7 SP1 (x86 and x64)
    Windows 8 (x86 and x64)
    Windows 8.1 (x86 and x64)
    Windows Server 2008 R2 SP1 (x64)
    Windows Server 2012 (x64)
    Windows Server 2012 R2 (x64)

```

The app itself once compiled will allow for XP based machines but to compile using VS2013 will require Windows 7 or newer operating system.  Just mentioning it as you at one time was concerned with backwards compatibility.

**Comment by Daenyth** [comment]
I don't care about XP or Vista support. Anyone using those OSs has bigger problems than getting cockatrice installed.

**Comment by woogerboy21** [comment]
Also posting this information for reference (as Im sure I will relook it up):

```
"Failed start because MSVCP120.dll was not found"
Your installation of windows is missing the Visual C++ runtime libraries (32bit) required by Cockatrice.
This can be solved by using the x86 installer from Microsoft. 
http://www.microsoft.com/en-us/download/details.aspx?id=5555
```

Also added to wiki.

**Comment by ZeldaZach** [comment]
Seems good to me

**Comment by woogerboy21** [comment]
:shipit: (Unless @Daenyth says otherwise)

**Comment by Daenyth** [comment]
ping @ctrlaltca @poixen Do you think this is appropriate?

**Comment by ctrlaltca** [comment]
These cmake properties require cmake >= 3.1

**Comment by woogerboy21** [comment]
@ctrlaltca mentioned this link.  @Daenyth you may want to consider something like this:
http://www.guyrutenberg.com/2014/01/05/enabling-c11-c0x-in-cmake/

**Comment by ZeldaZach** [comment]
Is this good to go yet?

**Comment by ZeldaZach** [comment]
Here we go!! :shipit:

**Pull request merged**
