### PR TITLE
Added buddy stars to chat

### PR DESCRIPTION
**Pull request by poixen**
+ Buddies will now have a star next to them in chat.
untitled

**EDIT: Newer version:**
+ Gold star is more conventional
+ Fixed staggered chat.

untitled

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Looks nice, but I wonder if it would be a slightly confusing experience if it did not have any explanation.

Maybe it'd be nice to add hover text for the star that says "Buddy" or something along those lines.

**Comment by woogerboy21** [comment]
And as usual.  Is this a configurable option?

**Comment by poixen** [comment]
@woogerboy21 ...it is now

**Comment by poixen** [comment]
@Nightfirecat Had a look into this, and there is no support for images and tooltips: http://qt-project.org/doc/qt-4.8/qtextcursor.html#insertImage-4

I thought about making a href, but it seems that can only be used with QTextCharFormat and handling text.

**Comment by Nightfirecat** [comment]
Drat... Hard to think of another way to do that. If there's no good way to show what it means, I think it'd be fine as-is--just thought it'd be a nice add. *shrug*

**Comment by Daenyth** [comment]
I like the feature but the icon feels a bit random. I also dislike that it plays with the alognment of stuff in chat, I feel like that might make things a little harder to read.

What about instead painting a soft grey background color along the whole line if it's from a buddy, instead of the icon?

**Comment by poixen** [comment]
We need to stay away from grey if possible, as we use alternating block backgrounds: [white][grey][white][grey]...

I can add white space for ht other users to alight it correctly?

And the icon, I chose the star as its quite universal, I tried yellow/gold, but it didnt show too well on the white background. Maybe if I have a gold star with a black outline?

**Comment by Daenyth** [comment]
That seems better. Maybe we could highlight in two other sets of colors instead of grey?

**Comment by poixen** [comment]
untitled
 How about that?

**Comment by poixen** [comment]
With the new allignment, this does not look good, if you havent got buddies: 
untitled

**Comment by poixen** [comment]
How about I create a new pawn for each one currently, which is sat in the middle of a colored square?
That should be better, will make a mock-up.

**Comment by tooomm** [comment]
If we can't have a tooltip... What about adding the star to the buddy list itself as well. That way people see the star directly related to the people they add to their buddy list and should get the connection about what the star is about.

@poixen are you referring to a pawn with e.g. a red background for buddies? (still showing which kind of user it is? mod etc.?)
Maybe you can add the star somewhere in there over the background change? Not sure if it looks nice, though.

Is this going to be checked in settings by default?

**Comment by poixen** [comment]
@tooomm Yea going to add a background to the pawn. Cant really add alot of detail there as we dont have many pixels to work with. 

Right now I have the star as an option that is set to true, that can be turned off. If we move with the background instead (which I think we should) then I might go ahead and remove the option. Its just not needed. Having a background will not cause any annoyance.

Also, any changes like this will be across the entire client. Right now its just the chat as its quick to code.

**Comment by poixen** [comment]
untitled

**Comment by Daenyth** [comment]
I like that. Shame we can't add a tool tip.

**Comment by ZeldaZach** [comment]
I'm personally not a fan of the color, and I was thinking is it possible to make the color dynamic to the colorwheel?

**Comment by poixen** [comment]
@ZeldaZach that would be hella hard.
I will just add here what i said in gitter:

I chose the same color as when you get self mentions. I did this as i feel that color should relate to information important to your user.
I dont want to have too many colors as it can be confusing. Like with the purple star.

About the color wheel:
Its tricky... either it stays like this and then its on the user if they want colors everywhere or we remove the color wheel.
maybe we could just highlight the line? but i wanted an app wide way to see buddies,chat isnt available everywhere EG:like in the userlist

**Comment by ZeldaZach** [comment]
So yeah, progress is going well :+1:

**Comment by poixen** [comment]
I know about the failure. Working on it. Code was WIP.

**Comment by poixen** [comment]
As an update, the scope has grown. I am now replacing all instances of pawns with stars (if that person is a buddy). I feel that if we want to do this, we need to do it everywhere.

**Comment by poixen** [comment]
Closing for now, still needs a lot of work.

**Comment by ZeldaZach** [comment]
Good luck with it, @poixen !!

**Comment by Daenyth** [comment]
I like it :)

**Pull request closed without merging**
