### PR TITLE
Readme tweaks

### PR DESCRIPTION
**Pull request by tooomm**
- rearranged Gitter & Travis buttons to make it a nicer and cleaner look
- move "Community Ressources" up for better visibility to the normal user (see 7e92b4e)

Open to your thoughts.

### CODE REVIEW

**Comment by Daenyth** [comment]
Seems fine but it looks like you didn't update your fork

**Comment by tooomm** [comment]
I made the changes within an own branch. And made a PR out of it pointing at your master.
What else do I need to do? (I'm new to all this :) )

**Comment by Daenyth** [comment]
When you created your branch, whatever you were on previously is what the branch is based on. Do a `git remote update; git merge upstream/master` on your branch.

On your master you should do the same

**Comment by tooomm** [comment]
I need to look into this again, maybe I'll stop by in gitter on sunday.

**Pull request closed without merging**
