### PR TITLE
Oracle: support AllSets.json.zip; Fix #624

### LINKED ISSUE #624: Allow oracle to download zipped version of sets json
With the default json we'd go from 11mb -> 2.5mb on each download.

### PR DESCRIPTION
**Pull request by ctrlaltca**
Imported unzip methods from OSDaB-Zip project;
Adds a soft dependency on zlib to oracle; if lib is not found, oracle will continue to compile and work but without zip support.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Tested and works as expected. Ready for merge

**Comment by tooomm** [comment]
Oh yeah! :dancers: 

Is there some kind of fallback when there is a problem with the zip-File or the lib being not working correctly or being broken etc. after downloading the file?
e.g.: "Can't open zip-File" --> run again and use unzipped download instead

The "Restore default url" button is still pointing to the unzipped "AllSets.json"?
I kinda like that in case there are problems.

**Comment by ZeldaZach** [comment]
Yes @tooomm it seems there is. It will spit an error if there's an issue and ask you to put a new link/new file

**Comment by tooomm** [comment]
@ZeldaZach Thanks for clarification.
I always feel dumb when I can't check the code for myself and ask this silly stuff all the time... :(
Still trying to help with understanding + improving the program... more from a user's point of view, though.

In the case you described above ("It will spit an error if there's an issue and ask you to put a new link/new file") it would be great to see a hint, that tells the user to use the "Restore default url" button to automatically provide the right link for the not-zipped version without any hassle for them.

**Comment by Daenyth** [comment]
Can we make the error message for zip failure by

Retry with Zip | Retry unzipped | Retry from local file | Abort ?

**Comment by ctrlaltca** [comment]
@Daenyth what should happen when an user clicks on each option? i imagine:
 * retry with zip: set url to zipped file, press "next"
 * retry unzipped: set url to json file, press "next"
 * retry local file: open "open file" commondialog, then let the user press next
 * abort: quit oracle

Anyway, i having a multi-choice messagebox in the middle of a wizard seems a bit strange to me in terms of UI design.

**Comment by Daenyth** [comment]
Those are the actions I had in mind

**Comment by tooomm** [comment]
To keep it simple:

on Error/Failure:
- sth like: "There was a problem. You want to retry with the bigger uncompressed download instead"
- OK/Cancel

OK will set url to json file, press "next".

**Comment by ctrlaltca** [comment]
Popup added, here it is (a dot is missing after the first sentence, it's already fixed):
yousure

**Comment by Daenyth** [comment]
What does cancel do? Go back to the download panel? Abort oracle? Labeling
isn't clear

**Comment by ctrlaltca** [comment]
Yes/No could be better. "No"  just closes the popup.

**Comment by tooomm** [comment]
If the file is corrupt or there was a download error it will show me a message about the archive containing several files?
That's not serving all cases and is a bit confusing. Why don't we keep it general? (--> e.g. error/failure...)

"There was a problem with the compressed .ZIP archive.
Do you want to download the uncompressed file instead?"

**Comment by Daenyth** [comment]
+1 for that wording change. Cc @poixen if you have any user flow input on
this

**Comment by ctrlaltca** [comment]
That's not exact: mine screenshot was just an example of one of the possible error messages.
The code i changed is not involved in the download process itself, but only in trying to unzip the file if it's detected as a possible zip archive (that could be the result of a download or a local file).
A download error will trigger the preexisting error message: Network error <description>.
When unzipping the file, the following error messages can be displayed depending on the specific error:
 * Failed to open Zip archive: <description>
 * Zip extraction failed: the Zip archive doesn't contain exactly one file.
 * Zip extraction failed: <description>
 * Sorry, this version of Oracle does not support zipped files

Can i suggest you to test the code or at least look at it?

**Comment by ctrlaltca** [comment]
@Daenyth the +1 for the wording change was for my  "yes/no" proposal  or for @tooomm 's error message proposal?

**Comment by Daenyth** [comment]
Both, but you've explained the error wording so that makes sense now. Sorry, I hadn't checked the revised code yet

**Comment by ctrlaltca** [comment]
Is there any other improvement that i can make to this PR?

**Comment by Daenyth** [comment]
I think it's ready to merge. @zeldazach do you want to check it?

**Comment by ZeldaZach** [comment]
I did a few hrs ago

**Pull request merged**
