### PR TITLE
Search full subdirectory for custom databases

### LINKED ISSUE #2324: Recursively search customsets folder for xml set files
see #2251 

Support for sub directories is now included for the custom picture folder, but not yet for custom sets.

### PR DESCRIPTION
**Pull request by ZeldaZach**
## Related Ticket(s)
- Fixes #2324

Allows for system iteration

```
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/cards.xml"
PictureLoader: cache fail for "_trice_card_back_231291"
[CardDatabase] loadCardDatabase(): Path = "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 21494 Sets= 501
[CockatriceXml4Parser] Trying to parse:  "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21967 Sets= 501
[CardDatabase] loadCardDatabase(): Path = "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21967 Sets= 501
[CockatriceXml4Parser] Trying to parse:  "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/customsets/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/customsets/tokens.xml" Status = 0 Cards = 21967 Sets= 501
[CockatriceXml4Parser] Trying to parse:  "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/customsets/test1/test1.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/customsets/test1/test1.xml" Status = 0 Cards = 21967 Sets= 501
[CockatriceXml4Parser] Trying to parse:  "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/customsets/test2/test2a/test2.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/zachary/Library/Application Support/Cockatrice/Cockatrice/customsets/test2/test2a/test2.xml" Status = 0 Cards = 21967 Sets= 501
CardDatabase::loadCardDatabases success
```

With 
```
$ tree
.
├── test1
│   └── test1.xml
├── test2
│   ├── test2a
│   │   └── test2.xml
│   └── test4 -> test4
├── test3
└── tokens.xml
```

### CODE REVIEW

**Comment by ZeldaZach** [comment]
(Two extra files are from clangify)

**Review by ebbit1q — CHANGES_REQUESTED** [review]
this works great but it will now load the databases in a random order, they are expected to be loaded alphabetically.
I'm also worried about recursing too deep here, anything more than 2 recursions sounds unnecessary to me.

**Comment by ZeldaZach** [comment]
Agreed. I've changed it to load alphabetically and alert the user of the load order. I'm not worried about recursive looking tbh, as some users like heavily nested components.

**Review by ebbit1q — APPROVED** [review]
works fine, a bit slow maybe

**Pull request merged**
