### PR TITLE
CI: Update Qt version (Windows)

### PR DESCRIPTION
**Pull request by tooomm**
## What will change with this Pull Request?
- Update to Qt 5.15.2 and MSVC 2019
- Fix QTDIR var call

### CODE REVIEW

**Comment by ebbit1q** [comment]
we should update it to 5.15 if possible, 5.15 will be the longest supported qt5 version and has an important security issue fixed that'd affect you if you wanted to run a server on windows. https://github.com/Cockatrice/Cockatrice/pull/4398

**Comment by tooomm** [comment]
Let's see how this works with msvc and 32bit.

**Comment by ebbit1q** [comment]
I'm not able to test these

**Comment by tooomm** [comment]
I have the 64bit version running without issues since two weeks

**Review by ZeldaZach — APPROVED** [review]

**Pull request merged**
