### PR TITLE
add homebrew cache to cache

### LINKED ISSUE #3775: Cache homebrew in travis
See https://travis-ci.community/t/how-to-cache-homebrew-updates-on-macos/3971

### PR DESCRIPTION
**Pull request by ebbit1q**
We'll build this a few times

## Related Ticket(s)
- Fixes #3775

### CODE REVIEW

**Comment by ebbit1q** [comment]
I'm triggered by the ci not being triggered

**Comment by ebbit1q** [comment]
eeek, it's using 5.13

**Comment by ebbit1q** [comment]
Acceptable build time, under 10 mins.

**Comment by tooomm** [comment]
>eeek, it's using 5.13

No ~`qt-lts` on homebrew. Always only the newest... 😢 
It also silently switched on our master branch already.

But nice improvement here.

**Pull request merged**
