### PR TITLE
Remove Fedora 37 Build, Add Fedora 39 Build

### PR DESCRIPTION
**Pull request by SlightlyCircuitous**
## Short roundup of the initial problem

Fedora 37 [went end of life on December 5, 2023](https://docs.fedoraproject.org/en-US/releases/eol/) so we will not need to build for it in future releases. 

Fedora 39 was released on November 7, 2023 and [will be supported until December 5, 2024](https://fedorapeople.org/groups/schedule/f-39/f-39-key-tasks.html) so it would be advantageous to our users to build for it in future releases. As far as I can tell, none of the packages that we depend on for this build have been renamed or reorganized between Fedora 38 and Fedora 39.

## What will change with this Pull Request?
- Removes Fedora 37 build from CI
- Adds Fedora 39 build to CI
- Edits release template to reflect the above changes

### CODE REVIEW

**Review by tooomm — APPROVED** [review]
Changes looking good, builds pass 👍 

Did you test the resulting Fedora 39 build?

**Comment by SlightlyCircuitous** [comment]
no, I didn't yet. I can spin up a fedora 39 vm and do that

**Comment by SlightlyCircuitous** [comment]
Installed the Fedora 39 build in a VM without issues. I can open the client, run oracle, start a local game, and do basic card manipulations like drawing cards, playing cards, creating tokens, and putting cards in graveyard/exile.

**Comment by tooomm** [comment]
Online connection also works?

**Comment by SlightlyCircuitous** [comment]
Yes, it can connect to Chickatrice with no issues.

**Comment by tooomm** [comment]
Thanks for updating and confirming that there are no issues!

**Pull request merged**
