### PR TITLE
Load .cod files from clipboard in deck editor

### LINKED ISSUE #818: Load from clipboard should support .COD
the only other format i've tried is mtgo's `.txt`, which works, is that the only one supported? would be nice if the supported formats were documented, preferably in the load dialog

### PR DESCRIPTION
**Pull request by Fizztastic**
Fix #818

Adds the ability to load .cod (xml) from clipboard.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Tested and works fully as expected. Nice job!!

**Comment by ZeldaZach** [comment]
:shipit:

**Comment by woogerboy21** [comment]
Yeah this worked for me as well.

**Comment by Daenyth** [comment]
We should probably make that DeckLoader stack allocated instead of new-ing it

**Pull request merged**
