### PR TITLE
Run tests on WIndows CI

### PR DESCRIPTION
**Pull request by olegshtch**
## What will change with this Pull Request?
- Adds tests to Appveyor
- Synchronizes mock headers in the `dbconverter` and tests.

### CODE REVIEW

**Comment by ebbit1q** [comment]
This is very useful, tests would probably behave differently on windows. Consider #4000 you'll most likely have to use the debug build type which'll give other issues :(

**Comment by olegshtch** [comment]
I suppose MSVS doesn't accept mocks as the same symbols.

**Comment by ebbit1q** [comment]
Is anyone even able to compile the tests locally on like a normal windows vm?

**Comment by olegshtch** [comment]
Tests are failed because required libraries aren't in `PATH` but link issues are fixed and test results are published.

**Comment by olegshtch** [comment]
@ebbit1q Looks like Windows also affected by #4000

**Comment by ebbit1q** [comment]
I expected as much, would we be able to use the debug build type if it fixes the problem?

**Comment by ebbit1q** [comment]
I see there is now 4 builds, do the release builds still run tests or only the debug ones?

**Comment by tooomm** [comment]
>It doesn't fail build although.

@olegshtch Is that a general appveyor thing, or a setting?

<br>

Having all 4 builds run every time doubles the already long appveyor build time again and leads to very late results...

For travis we have "conditional builds" setup:
PR's build debug only, master branch builds debug+release and tagged commits build only release.
Maybe something similar is possible here, too?

**Comment by ebbit1q** [comment]
on travis all the pr builds are debug, only the ubuntu 18.04 one is tests but it only adds like 3 seconds or so.

**Comment by ebbit1q** [comment]
this is pretty much what I expected for debug builds on windows:
```
    4846 Warning(s)
    18 Error(s)
```

**Comment by olegshtch** [comment]
> this is pretty much what I expected for debug builds on windows:

@ebbit1q Looks like mocks doesn't work for debug builds as even `dbconverter` is broken. I'll remove debug configuration for now.

> Maybe something similar is possible here, too?

Debug is hadrly broken here so I think it's too early to think about it. I want to try to parallelize build.

**Comment by olegshtch** [comment]
It looks like in Debug build `mocks.obj` have own `QString SettingsCache::getCardDatabasePath() const` from `mocks.cpp` and `carddatabse.obj` have not inlined `QString SettingsCache::getCardDatabasePath() const` from `settingscache.h`. In the Release build second is inlined and doesn't lead to link conflict.

**Comment by olegshtch** [comment]
#4000 was fixed so tests are passed now.

**Pull request merged**
