### PR TITLE
Rework the way sets selection/importing works; fix #539

### LINKED ISSUE #539: Default set selection for Oracle doesn't encompass all printed cards
In the sets selection step in Oracle, the default set selection is all the core sets + expansion sets. However, this selection ***does not*** encompass all the cards printed in magic, so a user going with the default selection will be missing unique cards from the commander, planechase, and conspiracy sets, which can often show up in legacy, cube or EDH. (e.g. True-Name Nemesis, Shardless Agent, Grim Tutor). The fact that the default set selection does not include data for True-Name Nemesis (a card that appears fairly often in legacy) is pretty poor. All the portal sets also seem to be excluded. 

Fix: Add the the non-standard legal sets (planechase, commander, conspiracy) and portal to the default set selection in oracle.

sets to be added:
http://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets#Non-standard-legal_sets
http://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets#Introductory_sets

set selection

### PR DESCRIPTION
**Pull request by ctrlaltca**
This PR modifies the way oracle imports and cockatrice handles sets in order to:
 * ensure every player have the full list of cards (needed eg. when spectating other's games);
 * a player can decide once the sets he want to use, and oracle won't override that at eery run;

So, first change is that now oracle always loads all the sets (no more choice screen).
Then, inside cockatrice, you can enable/disable each set; cards from disabled sets won't be shown in the deck editor, but cockatrice will still knows that they exists and show them if needed (eg. when another player use that card).
sets
The last change is that cockatrice will remember the existing sets from its previous runs, so it will be able to understand if a new set has been added to the card database. If this s the case, when a new "deck editor" tab gets open, the user will be presented a messagebox with 3 options:
msgbox
 * Yes enables the new sets;
 * No keeps the new sets disabled;
 * Cancel postpones the question.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Seems to fail on QT4, but I really like how this is turning out a lot!

This should help limit issues people have and allow people to understand how to add new sets easier than before. :+1:

**Comment by ZeldaZach** [comment]
This seems to be perpetually saving the information in the plist file found at `~/Library/Preferences/de.cockatrice.Cockatrice.plist`, which we discussed in the past with sortKeys and a potential change in how they're done (#347).

Just pointing this out, as the sortKey thing we discussed was an issue

**Comment by ctrlaltca** [comment]
I suppose the discussion in #347 predates the changes to the "sets window" that made sorting sets a bit easier. Anyway, it' surely related and creating a comprehensive solution is a good idea.
The plist file is something you'll find only under osx, since it's the default backend for QSettings, that uses the registry under windows and ini files under linux.
The nice part of using QSettings is that we don't need to care about where settings are stored and in what format. The bad part is that currently these preference are saved outside the cockatrice profile folder, in different formats depending on the os.
Maybe we could address this in a separate PR, moving preferences to a file inside cockatrice's profile folder, using a better format (xml or ini)?

**Comment by ZeldaZach** [comment]
Nice changes in dd6a1d1 with allowing for enabling/disabling the entire field list in case you want to only work with certain sets and such.

I feel as if this is ready to ship, but I think another person or two should check this out :shipit:

**Comment by tooomm** [comment]
I like this change very much! :+1: 

very nice for:
- spectating games, because you can see/read all played cards 
- card mentions in chat with [[x]] are always visible

<br>
> It's, at least to me, important to make sure that by default, you can see every card people play. 

This point from @Cerxi is also accomplished.

<br>
Which sets are enabled by default if I run oracle + cockatrice for the first time?

What do you think about a (optional) possibility to just save pictures from sets you have enabled to your pc. Other card pictures (from that one card in chat that you check for 5s once) will just be saved temporarily and are gone after restart the client.
This will save you hundreds of mb over time and keeps your picture folder clean. Sets you use more often will be enabled anyway.

Images of sets that I disable should be deleted? (with warning or yes/no box!)

**Comment by ZeldaZach** [comment]
>Which sets are enabled by default if I run oracle + cockatrice for the first time?

All of them

>What do you think about a (optional) possibility to just save pictures from sets you have enabled to your pc. Other card pictures (from that one card in chat that you check for 5s once) will just be saved temporarily and are gone after restart the client.

Getting complex Tomm :yum: 

>Images of sets that I disable should be deleted? (with warning or yes/no box!)

I don't see a reason for this as we have a "clear all downloaded" button

**Comment by ctrlaltca** [comment]
Hum maybe i should add a check that if no sets are known/enabled, then all of them gets enabled without the need to ask the user. This way we'll avoid new users to mistakenly answer "no, don't add any set" and found no card available in cockatrice until they find the "sets" window.

About temporary images, that's a bit complex, but it could be discussed/implemented in another ticket.

**Comment by ctrlaltca** [comment]
Additionally, if no sets are known/enabled, we should set a default sets ordering. I suppose a good default could be release date DESC (newer to older)

**Comment by ZeldaZach** [comment]
>Additionally, if no sets are known/enabled, we should set a default sets ordering. I suppose a good default could be release date DESC (newer to older)

**Comment by tooomm** [comment]
I like that.
Select all sets by default, order them from newest on top to oldest on the bottom.
It's not perfect and many users might scream at first. But it's ok I think and keeps things simple.
They have to look into it once and are good to go.

But I don't like to automatically enable all sets if none are enabled. Maybe someone builds his decks within an other app or uses decklists from the web to play or someone just spectates. So he disables all sets to have a clean deck editor.
For first time users they should be all enabled though, and the "Edit sets..." dialog should always open as well. So they know they can make changes. If they don't want to, they just close the window and will never see it again.
In this case it would be better to replace the "xx new sets have been found...." dialog box for first time users and go to the "Edit sets..." menu instead.
This will avoid, that they click "no, don't import" by mistake and ask for help because they don't see any cards. :)

<br>
ideas:
- Do we need `enable/disable set` buttons?<br>
We have checkmark boxes for that and oracle had them before too without the need for additional buttons. The additional buttons just blow up the interface without providing real benefit. Users know about checkmark boxes.
- There should be normal dialog buttons like `ok` and `cancel`.<br>
`cancel` to overrule any changes and `ok` to accept changes instead of `restore old ordering` etc.
Ok=save/accept, cancel=discard, don't confuse the user with new buttons :)
- Configuration is not stored inside cards.xml - is that correct?<br>
Save set configuration to a file, to easily transfer the heavily customized settigs to other computers, backup them or help with setting up a new laptop for example.
- Button which links to the set editor from the dialog box "xxx new sets have been found. do you want to enable them".<br>
Button label might be `Edit sets`, `Go to set editor`, `Go to "Edit sets..."`, `Configure` ...

<br>
>I don't see a reason for this as we have a "clear all downloaded" button

For example, there is someone just playing standard. So he needs the last ~6-8 sets.
When editions are no longer legal, he just keeps all the old arts for no reason (easily thousands of files and hundreds of mb in a short time).
Or he deletes all his pictures with the "clear all downloaded" button, just to redownload 80% of them right after...
With the new upcoming rotation system, there will be even faster changes and fewer sets legal at one time.

If deselecting a set triggers a dialog box which asks to delete (y/n) the corresponding pictures that would be great! The "clear all pics" button is still valid and useful for some other use cases.
I would be happy to use that for limited play only as well!

**Comment by ctrlaltca** [comment]
> In this case it would be better to replace the "xx new sets have been found...." dialog box for first time users and go to the "Edit sets..." menu instead.

Nice idea :+1: 
> Do we need enable/disable set buttons?
I think i left them in just for visual parity, so that we have 4 buttons in the "enable/disable" part of the window and 4 buttons in the "sets order" part of the window. 

> There should be normal dialog buttons like ok and cancel in the lower right corner.
Definitely a wise idea.

> Configuration is not stored inside cards.xml - is that correct?
Yes; cards.xml will be completely overwritten by oracle when updating cards. We want t store persistent settings somewhere else. I already discussed (IIRC with @ZeldaZach) the need of moving these persistent settings in a user-accessible file (by now it depends on the os: win registry, linux ini file, osx plist). Anyway this is out of scope, i will address it in another PR.

> Button which links to the set editor from the dialog box "xxx new sets have been found. do you want to enable them".
> Button label might be Edit sets, Go to set editor, Go to "Edit sets...", Configure ...
While i agree with the general idea, i think that having 4 different choices in a "quick question dialog" out of basic choices (yes/no) is too scary in UI terms.

> If deselecting a set triggers a dialog box which asks to delete (y/n) the corresponding pictures that would be great! The "clear all pics" button is still valid and useful for some other use cases.
This is an interesting idea, but out of the scope of this ticket.

**Comment by ctrlaltca** [comment]
So, i've implemented the proposed changes and pushed an additional patch that will fix cockatrice from changing the sets order when using a tokens.xml.
Before 5296c57, cockatrice would
 * load tokens and create sets defined in tokens.xml
 * change all the sets key recounting from 1, then sort sets
 * load cards and create sets defined in cards.xml; if a set with the same code already existed, we created a new set with the same code and insert it over the old one
 * change all the sets key recounting from 1, then sort sets

This caused sets appearing in tokens.xml to have their sortkey changed.

**Comment by ctrlaltca** [comment]
By the way my current test procedure is:
 1. clean cards.xml and preferences; under osx cleaning preferences is a mess:
```
# my username is fab; yours can be different ;)
rm -rf "/Users/fab/Library/Preferences/de.cockatrice.Cockatrice.plist" "/Users/fab/Library/Saved Application State/com.cockatrice.cockatrice.savedState" && killall -u fab cfprefsd
```
 2. run oracle with an old AllSets.json (missing some recent sets);
 3. run trice, ensure that the "edit sets" window gets shown with all the sets enabled and sorted by release date desc;
 4. disable all sets, enable only my favorite ones, press ok;
 5. reopen the "edit sets" window, ensure everything is as expected;
 6. quit trice and restart it, open the "edit sets" window, ensure everything is as expected;
 7. run oracle with a newer AllSets.json;
 8. run trice, ensure the "new sets found" popup appears, answer yes;
 9. open the "edit sets" window, ensure the new sets are enabled and at the top of the list, press ok;
 10. reopen the "edit sets" window, ensure everything is as expected;
 11. quit trice and restart it, open the "edit sets" window, ensure everything is as expected.

**Comment by ctrlaltca** [comment]
@Daenyth do you think this is actually mergeable?

**Comment by Daenyth** [comment]
I like the feature but I haven't had time to test or review much

**Comment by ZeldaZach** [comment]
I wonder why this is failing on Macs.

The warning comes from #966, but it seemed to work fine when I went through it separately and Travis agreed.

**Comment by ctrlaltca** [comment]
While merging master i failed and removed a needed #include <QProcessEnvironment>.

**Comment by ZeldaZach** [comment]
I think Dae would want a rebase done, but this is ready to merge when you are :shipit: :)

**Comment by ctrlaltca** [comment]
Closing in favor of #985

**Pull request closed without merging**
