### PR TITLE
Reworked deck editor

### LINKED ISSUE #97: New Deck Editor needs UI Polish
- [x] Card movement icons need improvement (keycodes listed, better icons)
- [x] The color filter needs the user to enter "g" for "green", etc. It should handle the color words
- [x] Case handling might not be consistent
- [x] Hitting <kbd>-</kbd> on a filter doesn't remove it
- [x] Oracle text can't be viewed at the same time as image, and the toggle between is hidden in the menu
- [x] There's no "clear all" button for filters except hidden in the menu
- [x] cardname filter box is anchored to beginning of name instead of anywhere in name
- [x] Deck editor needs to do natural sort. Diacritics should come after their unmodified form. Eg `Jö` should come after `Jo` and before `Jw`

### PR DESCRIPTION
**Pull request by ctrlaltca**
Reworked the filters area, added proper buttons to remove filters and grouped it in a box.
Reworked the card preview, added back the ability to see both the card image and text.
Idea from #97 

middle

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Just a note; don't write "fix #97" as it will close the ticket on merge... And that's the super long suggestion ticket. 

I'll do some testing when I get home. Looks nice :)

**Comment by ZeldaZach** [comment]
After testing, this works fully as expected. My only suggestion is to potentially re-look at how the buttons are displayed. In-game, they are configured into a `<select>` menu, and being redundant might be better then having a whole new way to see things.

screenshot 2015-06-13 18 43 57

Also, when you see both, you have the option to resize the card image where as in the deck editor, with your change, you cant:
screenshot 2015-06-13 18 44 36
screenshot 2015-06-13 18 44 40

**Comment by ctrlaltca** [comment]
The in-game card view is not the same widget used in the deck editor; if this one looks good, i can look towards using it in games, too.

> Also, when you see both, you have the option to resize the card image where as in the deck editor, with your change, you cant:

That's because in games there's a splitter that you can slide manually.. this is a nice idea that could be implemented in the deck editor, too.

**Comment by ZeldaZach** [comment]
I'm fine with using either method, as long as it's consistent throughout the client. 

The slider thing is pretty nice, so if you could look into it I'd appreciate it :)

**Comment by Daenyth** [comment]
I'd like to get this feature in first and then we can polish after in
another PR.

**Comment by ZeldaZach** [comment]
Based on @Daenyth's comment, this is ready to be merged.

**Pull request merged**
