### PR TITLE
Cleanup server running variable information

### PR DESCRIPTION
**Pull request by woogerboy21**
This PR is designed to accomplish the following goals:
- Cleanup the server variable declaration and remove un-needed variable content consuming memory
- Allow for most (if not all) server side settings to now adhere to settingsCache->reload calls (this will allow for most if not all the server settings to refresh during operation not requiring a server down/up to reload settings)
- Uniform the method in the code base for server/servatrice to get settings information
- Clear the path for moving the helper function calls into the settingsCache class (clarity reasons)
- Create slot/function/calls to allow for featureset refreshing while running.

This is a pretty large change and could use others eyes on testing server side functionality.  @ctrlaltca comes to mind if you have free time at some point (at least to look over the code changes).

### CODE REVIEW

**Comment by woogerboy21** [comment]
Just an FYI, I currently have only done a successful compile with the code.  I have not put any effort into actually testing server side functionality just yet as I wanted to get the signal/slot items in place before doing so.  Use at your own risk right now for testing.  Im 99% confident its fine, but tinkering with variables often results in something being over-looked and a default value being used rather than being read from the ini properly.

**Comment by ctrlaltca** [comment]
Looks like a nice cleanup, will definitely test it later

**Comment by woogerboy21** [comment]
This is no longer a work in progress and should be ready for testing / review.  I added the ability for required featureset settings to be refreshed on config reload which was the last step.

**Comment by woogerboy21** [comment]
@ctrlaltca would you like me to move the getXXXX functions in servatrice over to the settingsCache class or would you prefer to have that done in a separate PR?

**Comment by woogerboy21** [comment]
So far I have tested the following settings for recognition of settings updates and are working properly:
* reg only server requirements
* required feature list
* max users total

**Comment by woogerboy21** [comment]
These types of changes may ultimately lead to having a more dynamic based server allowing for things like room changes etc without having to bring down the server .... some day.... maybe .

**Comment by ZeldaZach** [comment]
@ctrlaltca Want a merge before I release?

**Comment by ctrlaltca** [comment]
We-d better merge after release, to test this on a live server for a few time before including it.

**Comment by ZeldaZach** [comment]
Fine by me. Can you come on gitter btw?

**Comment by tooomm** [comment]
Is the server info text in the `server` tab changeable without restarting the server too?

**Comment by woogerboy21** [comment]
> Is the server info text in the server tab changeable without restarting the server too?

Are you talking about the lower box with the information on the lower section of the tab?

**Comment by tooomm** [comment]
Yes exactly. The "Welcome" message with hints, info about maintenance etc.

Reading the old ticket https://github.com/Cockatrice/Cockatrice/issues/211... I'm not sure if it's possible by now anyway. Hmm.

**Comment by woogerboy21** [comment]
@tooomm 
As long as the welcome message is stored in the database it can be updated and then refreshed while the server is online.  Thats functionality that already exists.  What can't be changed on the fly (might be possible with some more research) is the little message that you get when you join a room until the room object is destroyed and recreated.

**Comment by woogerboy21** [comment]
I actually rolled this in on the last system update for the woogerworks server.  Its running live so im not sure how long you guys want to wait to commit it but thought I would mention it.  No rush on merging at all, just a bit of info.

**Comment by tooomm** [comment]
> little message that you get when you join a room

I've no idea what you mean

**Comment by skwerlman** [comment]
> I've no idea what you mean

The green message that is always at the top of chat

**Comment by woogerboy21** [comment]
@tooomm 
image

**Pull request merged**
