### PR TITLE
Game view time 

### PR DESCRIPTION
**Pull request by setti93**
Changed text alignment on the first column to get a better look

### CODE REVIEW

**Comment by tooomm** [comment]
Hello and welcome @setti93 !
We are actually just working on (and mostly agreed already to) a new handling of exactly this...
check out @poixen pr here: https://github.com/Cockatrice/Cockatrice/pull/2071

**Comment by poixen** [comment]
Closing as #2071 addresses this.

**Comment by tooomm** [comment]
Anyway... thanks for putting effort into this! I hope you like our new way of handling this.

Try to implement some pictures next time for better understanding of your visual change and to avoid misunderstanding.

Happy to see you around! You can also join us on [Gitter (link to readme)](https://github.com/Cockatrice/Cockatrice#get-involved-)!

**Comment by Daenyth** [comment]
@setti93 Thanks for the contribution! In the future it will make your life easier if you come by the gitter chat or open an issue ticket before doing a PR - in this case poixen was already changing that area so it was a little duplicated effort. We can definitely help you get set up if you have other areas you want to contribute on.

**Pull request closed without merging**
