### PR TITLE
Buddy stars

### PR DESCRIPTION
**Pull request by poixen**
Buddies will show as a star in the chat.

Please test. Does the chat feel slower? Mine feels slow, though I am 
untitled
overseas.

### CODE REVIEW

**Comment by Daenyth** [comment]
Love it! I'll try it out

**Comment by poixen** [comment]
Known issues:
 + if you see a user with a buddy star, then remove them as a buddy, the buddy star will remain until the next client restart.

**Comment by Daenyth** [comment]
Can you invalidate that user's pixmap cache key?

**Comment by ZeldaZach** [comment]
I was thinking the same thing @Daenyth

**Comment by ZeldaZach** [comment]
Glitch reporting: I'm a mod and it shows me with the buddy star? 

Also... whyy is it black again :( Please just be your branch is behind

screenshot 2015-01-28 19 26 26

**Comment by Daenyth** [comment]
@ZeldaZach Are you in your own buddy list?

**Comment by ZeldaZach** [comment]
Nope... and you can't add yourself anyway

**Comment by Daenyth** [comment]
Something is wrong here. I get this on OSX running from your chat_buddy + master:

wat

**Comment by Daenyth** [comment]
Is this intended to work inside game room user lists? Right now I get a green pawn for someone who was in my buddy list at launch time.

Similarly for the user list displayed on the right side of the chat room - I get the pawn there also.

If this is intended to only be in chat room chat lines for now that's fine, I'm just a little unclear on what the intended scope is.

**Comment by Daenyth** [comment]
Ok I lied about the chat settings problem - it does happen on #644 also but not always? Trying to figure out concrete steps to reproduce.

I don't think it's related to this PR

**Comment by Daenyth** [comment]
@poixen is this PR obsolete in favor of #654

**Comment by ZeldaZach** [comment]
I'm assuming yes and @poixen can reopen if necessary :)

**Pull request closed without merging**
