### PR TITLE
Travis: fix lint msg

### PR DESCRIPTION
**Pull request by tooomm**
Toooo muuuch spaccce

### CODE REVIEW

**Review by ebbit1q — CHANGES_REQUESTED** [review]
this is font specific, maybe you have a font that uses two character widths here instead of one
image

**Comment by tooomm** [comment]
Oh, maybe!
For me on Windows it's always wider, no matter if viewed with Firefox or Chromium

- Travis log:
travis

- GitHub
github

**Review by ZeldaZach — CHANGES_REQUESTED** [review]
It was correct as-is, might be a font issue on your end

**Comment by ebbit1q** [comment]
the :+1: on the other message is using two widths though, but my browser doesn't have a monospace version of that emoji in its fonts somehow so it's never aligned for me.

**Pull request closed without merging**
