### PR TITLE
Add a play face down context menu item when in the hand zone.

### PR DESCRIPTION
**Pull request by kaiserfro**
It seems to me that I've seen several questions about how to play a card face down from your hand.  The only answer is that you must shift+drag or shift+double click the card.  I thought that it was odd that there was no context menu item that allows you to play a card face down.  So I added one.  

I don't know if this omission was intentional or not.  I also don't know what text to use and accelerators to use.

P.S. Lots of changes due to whitespace changes...i had read someplace that Cockatrice's style guidelines were to remove whitespace.  I remove whitespace for other projects too, so my editor automatically strips it.   Hopefully no one minds.

### CODE REVIEW

**Comment by Daenyth** [comment]
Concept is fine.

In general I'd prefer whitespace changes be localized to just the section of code you change because they tend to create merge conflicts for people.

There's also a tab in here, can you use 4-space instead.

Code looks fine, we'll have to test it.

For ui changes it's helpful to add a screenshot for people without the full context to understand it quickly.

**Comment by kaiserfro** [comment]
Ok, here is the screenshot.

play_face_down

Comment on the wording or accelerator used.

**Comment by Daenyth** [comment]
Looks good. I'll try to test it tomorrow night

**Comment by MassCraziness** [comment]
Tested on Debian 7.8, and it works fine. :+1:

**Comment by Daenyth** [comment]
Bug: Playing a spell card face down resulting in playing it face up on the stack. You should set tablerow to always be the top row rather than what the card has.

This might need a servatrice change

**Comment by kaiserfro** [comment]
Issue #331 is supposed to address the location where a facedown card should be played.  As far as I can tell, the behavior between the shift double click and the menu item are the same.  In other words they're both broken.

**Comment by Daenyth** [comment]
In that case, this works as decribed.

**Comment by tooomm** [comment]
@Daenyth the bug you're talking about is filed already in #333
I think this is just an issue if you use the "play all nonlands on the stack by default" option in settings.

**Comment by Daenyth** [comment]
No, it's not related to that setting

**Comment by tooomm** [comment]
Well, I was talking about the "face up on stack when played face down", not the rows the cards get placed.
If you uncheck the setting they will be played face down on the battlefield and don't reveal themselves, they still reveal information about their card type depending on the position/row they get placed.

**Pull request merged**
