### PR TITLE
Cockatrice Docker Image

### PR DESCRIPTION
**Pull request by alfoltran**
## Related Ticket(s)
Scripts for client image generation. I am using this image to run the Cockatrice on Fedora.

## Short roundup of the initial problem
I don't know if this is the best place to store these scripts, but these are the scripts I used to create and maintain the images available in [Docker Hub](https://hub.docker.com/r/cockatrice/cockatrice).

I would also like to pass Cockatrice Docker Hub access credentials. So you can upload the image of the servatrice if you wish.

### CODE REVIEW

**Comment by tooomm** [comment]
Did you see our [Dockerfile](https://github.com/Cockatrice/Cockatrice/blob/master/Dockerfile)? Because you created a new one

**Comment by alfoltran** [comment]
> Did you see our [Dockerfile](https://github.com/Cockatrice/Cockatrice/blob/master/Dockerfile)? Because you created a new one

This is for the client, not for the server.

**Comment by ZeldaZach** [comment]
Looks like a quality change to me. Uncertain if the location is best, but it's a good tool to have around. @tooomm We only provide a servatrice instance on Docker currently. This adds a cockatrice instance.

Would it make sense to merge the two setups together? (I don't know enough about docker to know if that's bad practice)

**Comment by tooomm** [comment]
I assume having a dockerfile-servatrice and dockerfile-cockatrice is also not „allowed“?

**Comment by tooomm** [comment]
@alfoltran we are lacking Docker experience here. Can you have a look again and help us, please?

About Docker Hub:
I think it would be easy to include into our deployment routine.

**Comment by ZeldaZach** [comment]
Could be related to #3974, would love to see consistency across the docker operations we have

**Comment by alfoltran** [comment]
> 
> 
> Could be related to #3974, would love to see consistency across the docker operations we have

There is no relationship here. However I can give my feedback here and say that it would not be a good idea to have two compose.

First, with a little work on the host, docker-compose.yml works on Windows without changes.

Second, if you want to make things easier, just use docker-compose.yml.windows, because it works on Linux too.

**Comment by ZeldaZach** [comment]
If you're willing to get them combined into one file, would be greatly appreciated

**Comment by ZeldaZach** [comment]
Hey @alfoltran just a bump on this PR. Looking to cleanup some PRs and wasn't sure if you were still looking to solve this issue! Reach out https://cockatrice.us/discord if you have any concern or would like to chat!

**Comment by ZeldaZach** [comment]
Closing for now, due to lack of responses and interest. Feel free to re-file if you'd like to see this added

**Pull request closed without merging**
