### PR TITLE
[DO NOT MERGE] Revert "Appveyor: use Qt 5.12 LTS"

### PR DESCRIPTION
**Pull request by tooomm**
Reverts Cockatrice/Cockatrice#3732 for now, see https://github.com/Cockatrice/Cockatrice/issues/3733

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Please don't merge yet, i'm working on a fix.

**Comment by tooomm** [comment]
Awesome

**Comment by ctrlaltca** [comment]
See #3739

**Comment by tooomm** [comment]
https://github.com/Cockatrice/Cockatrice/pull/3739#pullrequestreview-244588628

**Pull request closed without merging**
