### PR TITLE
Add configuration option to send desktop notification on buddy presence

### LINKED ISSUE #1636: Add configuration option to send desktop notification on buddy presence
Notify when someone on buddy list connects/disconnects, toggled by configuration

### PR DESCRIPTION
**Pull request by pmwheatley**
## Related Ticket(s)
- Fixes #1636

## Short roundup of the initial problem

There is no obvious visual indicator when a user in your buddy list comes online.

## What will change with this Pull Request?
- Added notification icon to tab when user in your buddy list comes online. Icon is determined using the  existing `UserLevelPixmapGenerator`.
- Added a configuration setting to optionally show a desktop notification as well.
- Split out the notification related settings to their own section in the settings page.

## Screenshots
Screenshot from 2020-01-13 17-09-03
Screenshot from 2020-01-13 17-17-48

### CODE REVIEW

**Comment by ebbit1q** [comment]
I see no problem just enabling this by default.

**Comment by ebbit1q** [comment]
Notifications are lackluster on gnome either way 
image
that never changed, sigh

**Comment by tooomm** [comment]
Hmm, on Windows 10 it looks like I only get the in client icon shown in the account tab and the Cockatrice icon turns orange to signal something is going on. There is no notification send like for new arrive pm's or spoiler update notification.
This type of notification you are seeing does not work on Windows at all @ebbit1q.

I have the new setting in options checked.

**Comment by tooomm** [comment]
Any idea what could cause this issue on windows @pmwheatley?

**Pull request merged**
