### PR TITLE
Theme manager

### PR DESCRIPTION
**Pull request by ctrlaltca**
This is the first implementation of a theme manager. It’s a rebased and revisited version of #792.
It works like this:
* one theme is a folder with a tree of files and subfolders;
* some themes are bundled with cockatrice's inside the themes directory (c:\program files\cockatrice\themes\...);
 * the user can install new themes in his user profile's directory (%localappdata%\cockatrice\cockatrice\themes\...);
 * default resources (read:images) are still bundled inside the binary, but they're only used if the current theme doesn't specify the requested resource. So, a theme is not forced to contain all the images, it can just override the one it needs (and it will continue to work when we'll add another needed image to cockatrice);
 * cockatrice will default to a theme named "Default", which is an empty dir, so it will use all the builtin resources;
 * the old "zonebg" images have been used to create a few sample themes;
 * the current theme can be changed on the fly;
 * the theme manager will also load the stylesheet file named "style.css" inside the theme's folder.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Images have been reorganized in subfolders and renamed to remove redundant prefixes as per As per @daenyth’s suggestion: https://github.com/Cockatrice/Cockatrice/pull/792#issuecomment-76593730

**Comment by woogerboy21** [comment]
So how does one install a new theme and how does the application detect a new theme is installed?

**Comment by ctrlaltca** [comment]
A theme is a folder inside %LOCALAPPDATA%\Cockatrice\Cockatrice\themes.
Currently there's no "install theme" button, but (in the future) we could make themes redistributable as simple zipped folders, and the "install theme" button will just uncompress the zip in a new folder named after the theme.
The application by now looks for existing themes every time the "settings" window gets opened, but making the "install theme" button trigger a refresh after decompressing the zip is quite simple.
By now i would get the basic theme structure and inner workings in, and later focus on userfriendliness

**Comment by woogerboy21** [comment]
Wait, this does not have the [WIP] title.  Is this done or are there other changes you had in mind for it?

**Comment by ctrlaltca** [comment]
It was almost ready for a prime time, or at least to get comments out of people.
I see i should resolve some conflicts it, will do asap.

**Comment by ZeldaZach** [comment]
How's this coming along? :8ball:

**Comment by woogerboy21** [comment]
How's about now?

**Comment by ZeldaZach** [comment]
If there's a base established, there's no reason not to push this in and let people experiment

**Comment by Daenyth** [comment]
I'd also like to see it get out there.

Maybe as an experimental download alongside the main one?

**Comment by ZeldaZach** [comment]
Sounds good to me, but this needs merge conflicts resolved @Daenyth

**Comment by woogerboy21** [comment]
@ctrlaltca 
Could you take a look at this and fix any conflicts?  I would like to get this tested and rolled in (if possible).

**Pull request merged**
