### PR TITLE
Update sessions table columns for consistency

### LINKED ISSUE #2276: ip_address in cockatrice_sessions is too short
Currently, the `ip_address` column in `cockatrice_sessions` is a `char(15)`, which is fine for storing IPv4 addresses, but it is too short to store IPv6 addresses, which can be as long as 39 chars.

In order to store IPv6 addresses, the `ip_address` column should be changed to a `varchar(39)`.

### PR DESCRIPTION
**Pull request by woogerboy21**
Fix #2276
This update changes two columns in the sessions table to match the
column declartations in the users table.

### CODE REVIEW

**Comment by woogerboy21** [comment]
Though this PR changes the column value(s) to match between the two tables and I have tested these changes on a test box I would like some one that is more well versed in databases to take a look at the column changes and verify that removing the formatting wont be to catastrophic.

**Comment by woogerboy21** [comment]
If I recall correctly the failures for this are expected but @ctrlaltca would be better suited to answer it.  Since the DB version changes the build box DB needs updated to properly test the PR (if memory serves correctly).

**Comment by Daenyth** [comment]
> Schema version 18 does not equal new version 19

You forgot to update one of the values.

**Comment by Daenyth** [comment]
servatrice.sql

**Comment by woogerboy21** [comment]
:+1:  Good catch.  Always seem to overlook that for whatever reason.

**Comment by ZeldaZach** [comment]
Upon my review of literature I could not find a case where `char(X) -> varchar(Y), where Y>X` will cause loss of data.

**Pull request merged**
