### PR TITLE
Reworked a bit mentions/tags support in chat view; fix #791

### LINKED ISSUE #791: Bug in chat with mentions and '['
Using a mention in the same line that contains a '[' will change the '[' to an '@'

@Lamp_oyl We allow [a-z][A-Z][0-9][-_]
becomes
@Lamp_oyl We allow @a-z]@A-Z]@0-9]@-_]

### PR DESCRIPTION
**Pull request by ctrlaltca**

### CODE REVIEW

**Comment by Daenyth** [comment]
I'll try to test a bit tonight if I have time.

**Comment by ZeldaZach** [comment]
This works as expected fully using the issued phrase from the ticket "**We allow [a-z][A-Z][0-9][-]**"

**Comment by ZeldaZach** [comment]
@poixen Can you possibly test this when you get a free moment? I'd really appreciate it as this feature seems to work with what you've been up to lately.

**Comment by ZeldaZach** [comment]
Running a text given by @poixen, I came across an issue:

Test Phrase: **"@username [[Elvish Mystic]] [@username[[ hello @username @@@@hi hi hi ]][[[] @[url]google[/url]"**

Result: 
screenshot 2015-03-31 22 51 04

Where @username, Elvish Mystic, and @username work to start the test phrase, but everything past that is wrong
screenshot 2015-03-31 22 52 49
screenshot 2015-03-31 22 53 42

**Comment by ctrlaltca** [comment]
Lol.. i think i know what's going on here; deconstructing the string from the beginning:
```
@username [[Elvish Mystic]] [@username[[ hello @username @@@@hi hi hi ]][[[] @[url]google[/url]
```
1. @username => mention, ok
2. [[Elvish Mystic]] => card name, ok
3. [ => non-tag bracket, ok
4. @username => mention, ok
5. [[ => start card name
6. hello @username @@@@hi hi hi => card name (@ stripped off)
7. ]] => end card name 
8. [[ => start card name
9. [] @[url]google[/url] => card name ([/] stripped off)
10. (missing end card name)

How to fix 5 and 8?

**Comment by Daenyth** [comment]
I'm OK with this. Really, anyone doing that kind of string is trying to
break it...

**Comment by ZeldaZach** [comment]
It works for the most part, so I'm fine with merging this. @ctrlaltca You can merge it later if you'd like, or you can look into why it's screwy with the test string. Either is fine. Thanks for your hard work!!

**Comment by tooomm** [comment]
Is there some kind of known+tolerated bug list to keep track of this things, append them to release notes or fix them in the far far future?

Just a brain shenanigan...

**Comment by Daenyth** [comment]
When we make releases I try to include a note about known issues that are relevant

**Pull request merged**
