### PR TITLE
Enable parallel compilation.

### PR DESCRIPTION
**Pull request by olegshtch**
## Short roundup of the initial problem

Appveyor is slow.

## What will change with this Pull Request?
- Enables options to parallel compilation and building.

### CODE REVIEW

**Comment by tooomm** [comment]
That seems to speed up the clock! :)

Old PR without the /MP flag took 10min longer to build: https://ci.appveyor.com/project/ZeldaZach/cockatrice/builds/34110709/job/u0o3i52mnb4gfm31

**Comment by ebbit1q** [comment]
I always wondered if we could enable multithreading on those. it's faster than macos now https://travis-ci.org/github/Cockatrice/Cockatrice/builds/713817908

**Comment by tooomm** [comment]
@olegshtch There is also https://github.com/Cockatrice/Cockatrice/issues/3059 slowing AppVeyor down... what's your opinion there? We never managed to make it work.

**Comment by olegshtch** [comment]
@tooomm I've never seen any solution for MSVC caching.

**Comment by tooomm** [comment]
@olegshtch Any idea why compilation time is back up to 22min again (See [here](https://ci.appveyor.com/project/ZeldaZach/cockatrice-k884w/builds/35463905)), even more than before this PR?!
It used to go down by 50% to 11min with your change! 😭

**Comment by ebbit1q** [comment]
it's hard to say what's taking so long, the logs aren't timestamped like travis

**Comment by tooomm** [comment]
I'm not aware of any changes to the build environment at appveyor or that they cut down resources for free projects etc.

**Pull request merged**
