### PR TITLE
Servatrice: refactor signal handling and permit config reloading

### PR DESCRIPTION
**Pull request by ctrlaltca**
This PR refactors the code related to signal handling in servatrice, moving all the related code to a specific new class "SignalHandler".
The second part of the PR enables servatrice configuration reloading without the need of restarting the server.
The server can be told to reload configuration issuing it a SIGHUP (on unix only, of course), or from a new admin command accessible from the "administration" tab in cockatrice.
I've tested this trying to login with an invalid username, then changing the config and issuing servatrice a config reload on the fly.

### CODE REVIEW

**Comment by woogerboy21** [comment]
Nice.  Would you be able to post the sighup command to use?

**Comment by ctrlaltca** [comment]
under linux i suppose that a ```killall -HUP servatrice``` should do the trick. Otherway, get the process pid using ```ps aux | grep servatrice``` and then kill it using ``` kill -HUP pid```

**Comment by woogerboy21** [comment]
Would it be to much trouble to work in a log event about the server configuration file being reloaded when the sighup happens?

**Comment by woogerboy21** [comment]
Awsome thanks :+1: 
This should be ready to merge.

**Pull request merged**
