### PR TITLE
Refactored code and made lines cleaner

### PR DESCRIPTION
**Pull request by poixen**
Before:
before

After:
after

### CODE REVIEW

**Comment by Daenyth** [comment]
:+1:

**Comment by poixen** [comment]
@Daenyth  can you have a look at this? https://travis-ci.org/Cockatrice/Cockatrice/jobs/56738637

**Comment by ZeldaZach** [comment]
@poixen I restarted for you

**Comment by Daenyth** [comment]
:shipit:

**Comment by ZeldaZach** [comment]
@poixen Can you add to release notes when you get a chance as i'm not certain how to list this :)

**Pull request merged**
