### PR TITLE
Server was using message limit for commands

### PR DESCRIPTION
**Pull request by poixen**
Server was using getMaxMessageCountPerInterval over
getMaxCommandCountPerInterval.

Raised command limit from 10 to 20

### CODE REVIEW

**Comment by woogerboy21** [comment]
Could you please add the setting into the servatrice.ini.sample flie as well?

**Comment by poixen** [comment]
Done

**Comment by poixen** [comment]
@woogerboy21 ready for you to install server side, remember your ini too :)

**Comment by ctrlaltca** [comment]
Lol, i should have been quite tired when i added the new option and then used the old one :sleepy:

**Comment by tooomm** [comment]
Should there be an additional message to distinguish between those two?

"You are flooding the **chat**. Please wait a couple of seconds."
and
"You are flooding the **game**. Please wait a couple of seconds."

**Pull request merged**
