### PR TITLE
Added Korean Translation

### PR DESCRIPTION
**Pull request by ideocl4st**
As stated on https://github.com/Cockatrice/Cockatrice/issues/497, I finished translating Cockatrice into Korean.
Also, I added my name on "About Cockarice" dialog in window_main.cpp.

### CODE REVIEW

**Comment by Daenyth** [comment]
This looks fine, although I can't provide any feedback on the quality of translation.

Would you be able to get a second person who speaks fluent korean to sign off on the translations before I merge?

**Comment by ideocl4st** [comment]
I do know some other bilingual Magic players. What would they need to do exactly?

**Comment by Daenyth** [comment]
You/we could provide a compiled build for them to test and visually check, and they could also look at the translation file: https://github.com/ideocl4st/Cockatrice/blob/korean-translation/cockatrice/translations/cockatrice_ko.ts

**Comment by ideocl4st** [comment]
Alright, I guess I can ask a friend of mine...Do you need to do anything to provide a compiled build? My friend only has a Windows computer and I don't have a Windows build environment available.

**Comment by Daenyth** [comment]
@woogerboy21 Can you make a windows build from this branch?

Or @ideocl4st you can try following the windows build instructions on the github wiki on the right

**Comment by ideocl4st** [comment]
@Daenyth He is currently going through the translation file. How would he need to vouch for my translation after he is done editing?

**Comment by Daenyth** [comment]
I'm fine with you relaying it, or he can come comment on here

**Comment by ideocl4st** [comment]
I owe him a lunch now. :P He was more thorough than I thought.

**Comment by ZeldaZach** [comment]
My girlfriend happens to be from Korea and immigrated here a few years ago... I can ask her to look at it if you'd like

**Comment by ideocl4st** [comment]
@ZeldaZach That'd be great - More reviews are always helpful. Just make sure you help her out with magic lingos if she doesn't play Magic ;)

**Comment by ZeldaZach** [comment]
She looked at it and said it was ok. Ready to be merged :)

**Comment by Daenyth** [comment]
I think the travis failure is just a build box issue. Rerunning

**Pull request merged**
