### PR TITLE
[WIP] GH Actions tests

### PR DESCRIPTION
**Pull request by tooomm**
## Short roundup of the initial problem
The 10.13 environment isn't found.

## What will change with this Pull Request?
- Try 10.14 instead.

### CODE REVIEW

**Comment by ebbit1q** [comment]
I expected it to not find 10.14, instead it uses 10.15 which doesn't include this xcode version, it seems like we are dropping HighSierra support...

**Comment by tooomm** [comment]
Interesting that it replaces 10.14 with 10.15, but shows an error message about not finding 10.13 altogether:
```
Check failure on line 1 in .github
@github-actions github-actions / build (ElCapitan)

.github#L1

No runner matching the specified labels was found: macos-10.13.

```

**Comment by tooomm** [comment]
>it seems like we are dropping HighSierra support...

It looks like the lowest GH Actions can offer is macOS 10.14 Mojave (via Xcode 10.3 on macOS 10.15), yes.

**Comment by ebbit1q** [comment]
it seems like macos 10.14 images don't exist as I already thought, I'm going to close this pr.

**Pull request closed without merging**
