### PR TITLE
Add full and short name for card color filters.

### PR DESCRIPTION
**Pull request by kaiserfro**
This addresses one of the parts in #97.  Basically you can enter "green" into the card filter tree and get all of the green cards.

This feels a bit klunky though.  Maybe someone with more familiarity could suggest a place to put a color conversion function like this.

### CODE REVIEW

**Comment by Daenyth** [comment]
I think a series of unconditional string replace would possibly work better. It would also allow putting in 'UB' which I think your one doesn't right now, I need to test it.

**Comment by kaiserfro** [comment]
Ok, this version has got more functionality:
First, I converted the checks to straight QString::replace calls.
But then I added some code to iterate through the filter letters and check them each to the card.  So now you can enter something like "UBG" and find all of those together.  Consequently you can also enter "BLUE BLACK GREEN" into the field and the same happens.

**Comment by kaiserfro** [comment]
Strange, looks like travis had a problem with Mac builds when i pushed this.

**Comment by Daenyth** [comment]
It's been buggy, I'll rerun it

**Pull request merged**
