### PR TITLE
Filter password games consistancy

### PR DESCRIPTION
**Pull request by poixen**
BEFORE
before

AFTER
after

### CODE REVIEW

**Comment by ctrlaltca** [comment]
I see the logic has been inverted (show instead of hide), but since the default value of the checkbox state has been inverted, too, the default behavior is still the same :+1:

**Comment by poixen** [comment]
Yea. Forgot to mention I swapped the logic too.

**Comment by tooomm** [comment]
before:
[ ] show unavailable games
[ ] hide pw games

now:
[ ] show unavailable games
[x] show pw games

?

If yes, I like it. :+1:

**Comment by ctrlaltca** [comment]
@tooomm exactly

**Comment by ZeldaZach** [comment]
If it follows @tooomm's model, I'm fine with this. :shipit:

**Pull request merged**
