### PR TITLE
Consolidate play/pause buttons in replays

### LINKED ISSUE #1661: Consolidate play/pause buttons in replays
Since a replay can never being playing and paused at the same time, the Play and Pause buttons should be consolidated into one button (Play/Pause) whose image changes depending on the state. 
This also might make it easier to implement #1536?

### PR DESCRIPTION
**Pull request by RickyRister**
## Related Ticket(s)
- fixes #1661

## Short roundup of the initial problem
quoting from the issue,
> Since a replay can never being playing and paused at the same time, the Play and Pause buttons should be consolidated into one button (Play/Pause) whose image changes depending on the state.

## What will change with this Pull Request?
- The start and pause buttons are now a single button that toggles when you click it.
- While paused, the button displays the play icon; while unpaused, the button displays the pause icon
  - I could see it being the other way around too. Let me know what you think.

Screenshot 2024-10-15 at 10 39 26 PM
Screenshot 2024-10-15 at 10 39 12 PM

**Known issues:** The play button is still darkened when in the playing state. Ideally, the play button shouldn't change color when clicked, since we are changing the icon to indicate state. However, I spent two days on it and still can't figure out how to get it to not change. Hopefully someone who's better at Qt than me can come along in the future and fix it.

- I also made it so the fast forward button is always interactable. 
  - It made no sense to me why pausing would disable interaction with the fast-forward button, because if you pause while fast-forward is active, the fast-forward is still active after unpausing.
Screenshot 2024-10-15 at 10 40 08 PM
Screenshot 2024-10-15 at 10 43 25 PM

Screenshot 2024-10-15 at 10 40 14 PM
Screenshot 2024-10-15 at 10 40 18 PM

### CODE REVIEW

**Review by ebbit1q — APPROVED** [review]
excellent, thank you!

note that you can add "fixes #1661 " to your pr and it'll automatically close that issue on merge!

**Comment by RickyRister** [comment]
> note that you can add "fixes #1661 " to your pr and it'll automatically close that issue on merge!

in the title?

**Comment by ebbit1q** [comment]
in the pr, I already added it.

**Comment by ZeldaZach** [comment]
```
  /src/cockatrice/src/dlg_settings.cpp:464:51: error: ‘void QCheckBox::stateChanged(int)’ is deprecated: Use checkStateChanged() instead [-Werror=deprecated-declarations]
    464 |     connect(&useTearOffMenusCheckBox, &QCheckBox::stateChanged, &SettingsCache::instance(),
        |                                                   ^~~~~~~~~~~~
  In file included from /usr/include/qt6/QtWidgets/QCheckBox:1,
                   from /src/cockatrice/src/dlg_settings.h:4,
                   from /src/cockatrice/src/dlg_settings.cpp:1:
  /usr/include/qt6/QtWidgets/qcheckbox.h:41:10: note: declared here
     41 |     void stateChanged(int);
        |          ^~~~~~~~~~~~
```

**Comment by RickyRister** [comment]
strange, I don't remember touching that file.

**Pull request merged**
