### PR TITLE
Remove 'syntax = proto2' from .proto files.

### PR DESCRIPTION
**Pull request by Daenyth**
That marker is only recognized by pb3-compatible compilers, meaning that
tools which are otherwise compatible with our files break on them.
Notably, this includes hprotoc (for haskell).

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Related: the original repo for hprotoc seems to be this one: https://github.com/k-bx/protocol-buffers, maybe we could ask them to recognize the ```syntax```` marker or just ignore it.

**Comment by Daenyth** [comment]
Done. https://github.com/k-bx/protocol-buffers/issues/23

**Comment by ctrlaltca** [comment]
Cool. From the google docs i read that:
```
The first line of the file specifies that you're using proto3 syntax: if you don't do this the protocol buffer compiler will assume you are using proto2. This must be the first non-empty, non-comment line of the file.
```
so this change is not supposed to break support for people using the protobuf v3 compiler. :+1:

**Comment by woogerboy21** [comment]
@ctrlaltca 
If I recall correctly , what you say is right but it does throw a bunch of warnings in during compiling and is why the lines were added to clean up output.

**Comment by Daenyth** [comment]
Well, it still does compile, so I'll take warnings here over compile errors elsewhere

**Pull request merged**
