### PR TITLE
Revert "Condensed Card Counter Context Menu"

### LINKED ISSUE #2402: Revert new nested counter menu
Ok this may not be explained correctly, Bear with me. Recently there was a build with the Token creation process changed. Specifically counters. You would select your token, and then put counters on.  Now you have to select color and counters seperately adding a 3rd step to this process... This is not an improvement more like a step backwards. because of this people are using tokens less actually and its very annoying and rude to not use the Actual tokens. We should revert this back to the way it was.

### PR DESCRIPTION
**Pull request by ZeldaZach**
Reverts Cockatrice/Cockatrice#2348
Fix #2402

Based on initial feedback, this feature was not well received. As such, we are reverting back. May consider adding an option to "condense menus" at some point, but it won't be today unfortunately :(

### CODE REVIEW

**Comment by tooomm** [comment]
this fixes #2402

**Comment by Jinxstands4Jinx** [comment]
so when will this be implemented or must you redownload something?

**Comment by Nightfirecat** [comment]
It'll be in the next release, or you can download a build of that commit if you want to start using it sooner.

**Comment by skwerlman** [comment]
i will look forward to the condense option in future builds, then

**Pull request merged**
