### PR TITLE
Search by cmc

### PR DESCRIPTION
**Pull request by Daenyth**
cmcfuckyeah
ohyeahhalfmana

### CODE REVIEW

**Comment by poixen** [comment]
Last image is a nice touch.

:+1:

**Comment by Daenyth** [comment]
Split cards don't have the right cmc (bug in #634)

**Comment by Daenyth** [comment]
I think the split shouldn't get in the way of the merge, I can fix it separately

**Comment by Daenyth** [comment]
Reported #640

**Comment by Daenyth** [comment]
Fixed the split cards

splitit

**Comment by ZeldaZach** [comment]
Works as expected. Good to merge

**Pull request merged**
