### PR TITLE
Chat has focus when starting game

### PR DESCRIPTION
**Pull request by poixen**
When the game starts the line edit now has focus immediately.

### CODE REVIEW

**Comment by tooomm** [comment]
I was wondering the other day why the chat isn't in focus all the time during a game. So much easier and faster chatting since you don't use the keyboard for anything else (except shortcuts)... maybe because the shortcuts wouldn't work in that case?
But if that's true and we focus the chat at game start I can't use shuffle shortcut immediately?
Since I talk to my opponents before the game starts that's what I want to do first or 2nd after the dice roll shortcut. First thing I generally use the chat for AFTER game start is: "ip" "kp" etc. :)

**Comment by Psithief** [comment]
It turns out this is *rather annoying* in a local player game as one typically doesn't want to use the chat at all.

Ex:
* Focusing the chat disables CTRL+A (Attach to card) until one clicks in the text area above the text input.

**Comment by poixen** [comment]
I think the majority of players will benefit. The usual start is: roll, "ip", "kp". I want the players to start playing as soon as possible. This means having the chat active when starting.

**Comment by Daenyth** [comment]
We should be able to not focus during local mode though

**Comment by poixen** [comment]
#708

**Pull request merged**
