### PR TITLE
use utf8 instead of the system encoding

### PR DESCRIPTION
**Pull request by ebbit1q**
## Related Ticket(s)
- Fixes https://github.com/Cockatrice/Cockatrice/issues/4305

## Short roundup of the initial problem
filterString converts strings to the local char encoding, using utf8 might make it work properly on windows.

## What will change with this Pull Request?
- use toUtf8 instead of toLocal8Bit

because this is a windows bug I'm unable to test

### CODE REVIEW

**Comment by ebbit1q** [comment]
in order to be able to make tests https://github.com/Cockatrice/Cockatrice/pull/4580 is now a dependency of this pr

**Comment by ebbit1q** [comment]
a user on discord has been kind enough to verify if this actually works and it seems to have solved the problem

**Review by ZeldaZach — APPROVED** [review]

**Review by tooomm — APPROVED** [review]
It solves the umlaut issue on Windows. 👍

**Comment by ebbit1q** [comment]
@tooomm the build system was changed, I need someone to test if this build runs properly, did you test if servatrice runs?

**Comment by tooomm** [comment]
Oh, I did not realize you merged #4580 (which I did not look at yet) into this PR as well.

>I need someone to test if this build runs properly, did you test if servatrice runs?

I gave it a brief check. The server starts and I can connect to localhost on both ports (I did not change any server settings):
```
Using configuration file:  "C:/xxxxx/Cockatrice/Servatrice/servatrice.ini"
ERROR: can't open() logfile.
Servatrice 2.8.1-custom(9ef2c7a) (2022-02-25) starting.
-------------------------
Authenticating method: none
Store Replays: true
Client ID Required: false
Maximum user limit enabled: false
Accept registered users only: false
Registration enabled: false
Reset password enabled: false
Auditing enabled: true
Audit registration attempts enabled: true
Audit reset password attepts enabled: true
Adding room: ID= 0 name= "General room"
Starting status update clock, interval 15000 ms
Starting server on host "0.0.0.0" port 4747
Server listening.
Starting websocket server on host "0.0.0.0" port 4748
Websocket server listening.
Idle client timeout value: 3600
Set required client features to: QMap(("2.7.0_min_version", false)("2.8.0_min_version", false)("client_id", false)("client_ver", false)("client_warnings", false)("feature_set", false)("forgot_password", false)("idle_client", false)("mod_log_lookup", false)("room_chat_history", false)("user_ban_history", false)("websocket", false))
-------------------------
Server initialized.
```

**Comment by ebbit1q** [comment]
yes, that is expected, it is not actually loaded if not found, the logfile error is also funky, but it's working as expected according to you so I'll move ahead and merge https://github.com/Cockatrice/Cockatrice/pull/4580 :+1: thanks

**Pull request merged**
