### PR TITLE
Fix windows size growing out of screen; fix #1144

### LINKED ISSUE #1144: Maximizing screen
This is still an issue and it keeps putting the chat box under my taskbar it does this whenever i Sideboard for a game or when ever i check the "Account" tab.i have to minimize athen remax each time, and when i am done side boarding it does it again when the game starts.

### PR DESCRIPTION
**Pull request by ctrlaltca**
We had two different problems here:
 1. in the accounts tab, the avatar image had no limits in size; it's now constrained to 400x200 to avoid the image making the windows grow out of screen. The same code is used in the "user" popup.
 2. in the game tab, the card preview on the right could cause the splitters size to grow out of the screen. The old widget has been replaces by the new cardframe introduced in #1137, that fixes the issue.

How to replicate the problem in game with the old card preview widget:
 * switch the widget to "image only" mode
 * move the splitter up, and make the players/chat boxes as wide as possible
 * switch the widget to "image and text" mode: the card preview hioght will grow, pushing the other two widgets out of the screen.

Note: this PR avoids the splitter from getting a wrong value, but if it already has a wrong value as described in #1144, you probably need to reset the splitter size to a sane value manually.

### CODE REVIEW

**Comment by LestatTheDarkPrince** [comment]
I changed my image and resized it slowly cutting the edges. and now it does not do it so i guess i have to use a smaller image to make it work tight.

**Comment by ZeldaZach** [comment]
I'm a fan of this change, but I see two small issues.

1) The users in room bar seems to have a slider now, which it didn't before.
screenshot 2015-06-19 23 20 38

2) If you attempt to move the slider between the card image & room bar list too high, it will overtake everything and not allow for resize. (Same issue happens for description & both)
screenshot 2015-06-19 23 22 21
screenshot 2015-06-19 23 22 29

**Comment by LestatTheDarkPrince** [comment]
Also i am noticing that text Text are where people type what they are doing
or it logs your actions is behind. it will keep up with phases but it will
not advance with things correctly.

**Comment by ctrlaltca** [comment]
The splitter was already there:
old style
basically it's a chest of three drawers, where the drawers can be resized and even collapse if the other 2 are taking up all the space.
Imho the ability to hide the chat or the card preview by collapsing it useless, or even dangerous for users accidentally doing it.

**Comment by ZeldaZach** [comment]
So should we just leave it as is then?

**Comment by ctrlaltca** [comment]
making the items noncollapsible, and maybe make the minimum height of the players list smaller (down from 60 to 40px => from 3 to 2 users)

**Comment by ctrlaltca** [comment]
Is this in an acceptable state now?

**Comment by ZeldaZach** [comment]
Good to go! :shipit:

**Pull request merged**
