### PR TITLE
Added text line about default sets selection in Oracle

### PR DESCRIPTION
**Pull request by tooomm**
I strongly felt the need for some kind of information about this.

No sure if there is any huge impact with translation...

Thoughts?

### CODE REVIEW

**Comment by ZeldaZach** [comment]
It will render all current translations of that phrase outdated and incomparable, but at this point I don't see a need for this update to the Oracle tool as nobody really cares which sets are defaulted to in my opinion... I could always be wrong though

**Comment by ideocl4st** [comment]
Translator here.
As far as I know the Oracle tool does not have an option to change language and it is not being picked up by ts files.

**Comment by Daenyth** [comment]
It has separate ts files but maybe we're not exposing an option to select lang

**Comment by ZeldaZach** [comment]
If we're not doing language support for Oracle, which I find somewhat unnecessary due to the BASIC nature of it... is this needed?

**Comment by tooomm** [comment]
@ZeldaZach what do you dislike about explaining what the program actually does for you or to first time/unexperienced/... users?

It should be as easy as possible for everyone to use, doesn't it?

**Comment by ZeldaZach** [comment]
Hmm, not a terrible idea @tooomm

**Pull request merged**
