### PR TITLE
Updated ready/not ready

### PR DESCRIPTION
**Pull request by poixen**
Old
old

New
new2

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I approve of this. Anyone else?

**Comment by Psithief** [comment]
It's not as immediately recognisable for the colourblind, so I don't know why you'd want to change it.

**Comment by poixen** [comment]
cb
@Psithief what is not immediately recognizable?

**Comment by Daenyth** [comment]
The shapes are more similar now than before

**Comment by Daenyth** [comment]
Personally I think it's still OK even with that, barring feedback from
people who are colorblind

**Comment by poixen** [comment]
My line of thought was; I want something cleaner and more uniform.
Also that original tick is horrific, you should look at it in inkscape.

**Comment by ZeldaZach** [comment]
Maybe we can have a color blind setting to change all images around to a different, easier to see set?

**Comment by Daenyth** [comment]
I'd rather address colorblindness through better theme support

**Comment by littleaj** [comment]
A compromise could be made by replacing one of the outer shapes with a contrasting shape.

For example, the **ready** state would be represented by a white check surrounded by a green circle and the **not ready** state by a white X enclosed in a red square (or octagon).

**Comment by poixen** [comment]
It feels like this is being made into more of an issue than it should be.
We are not just using two colored circles to represent ready/not ready, there is a tick and a cross as a symbol for those with visual impairments.

**Comment by tooomm** [comment]
I understand the objections.
Colorblind people might just see two circles and they might have problems to distinguish between the checkmark and the x inside. If we can make the X bolder inside the cirlce that helps maybe.

**Comment by Daenyth** [comment]
I think it's fine as is

**Comment by poixen** [comment]
@Daenyth Its fine as it is now without any changes, or the PR is fine and can be merged?

**Comment by ZeldaZach** [comment]
So is it the "new" one from the top comment with the red/green? If so, then I'm happy with it to be merged

**Comment by Daenyth** [comment]
Merge it

**Pull request merged**
