### PR TITLE
Removed the loading and saving of the user name and game description

### LINKED ISSUE #576: Filter for games list in "server room" and in "user's games" share the same save settings
I prefer different filters applied/saved to these two completely different features.

In the room with all games listed ("Chat Room" on wooger server) I want to filter for draft games not yet in progress or some other particular thing, in the user's games list (right click on a user --> "Show this user's games") I want to see all games, including the ones in progress for sure!
It always destroys the other settings and automatically saves the "wrong" ones, so its a doom loop if you happen to use both from time to time. :)

I'm not certain if we need the saved feature for the "Show this user's games" dialog at all. Just show all games by default... that's what you want and expect from this option.
Even a high frequent player with 2 ongoing games in parallel, 2 dead drafts room and a game room for chatting with friends is not confusing in this case.
You can still use the filter if you want/need to (without storing changes to the filter!)

### PR DESCRIPTION
**Pull request by kaiserfro**
Fixes #576

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I'm fine with this :+1:

**Comment by Daenyth** [comment]
This seems reasonable. @poixen do you have an opinion? If you're OK with it let's merge

**Comment by tooomm** [comment]
Not 100% sure what this is exactly about and what this change will interact with. Just reading description and extrapolating the impact. :)

I do solely draft and sealed games and used to use "ktk" as filter in description to filter out all these cubes etc. All day long.
So when this gets merged and I restart cockatrice all filters are there expect for the ktk description and I need to reapply it every time?

Not sure what this is about to help with anyway. I think you don't get my point then in #576. :)

**Comment by kaiserfro** [comment]
Perhaps the fix went too far.  Only the user name filter should be removed from the save filters and keep the game description filter in the saved set.

Would everyone agree to that?

**Comment by tooomm** [comment]
That's just my use case with the description thing, don't know about others...

@kaiserfro But still I don't get in which way either one of this changes (description or user name filter) are related to my initial issue. If I need to clarify myself please tell me. :)

I just retested and realized when you change the filters in the "show this user's games" dialog window it won't override the ones in the games list filter of the server. But will the other way around.

**Comment by kaiserfro** [comment]
Ok, the fix that I put it should be fixed to not save the filter for the user filter.  It should be saving the game description though, so I'll make that change when i get a chance.  I did not realize that you were using the other filter method, where you can right click on a user in the user list, select the "Show this user's games" item and get yet another filter window.

This seems totally unnecessary.  Having a separate window for this seems redundant.  I think the menu item should simply set the filter for the main games filter.  Does that seem reasonable?

**Comment by Daenyth** [comment]
No, because the filter view is in a room and the user's game may not all be in the same room

**Comment by kaiserfro** [comment]
Of course.  So the adjusted fix should save the game description filter but not the user filter.  Looking deeper,  the user game dialog uses the same game selector as the main room selector,  so the filters should match with the addition of the user. 

@tooomm is this closer to your expected behavior?

**Comment by ZeldaZach** [comment]
@tooomm Any opinions?

**Comment by tooomm** [comment]
@kaiserfro Not quite sure. We now have a better filter for the games in a room. I Like that.

But what I really expect the "show this user's games" right-click-option to do is this:
- open a new window (like it is now - well, actually a bigger one since right now you can't see much information about the games. But that's the reason why you actually opened this window...)
- search for all kind of games, with all titles, from all creators etc. this users has joined (or created himself), just everything. Including password protected, unavailable etc.pp. **by default**

- therefor don't load the stored options from the "filter all games in this room" for this particular right click on a user option and use other default settings for this special filter. Don't save them back. Or make it a separate storage. So that these two filters don't interact with each other.

You can then customize your filter for the games in a room as you like/need and still get a useful filter for all games of a single user with no weird interaction of both features.

**Comment by Daenyth** [comment]
I agree that the use games window shouldn't use stored settings but instead have a default set. Adding a load settings Boolean option to the constructor is probably the right way, them the code creating the window can just set the filters itself to be specific to the user

**Comment by kaiserfro** [comment]
Ok, I've made the additional constructor changes that @Daenyth mentioned.  Hopefully this helps move this in the right direction.

**Comment by Daenyth** [comment]
I don't see them in this branch

**Comment by kaiserfro** [comment]
Ok, fixed it, I was working in the airport on layover, and missed the fact that i was on the wrong branch.  It should be there now.

**Comment by ZeldaZach** [comment]
Layover? Were you stuck in NY during the storm?

**Comment by kaiserfro** [comment]
No. Flying from SEA to SNA, had a stop in SFO on the way...i had an hour+ to kill, so i played around with this code.

**Comment by Daenyth** [comment]
I'm not sure why the diff is showing up like this right now...

**Comment by ZeldaZach** [comment]
I feel this might've caused a regression of some kind with viewing a user's games 
screenshot 2015-02-05 21 36 17

**Pull request merged**
