### PR TITLE
Buddy stars

### PR DESCRIPTION
**Pull request by poixen**
Buddies will now be seen as stars in the chat

buddies

### CODE REVIEW

**Comment by Daenyth** [comment]
Code looks nice. I'll test it out

**Comment by ZeldaZach** [comment]
Tested and works as expected and listed above ^

I'd really like to see this manifest itself over into the users online list, in game list, buddy lists, etc

**Comment by Daenyth** [comment]
This is a good stepping stone to that

**Comment by Daenyth** [comment]
Can you pull master into this

**Pull request merged**
