### PR TITLE
Counter expressions

### PR DESCRIPTION
**Pull request by basicer**
## Short roundup of the initial problem
- You cant get the middle click menu for counters with a track pad
- Math is hard.

## What will change with this Pull Request?
- Shift+Clicking a counter will show the middle click menu.
- When setting a counter value, you can type a math expression in the box and the counter will be set to the result.

### CODE REVIEW

**Comment by skwerlman** [comment]
Is it possible to reference the current value of the counter?

**Comment by basicer** [comment]
Yup, the current value is x.

**Comment by ebbit1q** [comment]
Err? Why can't you middle mouse button on trackpad? isn't it triple tap everywhere? I can do this just fine.....

**Comment by ctrlaltca** [comment]
> Err? Why can't you middle mouse button on trackpad? isn't it triple tap everywhere? I can do this just fine.....

On macs the "three finger tap" is tied to a useless "lookup" function. The shift+click addition can be quite useful there.

**Comment by tooomm** [comment]
Do we want to let the user know that he can do calculations?
There is no exposure of this feature in the interface yet, right?

**Comment by basicer** [comment]
I suppose we could put it in the tips and tricks dialog.

**Comment by tooomm** [comment]
Haven't thought about that one :)

That would go here:
https://github.com/Cockatrice/Cockatrice/tree/master/cockatrice/resources/tips

Do you want to include that in this PR as well?

**Comment by ZeldaZach** [comment]
Should be included in the PR since it's such a big change. Re: tom's comment on new tip dialog

**Pull request merged**
