### PR TITLE
Webclient: make account fields more user friendly

### LINKED ISSUE #2310: Extraneous / Debug fields on Web Client Account Tab
The following fields appear on the Account tab of web client (current version @ woogerworks, Windows 7 / Chrome):

Gender: GenderUnknown
id: -1
serverId: -1

Missing features
mod_log_lookup
user_ban_history

### PR DESCRIPTION
**Pull request by ctrlaltca**
Fix #2310

### CODE REVIEW

**Comment by woogerboy21** [comment]
Should the privlevel location mimic the non-web client syntax (userlevel | privlevel syntax) ?
I also didn't see anything addressing the missing features.  Was that an one of the issue in #2310 ?

**Comment by ctrlaltca** [comment]
> Should the privlevel location mimic the non-web client syntax (userlevel | privlevel syntax) ?

I'm not a real fan of the `|` character, but more generally i have no preference on one or the other syntax;

> I also didn't see anything addressing the missing features. Was that an one of the issue in #2310 ?

How should i solve that? just hiding the missing features list?

**Comment by woogerboy21** [comment]
> How should i solve that? just hiding the missing features list?

I don't care if they are showing myself.  But wasnt sure what others opinions are.  Maybe @tooomm might have a suggestion?  Maybe @tritoch since he opened the issue?

**Comment by tritoch** [comment]
I don't have a strong opinion, hiding seems fine?

**Comment by tooomm** [comment]
The gender concept is dropped, the field can be completely removed as we don't support it in the client anymore too --> https://github.com/Cockatrice/Cockatrice/pull/1955

The privlevel should be shown the same as in the client. 

Hmm, about missing features list... we don't have that information anywhere else in the webclient and the user don't get informed about it via popup as in the client.
Can we move that to the login tab maybe? Display current server related missing features there while connected?

**Comment by tooomm** [comment]
I don't think so?

There is still an open question from ctrlatlca regarding the missing features list.
And the privlevel information is still displayed differently than in the normal client.

**Comment by ctrlaltca** [comment]
Thank you @ZeldaZach for the commit.
About the missing feature list: i don't see a good reason to remove it, at least until the webclient reaches feature parity with cockatrice.
About the userlevel and privlevel label: the webclient is not meant not be a 1:1 clone of the cockatrice UI, and imho the current way the privlevel is shown in cockatrice is.. improveable.

I'll merge this as it is this right now, it's time to move on and start to work on fixing something more important than labels..

**Pull request merged**
