### PR TITLE
No need for [url][/url]

### PR DESCRIPTION
**Pull request by poixen**
No longer need to use the [url] tags to add **HTTPS** links. I want to
only link to "secure" site by default, hence only https.

Users can still use [url] tags if they want to.

The ENTIRE chat  code needs to be rewitten, as it is just packing more
code upon code. It can be done in another PR though. This just gets the
base working feature in place.

This example was produced without the use of [url] tags

exampleofurl

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Based on how users can still use the `[url]` tag set, I don't see why we have to default to not allowing "not-secure" links.

In my opinion, I think anything that starts with `https`, `http`, or `www.` should auto link.

**Comment by Daenyth** [comment]
I'm also not sure I file the rationale for https only

**Comment by poixen** [comment]
I have updated this to use https, htttp and www

**Comment by ZeldaZach** [comment]
Cool, let me try this out!

**Comment by tooomm** [comment]
https://google.com doesn't get converted to https://**www.**google.com
same for http://google.com

that might be a problem for some sites.
remember the wooger site just being accessible with **www** not too long ago.

**Comment by Daenyth** [comment]
Yeah, we shouldn't tack on any modifications to the urls

**Comment by tooomm** [comment]
- if people copy a link from a browser it has all information needed
- if people write it by hand they wont use `http://xyz.com` and just go with `www.xyz.com`

it's fine i think.

**Pull request merged**
