### PR TITLE
update msg rework

### PR DESCRIPTION
**Pull request by tooomm**
## Short round-up of the initial problem
- some strings used to be messed up in transifex:
tx strings
- https://github.com/Cockatrice/Cockatrice/pull/2504/files#diff-68c33782ee685fda6ebc3cc66405a16aR114 was not displayed (Label inside QMessageBox)

## What will change with this Pull Request?
- added missing tr() string
- split content and formatting (get rid of translation strings with html tags, formatting and arguments),
modularized the strings into smaller parts as a result
- rephrased messages for better visibility and readability,
tried to uniform messages and still stress the important parts for the user

`\n` is no problem and gets actually recognized as linebreak by transifex. It also tells users to use `Return` in this spot.

## Screenshots
Some example screenshots:
- before:
old-available
after (development snapshots):
new-version
after (stable releases):
new-available

### CODE REVIEW

**Comment by tooomm** [comment]
Question:
- I'm not sure if both show up here... I guess it's just the QMessageBox title.
Can/should we remove setLabel there?
https://github.com/Cockatrice/Cockatrice/blob/e04010f00b18ac2c7d099d697d3afe29a09b4ffa/cockatrice/src/dlg_update.cpp#L176-L177
- Same for some other locations in that file. L195+196 or 181+183 for example

**Comment by ZeldaZach** [comment]
@tooomm The setLabel() in those situations sets the header of the dialog that pops up

**Comment by tooomm** [comment]
I'm not so sure:
updateerror

setLabel is `Error`. But the headline which show up is `Update Error` and it's defined within " QMessageBox".

**Comment by ZeldaZach** [comment]
Weird, I"m not sure. We can address it in a later PR

**Comment by tooomm** [comment]
We can also just fix it now. :P

It just needs very little input from somebody with better qt knowledge (or sb who understands the qt docs). Not even 5mins of work I guess.
"A stitch in time saves nine."

I'm pretty sure if we don't do it here it'll stay around for a very long time and translators need to deal with dead strings. ;)

**Comment by ctrlaltca** [comment]
Is this ready to go?

**Comment by tooomm** [comment]
There are two titles set for the dialogs, but it looks like just the one in QMessageBox is used, so we end up with unneeded translation strings.
https://github.com/Cockatrice/Cockatrice/pull/2672#issuecomment-298369030

Do you know if it's necessary to do it twice? @ctrlaltca

**Comment by ctrlaltca** [comment]
> setLabel is Error. But the headline which show up is Update Error and it's defined within "QMessageBox".

`setLabel("Error");` is called on the update dialog, not on the popup message. It updates the status label in the middle of the update dialog: https://github.com/Cockatrice/Cockatrice/blob/e04010f00b18ac2c7d099d697d3afe29a09b4ffa/cockatrice/src/dlg_update.cpp#L171

That setLabel call misses the "tr()", so it needs to be fixed anyway.

**Comment by tooomm** [comment]
done and rdy now

**Pull request merged**
