### PR TITLE
Creatures can now have power less than -1

### PR DESCRIPTION
**Pull request by poixen**
Addresses issue from #934

### CODE REVIEW

**Comment by tooomm** [comment]
not working on dddaec1, used just single `ctlr+"-"`'s and `ctrl+"+"`'s

token

**Comment by poixen** [comment]
@tooomm its a server side change, so wont work in MP yet, have you tried in SP? Works for me in SP.

**Comment by tooomm** [comment]
Ok, it's working in single player.

But there is a weird interaction with normal cards.
If you use it for normal creatures (not that uncommon actually), it starts with strange inconstant values.
Increasing power of any fresh creature will make it 0/0
Lowering power of any fresh creature will make it -2/0
Increasing toughness of any fresh creature will make it -1/1
Lowering toughness of any fresh creature will just write the card name to chat.

**Comment by tooomm** [comment]
It's working on backup server.

**The other issue with weird numbers is still valid.**
BUT just if you pull a card from the library to the battlefield. If it happens to be a creature there are no power and toughness values applied to the card and the strange things described above will happen.

**Comment by poixen** [comment]
This is known, if you move a card from the lib it doesnt show the PT. 

I always thought that was sopposed to happen. If not I can PR in another fix.

Its not related to this PR.

**Comment by tooomm** [comment]
I guess it's ok, no fix needed. If you happen to play cards from the top of your library, you mostly have to decide between several or they get revealed/exiled first. So you use the stack in between most of the time.

**Pull request merged**
