### PR TITLE
Updated reveal zone check boxes

### PR DESCRIPTION
**Pull request by poixen**
I saw in some images from other platforms it can take up alot of space.
Made the boxed horizontal, rather than vertical.

image

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I like the idea. Nice job!

**Comment by ctrlaltca** [comment]
:+1:

**Comment by ZeldaZach** [comment]
Testing this... some issues
screenshot 2015-05-02 20 56 31
screenshot 2015-05-02 20 56 26

**Comment by poixen** [comment]
What's the issue? For pile view to be enabled to need sort by type checked.

**Comment by ZeldaZach** [comment]
@poixen The text boxes aren't aligned like your initial image; the "shuffle when closing" isn't aligned vertically with "sort by type"

**Comment by poixen** [comment]
Must be a *NIX issue. If that's the case I can't really do much. It's still an improvement, even if your OS does add a stupid amount of vertical padding.

**Comment by ZeldaZach** [comment]
This is good as it is for now, but can be improved upon in the future.

**Comment by tooomm** [comment]
I'm also on win. Why do I have the same layout than Zach on his mac, but it's working fine for poixen on win? (see his first post)

I'm on win 8.

**Pull request merged**
