### PR TITLE
Show password games by default

### PR DESCRIPTION
**Pull request by Daenyth**
New users find this really confusing. Old users can use the fact that we remember filter settings to still hide them.

This PR toggles the "show password protected games", unchecked by default to be "Hide password protected games" unchecked by default.

### CODE REVIEW

**Comment by Daenyth** [comment]
Worth noting: Clear filters sets it to showing password games.

**Comment by ZeldaZach** [comment]
Works as expected and good to merge

**Comment by tooomm** [comment]
Wasn't able to test this earlier...

It used to be **unavailable games hidden + pw-protected games hidden** by default with these fields/wording:
[ ] Show unavailable games
[ ] Show password protected games

Now it's **unavailable games hidden + pw-protected games shown** by default with these fields/wording:
[ ] Show unavailable games
[ ] Hide password protected games

----

But why mix things up, confuse people and make it more difficult to understand/use because you need to think the other way around?
As you wrote the intention was to "show password games by default", so why not just tick the box by default and keep the consistent, straight and simple wording?
[ ] Show unavailable games
[x] Show password protected games

**Comment by Daenyth** [comment]
I'll reorganize it a bit

**Pull request merged**
