### PR TITLE
Multiple background images on all zones

### PR DESCRIPTION
**Pull request by fdipilla**
## Related Ticket(s)
- Related to #3985

## Short roundup of the initial problem
Now you may have a different tablezone background image for each player but not different handzones, playerzones or stackzones.

## What will change with this Pull Request?
With this you can have a different handzone, playerzone and stackzone background image for each player.

### CODE REVIEW

**Comment by ebbit1q** [comment]
this seems to be working fine for me
image
when will this be ready for review?

**Comment by fdipilla** [comment]
I was having a similar issue than what is shown in your screenshot, notice the mismatch between the 'Player 1' name and the zone number 2, the same with 'Player 2'.
I was hoping to take a look at that in the next few days, but maybe it's just me nitpicking.
If you think that the PR is good as is I will mark it as ready for review right ahead.

**Comment by ebbit1q** [comment]
I think it's fine this way, it aligns with the way the background was alterated this entire time, https://github.com/Cockatrice/Cockatrice/issues/2491 is a separate issue btw

**Comment by ebbit1q** [comment]
I propose we merge this and if you want you can make a separate pr for the turn order or background order issue.

**Comment by fdipilla** [comment]
Totally missed that it has its own issue :)

**Review by ebbit1q — APPROVED** [review]
:+1: makes these consistent with the backgrounds, we could consider how we could prevent all this code duplication though

**Comment by tooomm** [comment]
I removed the `[WIP]` tag from the PR title for you as you marked it as "ready" now @fdipilla.

The "Themes" wiki page is also updated already.

**Comment by ZeldaZach** [comment]
Thanks for your hard work helping to improve my project. It's greatly appreciated. If you'd ever like to chat about other improvements, feel free to hit us up on Discord or Gitter :)

**Pull request merged**
