### PR TITLE
Script to add the first admin account

### PR DESCRIPTION
**Pull request by woogerboy21**
Script to add the first admin account to the servatrice database.  Running this script after setting up a servatrice server will add the user account "servatrice" with the password of "password" with admin level access.

### CODE REVIEW

**Comment by woogerboy21** [comment]
This was created per a conversation on reddit.
http://www.reddit.com/r/Cockatrice/comments/2xw0pn/servatrice_user_management/

**Comment by ZeldaZach** [comment]
Seems good to me, but they'd have to run it themselves or would it auto run?

**Comment by woogerboy21** [comment]
They would run this themselves. I don't think the idea was to work anything in automatically with the scripts.  At some point we may want to consider some automated configuration post install.

**Comment by Daenyth** [comment]
Can you start a "Setting up servatrice" wiki page referencing this?

**Comment by woogerboy21** [comment]
@Daenyth   What did you have in mind for the page?  Are you looking for a step by step kind of guide?  With no real user management functionality built into the client I'm not sure how much more there would be than 1. setup database, 2. add default user.

**Comment by skwerlman** [comment]
Perhaps some sort of documentation for setting up web-based registration? I don't know PHP very well, so something like that would be really handy.

**Comment by woogerboy21** [comment]
please please don't take this the wrong way, its not meant to be at all.

We can see what we can do, but with the server not having any built in functionality and no real great documentation until something is written up to help users anyone wanting to run a server and connect it to a database is going to have to take the initiative to learn things like that.

**Comment by ZeldaZach** [comment]
It seems like from the point we're at, all we can really do is document what we change/add as it's just too much to go back and spend the time annotating.

**Comment by Daenyth** [comment]
@woogerboy21 merge when ready

**Pull request merged**
