### PR TITLE
apply clang format to proto files

### LINKED ISSUE #3060: Expand clang-format for proto and js
While #3028 covered `Language: Cpp`

@Daenyth also suggested in https://github.com/Cockatrice/Cockatrice/issues/2183#issuecomment-249416472 to include a style for proto.
Clang-format could also be expanded to cover the webclient written in Javascript!

Interesting link with help/description regarding the different options availabel: https://clangformat.com
Official clang-format documentation: https://clang.llvm.org/docs/ClangFormat.html

### PR DESCRIPTION
**Pull request by ebbit1q**
## Related Ticket(s)
- Fixes #3060

## Short roundup of the initial problem
proto files are not automatically formatted

## What will change with this Pull Request?
- rules that currently define our proto files are added to .clang-format instructions
- clangify will now pick up the proto extension
- the existing files are formatted

### CODE REVIEW

**Comment by ebbit1q** [comment]
I think I'm using a different version of clang-format :joy:

**Comment by ctrlaltca** [comment]
The value of `AllowShortBlocksOnASingleLine` used to avcept only boolean values up to clang 9; from clang 10 it accepts Never/Empty/Always.
IIRC travis is stuck at clang 5.

**Comment by ebbit1q** [comment]
well this displays another problem, if an internal error happens in the command `clang-format x | diff x -` the command diff will exit nonzero and hide the clang-format exit code even with set -o pipefail

**Comment by ebbit1q** [comment]
also it displays the version, it's using version 7, a rare case of foresight on my part

**Pull request merged**
