### PR TITLE
Protobuf Flaggage

### PR DESCRIPTION
**Pull request by ZeldaZach**
https://github.com/protocolbuffers/protobuf/issues/10357

### CODE REVIEW

**Comment by ebbit1q** [comment]
I don't like disabling this useful warning

**Comment by tooomm** [comment]
Other option, but also not ideal: We can mark the debug build to be allowed to fail for now.

**Comment by ebbit1q** [comment]
with the new mac builds this version of protobuf that failed building is no longer used, closing

**Comment by ebbit1q** [comment]
nevermind, it still happens I just didn't see it because the build failed because the runner version got bumped to 12 https://github.com/Cockatrice/Cockatrice/actions/runs/4129708130/jobs/7135613996#step:5:468

**Comment by ebbit1q** [comment]
it seems like they currently have a pr open that will address this, it's been stalled for cla reasons though

**Pull request closed without merging**
