### PR TITLE
Themes: don't use hardcoded extensions on images

### LINKED ISSUE #1507: Card Backs Missing
This has come about due to the theme manager, #1081.

Card backs are loaded from the first sub-directory down in each theme folder and is not acceptable in a .svg format, which is what we've used in the past.
    Ex: (OS X) `~/Library/Application Support/Cockatrice/Cockatrice/themes/Fabric/cardback.*`

Allowing the use of .svg in loading images for themes would be the best fix, but converting it into a QImage is also a possibility (I've experimented with this myself earlier).

### PR DESCRIPTION
**Pull request by ctrlaltca**
Now when loading an image from the theme just specify its name. Its extension will be auto detected.
Fix #1507

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Card backs still are missing with this. Also, this introduced a new issue:

Master:
screenshot 2015-09-12 18 36 59

This PR:
screenshot 2015-09-12 18 37 02

**Comment by ctrlaltca** [comment]
can you try re-running cmake? a file was renamed, resource changed.. maybe it didn't get it

**Comment by ZeldaZach** [comment]
@ctrlaltca I rebuild the build folder and the issue persists...

**Comment by ZeldaZach** [comment]
Also, a lot of images in client have shrunk and are weird now.

Old:
screenshot 2015-09-12 18 47 21
screenshot 2015-09-12 18 47 23

This PR:
screenshot 2015-09-12 18 45 59
screenshot 2015-09-12 18 46 51

**Comment by ZeldaZach** [comment]
Pawns&Flags fixed by above ^

**Comment by ZeldaZach** [comment]
Seems good to me :shipit:

**Pull request merged**
