### PR TITLE
Changes to recommended DL + chat link

### PR DESCRIPTION
**Pull request by tooomm**

### CODE REVIEW

**Comment by aeosynth** [comment]
i blocked this bot but i still get pinged, what do

**Comment by tooomm** [comment]
Sorry for that...
We know that it's not working as intended. it shouldn't do anything with `.md` files, too:
https://github.com/Cockatrice/Cockatrice/blob/master/.mention-bot

There is some problem on their side maybe?
Our configuration should be fine. What about implementation?

**Comment by ZeldaZach** [comment]
I think we should just trash the mention bot

**Comment by Daenyth** [comment]
I'll file a bug report on mention-bot, it seems like it completely ignores the config file.

**Pull request merged**
