### PR TITLE
[WIP] add option for always viewing top card

### LINKED ISSUE #3813: Feature Request: Always reveal top card to me.
Newer cards like Experimental Frenzy and Mystic Forge allow you to look at the top card of your library at any time, essentially meaning it is always revealed to you. The only way to handle this in the client currently is to do `Library > View top cards of library... > 1` every time the top card changes.

It would be nice for players to have an option to enable always revealing the top card to just themselves.

### PR DESCRIPTION
**Pull request by ebbit1q**
## Related Ticket(s)
- Fixes #3813

## Short roundup of the initial problem
see ticket

## What will change with this Pull Request?
- adds the option etc.

## Screenshots

image

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Code looks fine, just needs a minor clanfigy.
There's a minor behavior problem when:
 1. enable "always look"
 2. enable "always reveal"
 3. disable "always reveal"
So probably we want to force disable "always look" when "always reveal" gets changed.

**Comment by ebbit1q** [comment]
Makes sense, but currently the always look doesn't even work.

**Comment by ZeldaZach** [comment]
Any news on this one?

**Comment by ZeldaZach** [comment]
poke @ebbit1q on this PR :)

**Comment by ZeldaZach** [comment]
Hey @ebbit1q want to do anything with this before our next release?

**Comment by omegaula** [comment]
Would really love this to go in, anyway I can help push this along?

**Comment by ebbit1q** [comment]
this pr currently only contains the interface, the implementation is missing. if you'd like to contribute code to this we'd love to help you get set up on our discord.

**Comment by ebbit1q** [comment]
closing in favor of #4238

**Pull request closed without merging**
