### PR TITLE
Recursively search CUSTOM folder for images (i.e. subdirectories)

### LINKED ISSUE #2250: Allow Subfolders in the CUSTOM image folder
<b>OS:</b>
Win 7 SP1

<b>Cockatrice version:</b>
Cockatrice d55e44e

---

<br>

When attempting to add a folder full of custom art for a custom set playtest I had all the images within a subdirectory (Cockatrice\pics\CUSTOM\Dreamscape), however the images within the Dreamscape folder are not detected, meaning I have to place them directly in CUSTOM. 

This is means if I want to have multiple groups of custom images I cannot easily delete or update a single group as all the images end up in a single directory.

I want to propose that sub-directories be supported by the CUSTOM image directory, allowing for easier management of custom content.

### PR DESCRIPTION
**Pull request by ZeldaZach**
Fix #2250.

This will allow for a recursive search through the CUSTOM folder until every image is checked to see if it matches the name of the card in question. If not found, continue like normal. 

Checks subdirectories alphabetically, so if you have 
```
.
├── Bar
│   └── example.jpg
└── Foo
    └── example.jpg
```

The `Bar/example.jpg` will be used.

### CODE REVIEW

**Comment by tooomm** [comment]
Should the same apply to `customsets` folder?

Maybe somebody wants to have folders for different games and such.

**Comment by Daenyth** [comment]
We should use this for custom sets too. 

What happens if I put a symlink to the root directory inside custom? Will this then try to scan the whole file system?

**Comment by ZeldaZach** [comment]
I'll update it to include the custom sets dir, and true about symlinks. I can have it ignore them

**Comment by tritoch** [comment]
Does root take priority over subfolders?

**Comment by Nightfirecat** [comment]
@Daenyth @ZeldaZach I'd rather Cockatrice not ignore symlinks; I can see a use case for storing images on a separate drive/mount and symlinking the directory. I think that most anyone who's savvy enough to create symlinks is also smart enough not to symlink `/` (or otherwise recursive directories like `../`) within the custom sets dir.

**Comment by Nightfirecat** [comment]
That said, that could also be addressed by adding some kind of directory traversal limit&mdash;just stop searching deeper after some number of directories, say 10.

**Comment by ZeldaZach** [comment]
I can try implementing a limit on how far down you can go @Nightfirecat, but do you think that's an optimal idea?

**Comment by ZeldaZach** [comment]
I took a second look at what I've done and what I feel should be done.
I see no reason to have sub-folders for the `customsets` folder. They're all XML databases, why do they need to be sub'd? It doesn't really make sense, nor does it need to be done...

Second, for symlinks I feel that we should allow them, but limit the depth to 4 (`CUSTOM/symlink/dir1/dir2/dir3/image.jpg`) so symlinks that are linked incorrectly don't jump everywhere...

Finally, I feel the current selection algorithm (alphabetically by directory/filename) is the best choice, but I'm open to hearing other ideas on how we should sort the CUSTOM folder.

**Comment by Daenyth** [comment]
I haven't had a chance to review yet, but I'd really like to see logs on load time so that someone can read their debug log and see what cockatrice tried to find, and the results

**Comment by ZeldaZach** [comment]
@Daenyth Can you explain a little bit more on what you mean for the logs?

**Comment by Daenyth** [comment]
As you iterate through directories, log them

**Comment by ZeldaZach** [comment]
I can put a qDebug if you'd like, but it's a bit wasteful imo.

**Comment by tooomm** [comment]
>I see no reason to have sub-folders for the customsets folder. They're all XML databases, why do they need to be sub'd? It doesn't really make sense, nor does it need to be done...

What about that players who do other game as well, or several ones? Pokémon, Yu-Gi-Oh!, Hearthstone...
They might want a folder in customsets for each game to not mess with single pre-release xls's for certain sets or other custom xml's etc. which show up for each game individually. They might even favor that, and don't use a cards.xml at all?
You could also simply move the folder of the game you're about to play to customsets, 

It doesn't hurt to have it anyway?

**Comment by tooomm** [comment]
What happens to "qDebug" and "doing the same in customsets folder"?!

**Comment by ctrlaltca** [comment]
If it's still relevant, open a new ticket describing the needed improvements; "doing the same in customsets folder" doesn't really belong to this PR anyway.
The PR was approved by @Daenyth and stuck for 38 days, i think that the user originally reporting the bug at #2250 will approve being finally able to use this feature.

**Comment by Daenyth** [comment]
Agreed on all counts

**Pull request merged**
