### PR TITLE
Allow undo draw if card was moved within hand

### LINKED ISSUE #326: Bug: Undo draw function fails after rearranging cards
If you draw a card, then rearrange the freshly drawn card in your hand, the undo draw function will not work anymore. (presumably because it can't track the card in its new position.)

### PR DESCRIPTION
**Pull request by knitknit**
## Related Ticket(s)
- Fixes #326

## Short roundup of the initial problem
User could not undo draw if drawn card was moved around within hand.

## What will change with this Pull Request?
- Do not clear `lastDrawList` if the card is moved within hand, only clear once a recently drawn card is moved outside the hand
- Stop doing `lastDrawList.removeAt(lastDrawList.indexOf(card->getId()));` when `undoingDraw == true`, as the card was already popped off the end of the list in line 1086: https://github.com/Cockatrice/Cockatrice/blob/bec02b495299992b4210a8cc3724ca63679d7616/common/server_player.cpp#L1085-L1089

## Open question
How should "undo draw" work from a player/judge's perspective? Right now I think it's technically possible to get into a situation where say cards A, B, C are drawn; A is played, so list is cleared; user draws D; user plays B, which doesn't cause the list to be cleared; user undoes draw D. Should this be allowed?

## Screenshots
[Screen Recording 2020-10-29 at 10.08.02 PM.zip](https://github.com/Cockatrice/Cockatrice/files/5462608/Screen.Recording.2020-10-29.at.10.08.02.PM.zip)

### CODE REVIEW

**Comment by knitknit** [comment]
@ebbit1q what do you think of this change and the open question I have in the description? I don't think it's new or specific to this change, just something I realized as I was thinking about it.

**Comment by ebbit1q** [comment]
if the same player doesn't play any card they should be able to undo their draw, moving cards around is fine and other players should be able to play cards in between even though that's pretty confusing.

**Comment by ZeldaZach** [comment]
As long as playerA does no game actions involving moving cards from their hand to any other zone, I see no reason for the undo to not work.

**Comment by ebbit1q** [comment]
theoretically moving cards into your hand wouldn't break it, actually the only thing that'd break it is moving the specific drawn card out of your hand, but it seems reasonable to disallow it to avoid issues where players can no longer track game actions.

**Comment by ZeldaZach** [comment]
Once cards start leaving/entering the hand, I would call the hand "tainted" and we shouldn't allow a fix in that case. Also, I don't remember, but if I draw 3 cards one at a time, can I undo the draw 3 times? Or does it only work for the latest?

**Review by ZeldaZach — APPROVED** [review]
Tested and audited. This makes perfect sense to me and should be a great change. Will deploy to RR soon.

**Pull request merged**
