### PR TITLE
Refactoring file cockatrice/src/messagelogwidget.cpp

### PR DESCRIPTION
**Pull request by kopcion**
## Related Ticket(s)
- TODO found in code

## Short roundup of the initial problem
Created separate class in order to define phase

## What will change with this Pull Request?
- removed long switch-case from messagelogwidget.cpp file

### CODE REVIEW

**Comment by ebbit1q** [comment]
Thank you for getting to fixing that, you should remove the separate sql changing commits :)

**Comment by ebbit1q** [comment]
Also not marking the functions called "constant" in the code not const is sort of counterintuitive.

**Comment by kopcion** [comment]
About those commits, I have noticed too late, that's why I have closed the PR

**Comment by ebbit1q** [comment]
noone is going to merge it in the time that you are sorting that out, don't stress :)

**Pull request closed without merging**
