### PR TITLE
Parse cmc from json and store in cards.xml

### PR DESCRIPTION
**Pull request by Daenyth**
This is part one of #627 

Part two allows the searching.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Looks fine to me

**Comment by ZeldaZach** [comment]
This adds to the XML file correctly as expected;

```
<card>
    <name>Choking Vines</name>
    <set muId="4511">WTH</set>
    <color>G</color>
    <manacost>XG</manacost>
    <cmc>1</cmc>
    <type>Instant</type>
    <tablerow>3</tablerow>
    <text>Cast Choking Vines only during the declare blockers step.
X target attacking creatures become blocked. Choking Vines deals 1 damage to each of those creatures. (This spell works on creatures that can't be blocked.)</text>
</card>
...
<card>
    <name>Flesh // Blood</name>
    <set muId="368991">DGM</set>
    <color>B</color>
    <color>R</color>
    <color>G</color>
    <manacost>3BG // RG</manacost>
    <cmc>3 // 2</cmc>
    <type>Sorcery // Sorcery</type>
    <tablerow>3</tablerow>
    <text>Exile target creature card from a graveyard. Put X +1/+1 counters on target creature, where X is the power of the card you exiled.
Fuse (You may cast one or both halves of this card from your hand.)

---

Target creature you control deals damage equal to its power to target creature or player.
Fuse (You may cast one or both halves of this card from your hand.)</text>
</card>

**Comment by Psithief** [comment]
You could overload `mana cost` with equality signs.

### Examples

* `=3`
* `<=2`
* `>=6`
* `<5`
* `>7`

**Comment by ZeldaZach** [comment]
Mana cost shows as the default logic gate functions; `AND`, `OR`, etc...

**Comment by Daenyth** [comment]
I'm working on the filter next

**Pull request merged**
