### PR TITLE
CI: Remove EOL builds (Fedora 34 and Ubuntu 21.10)

### PR DESCRIPTION
**Pull request by tooomm**
## Short roundup of the initial problem
- Fedora 34 is EOL
Fedora releases are only patched for 12 plus ~1 month and a new version comes every 6 month, we generally need only the most two recent max.

- Ubuntu 21.10 is EOL

## What will change with this Pull Request?
- Remove builds, related files and mentions in the release template.

### CODE REVIEW

**Comment by ebbit1q** [comment]
I talked with this to zach while we added the fedora 36 build and we agreed to remove it after the next release.

**Comment by tooomm** [comment]
>we agreed to remove it after the next release

Is this still valid?
Two month passed since, there is no release ahead and a new release-blocking issue emerged.

In the meantime, the Fedora release in question is already EOL for a while.
Do you plan on releasing with an outdated Fedora 34 at some point in the future?

**Comment by ebbit1q** [comment]
no, please complete this pr by updating the release template

**Comment by tooomm** [comment]
>please complete this pr by updating the release template

Sure, absolutely missed that. Updated.

**Review by ebbit1q — APPROVED** [review]
thanks

**Pull request merged**
