### PR TITLE
[german-translation-fixes] Use formal you for consistency

### PR DESCRIPTION
**Pull request by Cat-Ion**
All the other translations already do, so I changed this one.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
For translations we use transifex. Why don't you go commit the change there so we can implement it here :)

**Comment by Daenyth** [comment]
@Cat-Ion Thank you for the contribution! As Zach mentioned, we manage the translations on Transifex rather than directly committing them with git.

Here's our landing page for translators: https://github.com/Cockatrice/Cockatrice/wiki/Translation-FAQ

It links to some Transifex documentation about getting started there. If anything is unclear we'd be happy to help you along with it.

**Comment by Daenyth** [comment]
Specifically I think you want to be here: https://www.transifex.com/cockatrice/cockatrice/translate/#de/oracle/40511209

**Comment by Cat-Ion** [comment]
Yup - I went to the wrong translations first (found two strings to correct there, though), and when I saw the one I'd created the pull request for it was already changed. Thanks :)

**Comment by ZeldaZach** [comment]
Thanks for your help @Cat-Ion! Glad to see new faces around here :)

**Pull request closed without merging**
