### PR TITLE
Created migration script

### PR DESCRIPTION
**Pull request by Lachee**
Python3 script that enables automated migration to newer schema. Provides functionally to pause after each iteration and cancel or to continue uninterrupted. Designed to work on linux based systems. Specifically designed with Ubuntu 16 in mind.

## Usage
To use, first create a mysql configuration, with `mysql_config_editor set --login-path=<configname> --host=localhost --user=<username> --password`. This will create a safe configuration for the mysql and prevent annoying messages (also make passwords invisible in console).

Then run the script with `Python3 migrate.py`. The script does not accept any arguments. On screen, it will ask for --login-path (created previous setup), database (normally `servatrice`), starting schema (schema the database is currently on) and if a pause should be made between each migration (for error checking).

### CODE REVIEW

**Comment by Daenyth** [comment]
I suppose this is reasonable, but if we're bringing in python is there any reason not to just use alembic instead?

**Comment by tooomm** [comment]
Would it be useful to have the little explanation on how to use it as comments on top of the file as well?

**Comment by ZeldaZach** [comment]
Is this the most optimal version of the script? Can it be rewritten to be more efficient / compact?

**Comment by skwerlman** [comment]
My thoughts on the script:
- `import os`, not `import os.path`; as is, the script _should_ fail at line 48
- make this work on both py2 and py3 since ubuntu refuses to let py2 die
- add a hashbang so i can just `./migrate.py`
- format the script so it passes `pycodestyle` without errors
- the main loop would be a lot clearer if the migration scripts were gathered and sorted before iterating
- all the inputs at the start should be arguments instead

**Comment by Daenyth** [comment]
You can install python3 on ubuntu just fine, even 16.04 (with a ppa), so 👎 for python2 support - it's non-trivial effort over time, and I'd like to keep scope minimal.

So far no one has answered though, if we are making server operators use python, then why not use alembic to manage the migrations instead of all our hand rolled stuff?

**Comment by ctrlaltca** [comment]
Bash oneliner:
```sh
for i in servatrice/migrations/servatrice_{0000..0099}_*.sql; do mysql -uuser -ppass servatrice < $i; done
```
Imho such a script could be useful if it makes some automated checks, eg:
 * it makes a full backup before even touching the db;
 * it automatically detects the current schema version (`mysql -uroot -p servatrice -sN -e 'select version from cockatrice_schema_version'`);
 * it runs all the migrations queries automatically one by one and it's able to detect if a single query  fails and stop before ruining the db;
 * it refuses to run a migration if it has already been run or if the needed previous ones have not been run.

**Comment by Daenyth** [comment]
> it makes a full backup before even touching the db;

Alembic doesn't do this by default but it could be made to do so

> it automatically detects the current schema version (mysql -uroot -p servatrice -sN -e 'select version from cockatrice_schema_version');
> it runs all the migrations queries automatically one by one and it's able to detect if a single query fails and stop before ruining the db;
> it refuses to run a migration if it has already been run or if the needed previous ones have not been run.

Alembic does all this

**Comment by Daenyth** [comment]
Alternately, skipping python entirely, https://flywaydb.org/

**Comment by ZeldaZach** [comment]
So I'm going to close this PR for the time being. If you ever feel like working with the tools Gav suggested, please do so! Thanks for the time and effort @Lachee :)

**Pull request closed without merging**
