### PR TITLE
Specify the player when triggering a move on a revealed card

### LINKED ISSUE #72: Move card menu does not work in 2 player local game
In version `92ff503` of cockatrice on Windows 7 64bit the "Move" context menu does not seem to work on any cards that belong to the non-active player. 

For example, scrying when it is not your turn you cannot move cards to the bottom of your library.

### PR DESCRIPTION
**Pull request by ctrlaltca**
Fixes #72, #493 
Please have a look at https://github.com/Cockatrice/Cockatrice/issues/72#issuecomment-68182612 for the full discussion.
I'm not so confident with this part of the code, so i'm unsure wether this patch could break something else.
Please hard-review this before committing.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
So, a patch to fix the second problem (change P/T on cards dragged from the opponent's battlefield) has been added.
I tested most of the other commands and they seem to work, and didn't notice any regression in server-game mode.
Anything else that still needs to be fixed?

**Comment by Psithief** [comment]
> Anything else that still needs to be fixed?

#### Moving stolen cards to other zones doesn't work.

Cards dragged from opponent's battlefield:
* must be dragged back to their battlefield before they can be dragged to their graveyard, hand, exile or  library
* Context menu shortcuts of `Move to graveyard` `Move to exile` `Put on top of library` `Put on bottom of library` won't take any action. Following the pattern, the Ctrl+Del shortcut for `Move to graveyard` won't do anything.

I believe the general case for these actions should be to send these cards to their **owner's** (not controller's) graveyard/exile/library zone when the appropriate request is made.

**Comment by Psithief** [comment]
Oh, I just remembered one more thing:
* Player `a` can't set cards to not untap normally while it's player `b`'s turn. There is no workaround for this.

**Comment by ctrlaltca** [comment]
The problem of moving a stolen card to the another player's private zone (eg: graveyard) is a bit complex, since none of the players have the right on making the full move:
 * the original owner of the card has no right on taking back the ownership of the stolen card;
 * the card controller can actually move the card, but has no rights on the target zone (the other player's graveyard)

**Comment by ctrlaltca** [comment]
The "don't untap normally" problems seems to already have been fixed by previous commit, so it's already working in this PR.

**Comment by Daenyth** [comment]
The controller of a card should have permission to put that card into it's owners public zones

**Comment by Psithief** [comment]
What about `Put on top of its owner's library` `Put on bottom of its owner's library` effects?

Would moving it to its owner's zones include the Cockatrice version of the stack?

**Comment by Daenyth** [comment]
stack is public so yes. Hidden zone moves should be handled by the owner, so move to owner's field and then owner can do it.

**Comment by Daenyth** [comment]
The code here looks OK. @ZeldaZach could you please test this, and if you feel it's good, merge it?

**Comment by ZeldaZach** [comment]
I'll look into this later today

**Pull request merged**
