### PR TITLE
Enable Dependabot

### PR DESCRIPTION
**Pull request by tooomm**
## Short roundup of the initial problem
Stuff is out of date

## What will change with this Pull Request?
Check several services for updates automatically and propose PRs
- GitHub Actions
- npm

### CODE REVIEW

**Comment by ebbit1q** [comment]
with submodules you mean just vcpkg right? vcpkg updates a lot and we don't need the latest version of stuff in it that we don't use, we only care about getting like protobuf through it.

**Comment by ebbit1q** [comment]
we also have dependabot making prs for the webclient already https://github.com/Cockatrice/Cockatrice/commits?author=dependabot%5Bbot%5D

**Comment by tooomm** [comment]
That's only for vulnerability patches I think.

There is no general setup available as far as I'm aware. No config file in the repo, too.

**Comment by tooomm** [comment]
In order to move this PR forward, I did not include submodule updates by Dependabot for now.

**Pull request merged**
