### PR TITLE
Option to opt-out of remember game settings

### LINKED ISSUE #1396: Remembering last game values
In one of the recent updates, you guys added a feature where the client remembers what you put in for the last game you made but there's no place in the settings to disable this if we don't like it. It would be great if this could become a checkbox somewhere in the settings.

### PR DESCRIPTION
**Pull request by Fizztastic**
Fix #1396
untitled-1

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Works as expected, my only complaint is the location of the checkbox. Can you possibly move it above the Cancel/Ok/Clear buttons?

screenshot 2015-08-22 15 34 48

**Comment by Fizztastic** [comment]
I tried putting it at the bottom but the way the layout is made it creates a third column on the right.

**Comment by ZeldaZach** [comment]
Can you try putting it below "Description & Players"?

**Comment by Fizztastic** [comment]
> Can you try putting it below "Description & Players"?

Yeah I can do that.

**Comment by ZeldaZach** [comment]
:shipit:

**Pull request merged**
