### PR TITLE
You have been kicked message box

### PR DESCRIPTION
**Pull request by poixen**
Getting kicked from a game will now:
+ Take user to kicked tab 
+ Alert the user with a popup

Popup contains the game name.
 
untitled

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I'm fine with this. Good to merge

**Comment by Daenyth** [comment]
Can you add the game name and number

**Comment by poixen** [comment]
@Daenyth Do you know where to get the game number? This code is in tab_game.cpp. Head is real fuzzy. what about games that have no name, i gather the name is the description?

**Comment by Daenyth** [comment]
I meant description. If you take the tab title that should work

**Comment by ctrlaltca** [comment]
@Daenyth is right, have a look at how ```TabGame::getTabText()``` is creating the tab caption

**Comment by poixen** [comment]
"You have been kicked out of the game: [game name]".
If no game name, then just like it is above.

**Comment by poixen** [comment]
@Daenyth @ZeldaZach I have updated functionality

**Comment by ZeldaZach** [comment]
Works as expected and I like.

**Comment by Daenyth** [comment]
:+1:

**Comment by Psithief** [comment]
**Sanity check:** Does this modal box lock up the entire application, or the entire OS until it's addressed?

I'm just wondering what happens if I'm spectating multiple games and I get kicked out of one of them while watching another.

**Comment by poixen** [comment]
It's modal, by definition you need to click ok.

**Comment by Psithief** [comment]
It's not just restricted to the relevant tab? :(

`<insert research about how modal dialogs are the worst thing ever here>`

**Comment by Daenyth** [comment]
We can look at changing it later. How often are you really getting kicked
though?

**Comment by Psithief** [comment]
Well, same thing if I'm in just the one game but I'm on the chat tab, or deck editor tab, or any other tab. What happens?

**Comment by Daenyth** [comment]
File a ticket for improvement and we can change it later to be confined to
the game tab, there's just no good display for that right now

**Comment by poixen** [comment]
@Psithief Not quite sure what the issue is? As mentioned in the feature description, when you are kicked you are taken to the game tab and shown the modal popup.

**Comment by Daenyth** [comment]
@poixen that's disruptive though, the user doesn't need to address the kick
that moment, it would be better ux to let them deal with it when they see
it rather than interrupt whatever other tab activity they have

**Pull request merged**
