### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by ctrlaltca**

### CODE REVIEW

**Comment by tooomm** [comment]
To prevent a 3 hour codacy scan next time: #2891

**Comment by tooomm** [comment]
You have to pull the new `master` into your translations branch, no `.codacy.yml` there yet: https://github.com/ctrlaltca/Cockatrice/tree/translations

**Comment by ctrlaltca** [comment]
Right, force rebased to current master and repushed commits on top of HEAD

**Comment by tooomm** [comment]
Hmm, that's unexpected. I contacted their support.
After clicking `Details` in the status check here, their interface just sais `analyzed`...

Maybe some error in config: https://github.com/ctrlaltca/Cockatrice/blob/translations/.codacy.yml

**Comment by ctrlaltca** [comment]
I force restarted the analysis..

**Pull request merged**
