### PR TITLE
Add "play top card face down" menu entry to library; fix #762

### LINKED ISSUE #762: no manifest from library (play face down) option
@kaiserfro added a right click entry to the hands menu in #726 

The same entry at the library menu would be great and will make playing the current cards easier.

(i know about shift+dragging from library)

### PR DESCRIPTION
**Pull request by ctrlaltca**

### CODE REVIEW

**Comment by ZeldaZach** [comment]
@ctrlaltca When I press the button, it should assign the face down card a P/T of 2/2.

Also, do we want it to tell me what card I played or no?
What I see: `ZeldaZach puts the top card of his library into play.`
What my opponents see: `ZeldaZach puts the top card of his library into play.`

What I should see: `ZeldaZach puts the top card of his library (Batterskull) into play.`

**Comment by tooomm** [comment]
Rules wise the library is a unknown zone and you don't get to see the top card before you bring it into play. You are just allowed to look at it when it is in play under your control.
So I think that's ok.

**Comment by ZeldaZach** [comment]
Derflippi said it was fine to show the name of the card as you manifest it, so yeah :+1:

**Comment by Daenyth** [comment]
But it's not always manifest - we should prefer the more conservative
option when possible to give the broadest support

**Comment by ZeldaZach** [comment]
Fine by me @Daenyth.

I think we can safely merge this then.

**Pull request merged**
