### PR TITLE
Added fade to games you cant join

### PR DESCRIPTION
**Pull request by poixen**
+ Games you cant join are faded
+ Added faded lock image

untitled

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Tested and good to go. Will merge on travis passing

**Comment by poixen** [comment]
Can we wait for a code review before merge? Also I want @Daenyth s input.

**Comment by ZeldaZach** [comment]
Yup, no problem

**Comment by poixen** [comment]
Closing, am not happy with it. Too many edge cases to work out. Plus I am missing a check to see:
```
if (!(ownUser->user_level() & ServerInfo_User::IsRegistered))
            if (game.only_registered())
```

**Pull request closed without merging**
