### PR TITLE
Add URL to explain message macros

### LINKED ISSUE #267: Document "messages" functionality
It allows users to create chat message shortcuts for use inside a game.

### PR DESCRIPTION
**Pull request by SlightlyCircuitous**
## Related Ticket(s)
- Fixes #267 

## Short roundup of the initial problem
The in-game message macro feature is undocumented and many users don't know it exists.

## What will change with this Pull Request?
- Adds a URL in the Settings>Chat window that links to the [new wiki explanation on message macros](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Keyboard-Shortcuts-and-Message-Macros)
~~- Also edits the link in Settings>Shortcuts since I changed the name (and thus the link) of that article to include info on message macros.~~ The article name has been reverted to not break existing links elsewhere.

## Screenshots
Current:
Screenshot from 2022-11-29 23-34-25

Proposed:
Screenshot from 2022-11-29 23-35-37

### CODE REVIEW

**Comment by ebbit1q** [comment]
I notice you've edited the page name of this wiki page, please don't do that! it changes the wiki link for our existing link to this page on the shortcuts page of the settings!

**Comment by ebbit1q** [comment]
I've reverted your rename of the file, this way the link already in the client right now doesn't stop working, github wikis do not support redirects.

**Comment by SlightlyCircuitous** [comment]
Yeah, sorry about that. I didn't realize that was also linked in settings until I had renamed it; I probably should have just put it back once I noticed. Seemed like you wanted macro documentation to be very easy to find though, so putting it in the title made sense at the time. 

I'll just use the current link in this PR then.

**Comment by SlightlyCircuitous** [comment]
As far as I can tell, I have satisfied the code style issues. Is there something that I need to fix to make it run properly in macOS debug or is that unrelated?

**Review by ebbit1q — APPROVED** [review]
we could also link to the exact chapter of this https://github.com/Cockatrice/Cockatrice/wiki/Custom-Keyboard-Shortcuts#in-game-message-macros , but considering the wiki entry is so small it'd be rather pointless unless your screen is really small.

**Pull request merged**
