### PR TITLE
Ability to rotate player position in game view

### PR DESCRIPTION
**Pull request by mildmongrel**
With the "Player position rotation amount" setting, players can adjust their position in the local game view.  No effect on actual player ordering.  With the default setting of 0 there should be no change to current behavior.

I added this for multiplayer games - in the two-column view the local player always ended up in the bottom left corner.  In 2v2 multiplayer this setting allows players to adjust their "seat at the table".

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I tested this feature and here's my feedback:
+ Having the setting inside the settings panel seems a bit out of there. What if I want to watch one game a certain way and play another a different way? I think this should be implemented in the physical game tab(s).
+ I do like how the rotation works as it will make playing teams easier, but how will others be able to see/replicate your settings so that everybody knows who's with who?
+ Instead of having a rotation as it was made, why not possibly look into a drag/drop feature to move the game tables around inside the game tab, similar to how phones you can drag/drop applications around.
+ Finally, a small word of warning for you is that you made this PR on the `master` branch. Can you try making a sub branch because, as you see, you merged in from upstream which could cause issues for us in the future.

I hope this is helpful to you. Keep up the great work!

**Comment by mildmongrel** [comment]
Thanks for taking a look and testing Zach.

I agree on the settings approach being a bit clunky, but I couldn't find an obvious place to put it in the game tab.  I'll see what I can do here.

I assumed "who's with who" would be negotiated via chat, etc.  I have bigger ideas for multiplayer that would involve some sort of team coordination, but shooting for the lowest hanging fruit I went with a simple client-side view change.  Drag/drop is a great idea, but that would imply changing the turn order which should be dictated by the game creator and server, right?

My bad on the PR on master.  That's me being new to open-source project collaboration.  I'll rework my next PR as a feature branch.

**Comment by ZeldaZach** [comment]
With the drag/drop, I see what you mean on how it would change how the turn orders went.

For the rotation in game, maybe have a button that when pressed would rotate the entire playing field. Seems simple and do-able.



If you hit the button everything rotates 90*.

**Comment by mildmongrel** [comment]
Was thinking the same thing with a button, but I'm struggling with an intuitive place to put it that doesn't clutter.  Also since I'm the first person to request it I doubt it would be worth the real estate.  :)  How about via menu item?  Game->Player X->"Rotate to bottom left"

**Pull request closed without merging**
