### PR TITLE
New logo for changed tab

### PR DESCRIPTION
**Pull request by poixen**
untitled

### CODE REVIEW

**Comment by Daenyth** [comment]
The icon looks nice. :+1:

**Comment by poixen** [comment]
This good to merge now?

**Comment by ZeldaZach** [comment]
As long as it doesn't break down to fonts like it did before, seems good to me

**Comment by poixen** [comment]
I have converted it to a path, it should be fine. I gavent heard any issues yet.

**Comment by Daenyth** [comment]
It works fine for me

**Pull request merged**
