### PR TITLE
travis: update macos 10.15 images

### PR DESCRIPTION
**Pull request by tooomm**
## What will change with this Pull Request?
- use most recent (non-beta) Catalina (10.15) image available on travis
- high sierra is still on the latest, no changes needed

### CODE REVIEW

**Comment by ctrlaltca** [comment]
You could even switch to catalina, it should support all the macs that mojave supports.

**Comment by tooomm** [comment]
Will check, expected it to cut older macs off.

**Comment by ZeldaZach** [comment]
I'm fine with the bump, as we don't lose anything

**Comment by ebbit1q** [comment]
Which versions of macos are supported by this build?

**Comment by tooomm** [comment]
With this PR we build on
- High Sierra: https://github.com/Cockatrice/Cockatrice/blob/master/.travis.yml#L120 
- Catalina: https://github.com/Cockatrice/Cockatrice/blob/master/.travis.yml#L162

So for releases, the deployed dmg is unchanged and still supports 10.13+ (should still run on 10.15, but without Dark Mode support).
The zipped dmg is now 10.15+ (instead 10.14+).

**Comment by ebbit1q** [comment]
So we dropped dark mode support from 10.14?

**Comment by ZeldaZach** [comment]
All machines that can run 10.14 _can also_ run 10.15, so they'd just have to upgrade

**Comment by ebbit1q** [comment]
Yes, but they should know that they need to upgrade as well.

**Pull request merged**
