### PR TITLE
[WIP] Move top card to exile/graveyard binding

### PR DESCRIPTION
**Pull request by jjcard**
## Related Ticket(s)
- Keybinding part of #2618 

## Short roundup of the initial problem
 - If it's a lot of one-off setting of top card to graveyard or exile, don't want to have to pick each time

## What will change with this Pull Request?
- adds keybinding for sending 1 card from deck to graveyard or exile. Adds keybinding Settings page element for each.

## Problems with the implementation
- So can't seem to get the keybinding to work. I tried changing it so it would do the same 'pick number of cards' as the UI element to see if it somehow defaulting to 1 wasn't working, still didn't work. 
- Also wanted to ask what you think the text for the settings page should be, just kind of threw it togther
decktobindingsettingspage

### CODE REVIEW

**Comment by tooomm** [comment]
>Also wanted to ask what you think the text for the settings page should be, just kind of threw it togther

My suggestion would be:
```
Move top card from library
    ...to graveyard     [                   ]  [  ] [  ]
    ...to exile         [                   ]  [  ] [  ]
```

**Comment by Daenyth** [comment]
Does it work from the menu? I'd get that first, then after, you can rig up the keybind

**Comment by jjcard** [comment]
I was working on the shortcut first since I was not quite sure how the UI should be. Having basically the same action next to each other in the menu seems redundant, and I couldn't figure out how to have a sub-menu where the menu itself is clickable. And even then, the submenu item for the new 'one' action doesn't do anything, though it does show the correct shortcut next to it.

**Comment by tooomm** [comment]
Do you need any assistance or input here @jjcard ?

**Comment by jjcard** [comment]
I got sidetracked with hacktoberfest. I had tried adding the to the UI, but wasn't having any luck, but I I'll take another stab at it.

**Comment by Daenyth** [comment]
Hmm, here's an idea - @ZeldaZach or @ctrlaltca would either of you be willing/able to set up a time with @jjcard to do pair programming over hangouts or something? That might help get unstuck and be a good chance for everyone to learn more

**Comment by ZeldaZach** [comment]
Hey @jjcard do you want to work on this together at some point? Feel free to reach out on Gitter :)

**Comment by ZeldaZach** [comment]
Hey @jjcard If you ever want to work on this again or contribute, feel free to reach out on Gitter at some point.

**Pull request closed without merging**
