### PR TITLE
Registered + VIP + Buddy Gummy Update

### PR DESCRIPTION
**Pull request by tritoch**
Made Reg/VIP/Buddy gummy unique (all-gold)

### CODE REVIEW

**Comment by tooomm** [comment]
Can you include some pictures, please?

**Comment by poixen** [comment]
Looking at the changed files, you have only updated a star to be gold:


screen shot 2017-01-04 at 15 02 02

The commit says you have done Reg/VIP/Buddy. Is this 3 things or 1? I see the file name is `registered_vip_buddy.svg`. Can you clear this up?

**Comment by tritoch** [comment]
> The commit says you have done Reg/VIP/Buddy. Is this 3 things or 1? I see the file name is registered_vip_buddy.svg. Can you clear this up?

The SVG is for a user who is a Registered VIP, and another user has them as a Buddy.  Currently, if a user is Registered and VIP, and someone adds them to their buddy list, they have the same (green star) as a Registered Buddy.  This adds 'VIP' coloring to the star.

**Comment by tooomm** [comment]
Just by looking at your buddy list you can't tell if a mod or admin is marked as VIP.
Why should you be able to do so for normal registered users?

But my main concern is, that it's a bit misleading!
Since all Buddy icons are based off the normal gummy icon at the moment...
admin --> red
admin-vip --> red
mod --> black/white
mod-vip --> black/white
donator -->purple
reg --> green
reg-vip --> gold?!
It feels inconsistent to change the reg-vip one to have a gold star totally unrelated to the gummy color.

To make it more consistent... did you try to use a gold border around the green star instead?
It could be applied to the other levels as well (admin-vip, mod-vip)

Why is there no donor-vip btw? :)

**Comment by tritoch** [comment]
We did try gold fringe.  Was not legible.  Also tried all of these, with mediocre results (icon too small for most of these to be noticeable):
registered_vip_buddy
registered_vip_buddy
registered_vip_buddy
registered_vip_buddy
registered_vip_buddy
registered_vip_buddy
registered_vip_buddy
registered_vip_buddy

**Comment by tooomm** [comment]
If there is no other compromise I might favor consistency over a completely new icon to be honest...

**Comment by tritoch** [comment]
>If there is no other compromise I might favor consistency over a completely new icon to be honest...

Recognizing that the current Reg-Vip has a giant gold star already:
registered_vip

**Comment by tritoch** [comment]
Changed the non-buddy one to match the star.
registered_vip

**Comment by poixen** [comment]
Whats a VIP user? I think im out of the loop a bit.

**Comment by tooomm** [comment]
Unless I'm missing something, I guess you got me wrong.
For me this looks like putting the cart before the horse...

We need fresh input here :)

**Comment by woogerboy21** [comment]
> Whats a VIP user? I think im out of the loop a bit.

It's simply a user that is deemed by the operator to be of importance over any regular registered user.  There also is the privlevel of donator.  They both simply bypass user limit counts and have custom gummy's associated to each from a code stand point.

**Comment by poixen** [comment]
Ok, I understand the issue now.

VIP: 
screen shot 2017-01-06 at 22 31 27

VIP + Buddy:
screen shot 2017-01-06 at 22 32 22

Mixing all the user states and gummies is getting complex. I also think that the current VIP image looks more like a buddy, than the actual buddy.

I like the idea of having the following solid colors for gummies:

Mod = B/W
Reg User = Green
Donor = Purple
VIP = Gold

If you are a buddy of any of these, then you are the same color, but a large star (how we currently handle registered buddies).
screen shot 2017-01-06 at 22 32 22

When it comes to combining states, like VIP and Donor, then _visually_ you should represent the highest precedence (currently undecided), whilst in your User Details there is a full breakdown of your sub types.

**Comment by tooomm** [comment]
>When it comes to combining states, like VIP and Donor (...)

It's not possible to have several/both atm.


> I also think that the current VIP image looks more like a buddy, than the actual buddy.

Haha, same for me. Maybe a consideration? Serious... ;D

---

This is getting a bit complex now... I'll try to put some light in the dark. :P
Let's have this ultimative table for clarification and overview:

| User level (admin level) | Privilege level |  Regular gummy | Buddy gummy (just in chat!) |
| -----------------------: | :--------------- | :------- | :------- |
|  |  |  |  |
| Admin                      | DONATOR           |    |     |
| Admin                      | VIP                      |    |     |  
| Admin                      | NONE                  |     |     |
|  |  |  |  |
| Mod                        | DONATOR            |     |     |
| Mod                        | VIP                       |     |     |
| Mod                        | NONE                   |      |     |
|  |  |  |  |
| Reg                         | DONATOR             |      |     |
| Reg                         | VIP                       |   →   |   →   |
| Reg                         | NONE                   |      |     |
|  |  |  |  |
| Unreg                     | NONE                    |     |  possible at all?!   |

**Gummys on the LEFT side of an arrow showing BEFORE this PR,
gummys on the RIGHT side of the arrow showing AFTER this PR**

What does this pr solve?
- keep privlevel recognition once reg-vip people are buddy's (new gold gummy --> new gold star)

**So the new gummy color and matching buddy star color is helping and an improvement!**
Still... If reg users with privlevel "VIP" (aka reg-vip) gets there own gummy color, there is no reason to have admin-vip or mod-vip getting a star instead because that breaks uniformity again.
- some VIP users (non-buddy) have stars in front, while others haven't
- some VIP users are not recognized as VIP anymore once they are marked as buddy's, others are

In other words:
*Some user levels tagged VIP get a star, others get a new color.*
*Some user levels marked as buddy lose the recognition of privlevels, others don't.*

<br>
But how could another streamlined solution looks like? (trying to be as uniform as possible and as easy and recognizable to everybody - including feedback from poixen about the actual buddy stars and woods statement that admins and mods are already considered valued and honorable enough by there own):

| User level (admin level) | Privilege level |  Regular gummy | Buddy gummy (just in chat!) |
| -----------------------: | :--------------- | :------- | :------- |
|  |  |  |  |
| Admin                      | DONATOR           |    |     |
| Admin                      | VIP                      |    |     |  
| Admin                      | NONE                  |     |     |
|  |  |  |  |
| Mod                        | DONATOR            |     |    |
| Mod                        | VIP                       |     |     |
| Mod                        | NONE                   |      |     |
|  |  |  |  |
| Reg                         | DONATOR             |      |    (with star as all buddy's!)  |
| Reg                         | VIP                       |    |   (with star as all buddy's!) |
| Reg                         | NONE                   |      |    |
|  |  |  |  |
| Unreg                     | NONE                    |     |  possible at all?!   |

Basically it reduces the concept down to just two icon types. All gummy's with stars are buddy, additionally the gummy color (no matter if buddy or not) shows the user and priv level on top.

This are the benefits I can think of:
- all users marked as buddy get a star added (no matter which user level or privlevel)
- nicer fit of the new buddy icons between the other gummy's in the chat, yet recognizable
- all non-buddy-gummy's are more similar to other non-buddy-gummy's now, regardless of privlevel (doesn't grant stars for some priv levels in combination with this user level, but that color instead for the same priv level and a different user level combination...)
- admin & mods don't loose recognition anymore once they are buddy's. They never get it in the first place because, as we agreed, they don't need additional recognition by privlevels (they can still benefit of the advantages once granted)

Understand my concerns and ideas now? Open for discussion...

Took me a lifetime to complete this - hope you value it! ;P
At least it's a nice visual overview and should take away with any confusion on this topic/pr. 🙄
This could be used for our wiki or on some server info pages as well.

**Comment by ZeldaZach** [comment]
I ask to hold back on a merge until I can review and discuss it with everyone. I apologize for any delay but I'd like to get things right, which does require a full review on my end when I return.

**Comment by poixen** [comment]
@tooomm Excellent writeup!

I think we should ditch the gummy with a star on the top. When reduced down to 8px it looks rough.

screen shot 2017-01-06 at 22 31 27vsscreen shot 2017-01-06 at 22 32 22
One of these is clearer to see than the other. Also a gold VIP buddy with a yellow/gold star on top? Really hard to see.

 **I like the idea of having 2 icon per level: a gummy, and a star.**

If you are multiple levels (admin, donor and vip), then you appear as the highest of these, which would be a red gummy/star.

Levels:
1. Admin - highest rank
2. Mod - 2nd highest rank
3. VIP - 3rd highest, only achievable by being recognised by the Admin. Not given out willy-nilly.
4. Donator - 4th highest, can be achieved by anyone by donating.

**Comment by woogerboy21** [comment]
I would have to agree with @poixen .  Due to how small the images are the simpler the better.  Stick with going from the gummy shape to a star shape for buddies and solid color's in general.

**Comment by tritoch** [comment]
Should I add the below?

>So the new gummy color and matching buddy star color is helping and an improvement!
Still... If reg users with privlevel "VIP" (aka reg-vip) gets there own gummy color, there is no reason to have admin-vip or mod-vip getting a star instead because that breaks uniformity again.

**Comment by ZeldaZach** [comment]
I'd like to keep the star rank for mod/admin as we can use it to designate a "head" of the staff of that rank, for example. Once you're a mod/admin, VIP/DONATOR don't really matter and we can use it for alternative purposes

**Comment by skwerlman** [comment]
Well, it wouldn't matter if mod/admin bypassed user limits, which it doesn't. Currently, if I want my staff to ignore user limits, I have to mark ALL of them as VIP, so they'd all have the star.

**Comment by ZeldaZach** [comment]
@skwerlman I plan on making mods/admin exempt from the user limit in the near future

**Comment by tooomm** [comment]
Everybody keeps saying that the gummy with star icon is too small. But for admin/mod it's ok...?!

**Comment by ZeldaZach** [comment]
It's too small to make noticeable on the buddy star icon. I like having the star as it is noticeable enough to distinguish a mod/admin rank

**Comment by ZeldaZach** [comment]
I tested this and am happy with the results. 

| User level | Privilege level |  User list gummy | Chat gummy |
| -----------------------: | :--------------- | :------- | :------- |
|  |  |  |  |
| Admin                      | DONATOR           |    |     |
| Admin                      | VIP                      |    |     |  
| Admin                      | NONE                  |     |     |
|  |  |  |  |
| Mod                        | DONATOR            |     |     |
| Mod                        | VIP                       |     |     |
| Mod                        | NONE                   |      |     |
|  |  |  |  |
| Reg                         | DONATOR             |      |     |
| Reg                         | VIP                       |    |    |
| Reg                         | NONE                   |      |     |
|  |  |  |  |
| Unreg                     | NONE                    |     |  N/A  |

This is the final result (see the table above). If anyone else has anything to say, please do so. I will also be creating a wiki page to denote the _default_ values of the gummys so users don't get to confused.

**Pull request merged**
