### PR TITLE
Added shortcut for Settings page

### PR DESCRIPTION
**Pull request by poixen**
Ctrl + H

### CODE REVIEW

**Comment by poixen** [comment]
@ZeldaZach please dont auto merge. I want feedback from other users too.

**Comment by Daenyth** [comment]
Ctrl h is a system bind on mac

**Comment by poixen** [comment]
Gimme something that is available. I'm not a Mac user.

**Comment by ctrlaltca** [comment]
I was about to say QKeySequence::Preferences (from http://doc.qt.io/qt-4.8/qkeysequence.html#StandardKey-enum), but it seems it's implemented only on osx :(

**Comment by poixen** [comment]
Ctrl + Alt + H?

**Comment by ZeldaZach** [comment]
>Ctrl + Alt + H?

Seems good to me

**Comment by poixen** [comment]
Updated to Ctrl Alt H

**Comment by ZeldaZach** [comment]
This doesn't seem to work as QT auto-binds **command + comma** to the "preferences" menu for mac. Not certain on the windows side of things.

**Comment by poixen** [comment]
Someone needs to give me something I can use that will work on a mac. Otherwise I will close this PR.

**Comment by Daenyth** [comment]
Can you just not add a shortcut on Mac?

**Comment by ZeldaZach** [comment]
Macs don't allow for overriding system shortcuts I think

**Pull request closed without merging**
