### PR TITLE
properly capitalize set types like Duel Deck and From the Vault

### LINKED ISSUE #3766: set types are not displayed perfectly
Oracle imports `duel_deck` as `Dual_deck` etc.
So we capitalize the first letter as they are all lowercase in mtgjson (see https://mtgjson.com/structures/set/).

But what we should really do is to convert to `Dual Deck`, with a space as separator and capitalize all words.

Untitled

### PR DESCRIPTION
**Pull request by ebbit1q**
## Related Ticket
- Fixes #3766
## Screenshot

image

### CODE REVIEW

**Comment by tooomm** [comment]
That's cool! Thanks for taking care.

Missing words in the list that don't get capitalized as well: `of, in, and, with, but, or`

**Comment by ebbit1q** [comment]
I only included words that I thought might be included in the future, currently it's only needed for From the Vault

**Comment by ebbit1q** [comment]
there, I included them

**Comment by tooomm** [comment]
If it doesn't hurt to have them. 👍
But you are right that the possible list of set_types shouldn't change to much and often...

**Pull request merged**
