### PR TITLE
fix volume slider on qt6

### PR DESCRIPTION
**Pull request by ebbit1q**
sound never worked on qt6, the volume setting goes from 0 to 1 instead of 0 to 100

### CODE REVIEW

**Comment by ebbit1q** [comment]
while this does fix the volume slider there seems to be a different issue on my system, the qt6 version only plays sound after I compile it until I run any other version of cockatrice on the same system, and there is always some audio clipping not present on the qt5 build

**Comment by tooomm** [comment]
Sound seems to work with the Win10 64bit file.

**Comment by tooomm** [comment]
Hmm, after going to the beta.9 to verify the issue... going back to

```
Client Version: 2.8.1-custom(fa859ec) (2022-06-15)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: en_GB
Install Mode: Standard
```

gives me no sound now. 🤔

**Review by tooomm — APPROVED** [review]
I tested and confirm this again for Windows with Qt6. 👍 

On beta.10 adjusting the volume has no effect, e.g. volume slider at 2 is as loud as at 100.
Only enabling/disabling works via the check box. Or putting the slider to 0 (disabled) or non 0 (enabled).
>Client Version: 2.8.1-beta.10 (2022-09-01)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.1
System Locale: en_GB
Install Mode: Standard

With the fix from this PR in `2.8.1-custom(0221b0e)`, the volume slider has expected functionality.


<br>

>there seems to be a different issue on my system, the qt6 version only plays sound after I compile it until I run any other version of cockatrice on the same system, and there is always some audio clipping not present on the qt5 build

I don't think I've those issues on my machine as far as I can tell. 🤔

**Pull request merged**
