### PR TITLE
Inform user of cards.xml save location on success

### PR DESCRIPTION
**Pull request by Daenyth**
I'm tired of seeing people say "Oracle ran, where is my cards file"

### CODE REVIEW

**Comment by MassCraziness** [comment]
Definitely seems like a good idea. Being told where the file is going can help if you want to do edits to it yourself or change things.

**Comment by woogerboy21** [comment]
Screenshot?

**Comment by Daenyth** [comment]
save

**Comment by MassCraziness** [comment]
That will be nice. Now, if only we could force users to remember that..

**Pull request merged**
