### PR TITLE
4007/refactor player class

### LINKED ISSUE #4007: Refactor Player Class
**Description of New Feature**
As it exists right now, the Player class functions well, however there are numerous places where I believe the code could be cleaned up. For the Player class specifically, I see a lot of opportunities to extract methods out to both increase readability and decrease code reuse (effectively copy-and-pasted code).

### PR DESCRIPTION
**Pull request by LeeTranMN**
## Related Ticket(s)
- Fixes #4007 

## Short roundup of the initial problem
The Player class has many opportunities for refactoring

## What will change with this Pull Request?
- No functionality will change, only where that functionality lies in the code.

### CODE REVIEW

**Comment by ebbit1q** [comment]
When will this be ready for review?

**Comment by tooomm** [comment]
Any updates? Are you still working on this, @LeeTranMN?

**Comment by ZeldaZach** [comment]
Hey @LeeTranMN thanks a lot for trying to improve on Cockatrice! If you're still working on this PR, feel free to mark it for review whenever. If not, I appreciate you taking a crack at it.

In any case, I'm going to close this PR in a few days if there is no new activity (Comments, Pushes, etc). Feel free to reach out anytime at https://cockatrice.us/discord if you have questions or would like to chat!

**Comment by ZeldaZach** [comment]
This change feels unnecessary as you didn't turn it into a builder class. It's more so just splitting up for readability compared to a full refactor. As such, I'm gonna close it for now. However, if you'd like to discuss how we can get this added reach out anytime!

**Pull request closed without merging**
