### PR TITLE
Re-Dockified the game & replay review areas

### PR DESCRIPTION
**Pull request by ctrlaltca**
This PR is heavily based on @woogerboy21's work in #1544.
The user-visible change is that now the game & replay tab contains dockable items that can be rearranged.
Anyway there are a few changes between this and the original PR #1544:
 * All the tabs can now contain dockable items (```Tab``` inherits from```QMainWindow```); so, all the tab classes have been reworked a little to accomodate this change
 * The administrative "View Logs" tab's layout has been refactored (avoid leak objects at every search + make tables fit a small screen)
 * In replay view, the "timeline / replay controls" widget is dockable
 * In games/replay view, the "game view" widget is not detachable anymore; i see no point in being able to detach all the widgets from the tab and leaving the game tab empty. If you want to see more games at once, we'll address this making the game tabs detachable
 * In ```TabGame```, all the duplicated code between the "game" and the "replay" mode has been merged
 * Saving the geometry of the docks in games now works
 * Game and replay geometries are saved to different config options

I squashed everything down to a single commit, where @woogerboy21 's is the author (being the author of the first original commit i based this PR upon)

### CODE REVIEW

**Comment by woogerboy21** [comment]
Cool!

**Comment by Fizztastic** [comment]
Just tested this and everything works as expected. Having the geometry saved properly is a really nice addition after using wooger's patch for months now ;)

**Comment by tooomm** [comment]
Awesome! This is THE pr i've been waiting for sooo long. :+1: :+1:

Saving works fine and is separated for replays/games. Can't test log tab.
<br>
My observations though:
- the "timeline" or "progress bar" widget in the replay tab has no name:
nowidgetname
since it includes the controls as well i'm not sure of a proper name, maybe "Timeline & Controls"?

- it seems that the `users in room` list in server tab & the `users on server` list in account tab are wider as they used to before

<br>
on a site note (replays might be broken? they are both older... the only ones i have right now though)
- like 5min before my replay ended the green progress bar on the timeline disappeared - the replay still continued, maybe a problem with this? never realized it before, but I mostly never watch replays
- another replay file showed confusing timestamps. after a longer break for deck building the next time stamp in chat had just a difference of ~1min, while the progress bar showed a huge gab with no action

**Comment by Fizztastic** [comment]
@tooomm The green progress bar disappearing during replay is a bug that's been in the app for a long time.

**Comment by ctrlaltca** [comment]
> the "timeline" or "progress bar" widget in the replay tab has no name:

Fixed, thank you.

> it seems that the users in room list in server tab & the users on server list in account tab are wider as they used to before

They just accomodate the "game view" width. As soon as you resize them once, they will maintain that size.

**Comment by woogerboy21** [comment]
@ctrlaltca 
One of the main reason I actually started working on getting detachable content was to be able to detach the game frame portion of the game view as that is one of the things requested by users in the past on a pretty constant basis when talked to me directly in client.  I was always told it was mainly for multi-monitor use or the ability to play a game and also have chat functionality available with out flipping between tabs.  One possibility that may be an option if people done see a good use for being able to pull the game view out would be to pull the chat frames from the various tabs out possibly?

**Comment by ctrlaltca** [comment]
@woogerboy21 yes, i'll try to address that in another PR.

**Comment by tooomm** [comment]
> The green progress bar disappearing during replay is a bug that's been in the app for a long time.

you are right: https://github.com/Cockatrice/Cockatrice/issues/1525
<br>
>They just accomodate the "game view" width. As soon as you resize them once, they will maintain that size.

i couldn't manage to resize the lists on windows somehow?! 
<br>
> yes, i'll try to address that in another PR.

detachable chat frames or complete detachable game tabs? :)

<br>
It seems there is a problem on Mac: https://github.com/Cockatrice/Cockatrice/issues/1730#issuecomment-170595489
@ZeldaZach or @Daenyth can you confirm this?
<br>
there are no app icons in the upper left if you detach a widget:
noicon

**Comment by Daenyth** [comment]
If/when I get a chance. Otherwise, here's the stack trace: https://github.com/Cockatrice/Cockatrice/issues/1730#issuecomment-170599607

**Comment by ZeldaZach** [comment]
@tooomm I don't see the reattach features either.

screenshot 2016-01-11 20 43 16
screenshot 2016-01-11 20 43 21

Furthermore, I'd like to be able to grab a corner and resize the widgets manually
screenshot 2016-01-11 20 43 53

Another thing; If I have two games open I could get confused with what's what. Maybe update the lists to say the game number as well (when detached and/or when multiple games are joined by a player)?

screenshot 2016-01-11 20 45 29

One other thing: there is no reset layout option for the log view

**Comment by tooomm** [comment]
> Furthermore, I'd like to be able to grab a corner and resize the widgets manually

On Windows I can grab all 4 sides and all 4 corners to resize the popped out widget!
<br>
> I don't see the reattach features either.

Since I'm using Windows I expect the logo of the app in the upper left corner and controlling buttons in the upper right. ;)
Interestingly you see the Cockatrice logo *centralized* in the popped out `Player List`, while I don't. <br>But you are totally right, a reattach icon would be cool. For me, a double click in the info bar is reattaching the widget to its old place in the layout though.

**Comment by Daenyth** [comment]
Double click to reattach isn't discoverable. Users won't figure it out.
Also double click the window bar can have window manager specific effects
on Linux.

**Comment by ctrlaltca** [comment]
@tooomm 

> i couldn't manage to resize the lists on windows somehow?!

If you're using OSX, this is a known Qt 5.5 bug: https://bugreports.qt.io/browse/QTBUG-46882

> detachable chat frames or complete detachable game tabs? :)

Detachable tabs (all of them)

> There are no app icons in the upper left if you detach a widget:

Fixed, thank you

> It seems there is a problem on Mac: #1730 (comment)

Unrelated: travis is currently building DMGs on OSX 10.9.5 and the user is unable to run them on OSX 10.7. Will investigate if this is fixable and eventually open another PR.

@ZeldaZach

> I don't see the reattach features either.

Do you mean a button that you can press on the widget's titlebar in order to re-dock it to the main window? This doesn't exists in Qt, but we could add a button somewhere inside the window.

> Furthermore, I'd like to be able to grab a corner and resize the widgets manually

OSX? See previous comment on Qt bug

> Maybe update the lists to say the game number as well

Great idea, implemented

> One other thing: there is no reset layout option for the log view

"Game" Menu → Reset Layout

@Daenyth 

> Double click to reattach isn't discoverable. Users won't figure it out.

I agree, it's problematic. Creating a "dock/reattach" button somewhere is quite simple, but:
 * adding it to the window's titlebar is problematic: we should re-create entire the titlebar widget (cross-os, handle events, etc)
 * adding it to the window itself is a waste of space

"Game" Menu → Reset Layout can be used as a "panic!" button when an user closed/undocked a widget and is not able to get it back in place.

**Comment by Daenyth** [comment]
What if we have a top-level menu (Panels? Docks? Windows?) which lists all docks, pinned or floating, and gives options to dock/undock, reset position, etc, individually?

**Comment by tooomm** [comment]
@Daenyth 
I talked to @woogerboy21 about this once as well when he was working with widgets because the `Reset Layout` buttons are not easy to find. Also, we now have a different handling for `Deck Editor` widgets from the old pr and the new widgets in this pr.
I had the idea to create a new menu and call it `View` and gather all options there to improve the UX/UI. Most programs have it already and people are used to it. There you find options to enable(show) and disable(hide) toolbars or other parts and elements of the app. Normally this is indicated with check marks.

Here are two examples:

Firefox:
ff-view<br>
Libre Office:
office-view

<br>
<hr>
The menu could look like this if you're using the `Game Room` tab right now:

`View`
 - [x] Card Info
 - [ ] Deck
 - [x] Filters<br>
 ----------------
 - Reset Layout

<hr><br>
<hr>
Or even one single menu for all types of tabs:

`View`
 - Reset 'Deck Editor' Layout<br>
 - [x] Card Info
 - [ ] Deck
 - [x] Filters
<br>
-----------------
 - Reset 'Game Room' Layout<br>
 - [x] Card Info
 - [x] Player List
 - [x] Messages
<br>
-----------------
 - Reset 'Replay' Layout<br>
 - [ ] Card Info
 - [ ] Player List
 - [x] Messages
 - [x] Replay Timeline
<br>

<hr>
<br>
With such a menu users could hide/show different elements and reset the layout. I think dock/undock is not necessarily needed - drag&drop seems easy enough and should be self-explaining. The only hidden feature would be double-click to dock widget at old position, but users could just drag it there as well... so no key feature.
Also I like your ideas about other names like `Panels` or maybe even just `Widgets` for the menu!

**Comment by Daenyth** [comment]
I like View and Panels. Widgets is a term non-programmers won't recognize

**Comment by ctrlaltca** [comment]
So, i just created a "view" menu in the deck editor. Please test it and report any problems / corrections. When everything's ok i'll add a similar one to the game tab.

**Comment by ZeldaZach** [comment]
I'm not exactly sure what was added, but let me go check that out now

**Comment by ZeldaZach** [comment]
Ok so the View menu is well done and should be implemented around the client. Great!!

**Comment by tooomm** [comment]
There is no refresh on the `floating` state in the menu once you undock a widget by dragging it out of the UI or using the undock button:
undock-no-floating-refresh
It works fine if you use the menu to undock though!
<br>

You removed the buttons to show/hide the particular UI elements in deck editor as well. I kinda miss them, but might get used to it. It was a fast way of enabling/disabling stuff since you might play around with the UI most in deck editor. But for consistency I'm ok with removing them.

**Comment by ctrlaltca** [comment]
> There is no refresh on the floating state in the menu once you undock a widget by dragging it out of the UI or using the undock button:

Fixed, thank you.

I've added the menus also on the game tabs.
Can you please test everything once again?

**Comment by tooomm** [comment]
- I realized that the `Reset/Clear Downloaded Pictures` button is displayed all over the settings menu when I use the build from this pr. It used to be a normal sized button?!
resetbutton

- The undocked windows don't display the game name and number anymore:
spectating-floating-nogamename
Not that I liked that... because many games use longer names with details, which makes perfectly sense for a helpful game name. :+1: 
BUT because of that just half the name was displayed and shortened down, plus the game number as simple unique identifier was not visible at all, because it was placed at the end.
*Can we just have the game number in the title bar of the floating widget??*
Something like: **Messages (#gamenumber)**
Because what zach describes above is an issue when we don't have window assignments.

<br>
- *>>There are no app icons in the upper left if you detach a widget:<br>
>Fixed, thank you*<br>
As you can see in the picture above it's not fixed in windows. No Cockatrice app icon in the title bar of the floating widget....

**Comment by ctrlaltca** [comment]
It seems like appveyor didn't pick up the right commit when building (or i mistakenly pushed a wrong commit). I've just re-pushed the correct commit and relaunched the build.

**Comment by ctrlaltca** [comment]
> I realized that the Reset/Clear Downloaded Pictures button is displayed all over the settings menu when I use the build from this pr. It used to be a normal sized button?!

It should be on the left of the "How to set a custom picture url", but it's unrelated to this change. Please open a new ticket for it.

> The undocked windows don't display the game name and number anymore:

The last push & appveyor recompile should have this bug fixed.

> As you can see in the picture above it's not fixed in windows. No Cockatrice app icon in the title bar of the floating widget....

On windows the floating docks never had a window icon shown, not even in the last stable (expeditions).

**Comment by tooomm** [comment]
>>The undocked windows don't display the game name and number anymore:

>The last push & appveyor recompile should have this bug fixed.

We now have text in the titlebar again:
titlebar1
titlebar2
titlebar3

But that's exactly what I was referring to...
>BUT because of that just half the name was displayed and shortened down, plus the game number as simple unique identifier was not visible at all, because it was placed at the end.
Can we just have the game number in the title bar of the floating widget??
Something like: Messages (#gamenumber)

What do you guys think about just having "WidgetName (#GameNumber)" to keep it short, simple and you can assign it with a special window/game/replay in case you need to.
It won't run you into trouble because game name, game type etc. are too long as well.
In the pictures from above you don't even see the most important information (--> which widget it is..., nor the gamenumber - mostly everything is shortened or not complete) because there are so many things displayed, and most of them not needed imo.

<br>
<br>




>>>There are no app icons in the upper left if you detach a widget:

>>Fixed, thank you

>On windows the floating docks never had a window icon shown, not even in the last stable (expeditions).

Well, you said it's fixed. Ok, so it actually can't get fixed. Simple misunderstanding. ;)

**Comment by ctrlaltca** [comment]
> What do you guys think about just having "WidgetName (#GameNumber)" to keep it short

I have no personal preference in using one or the other format, so i'll be glad to change this to the way what most people like.

> I also realized that you added a REPLAY text tag to docks from that tab.

I'm just currently concatenating the tab title with the widget title; a game replay has a "REPLAY" prefix in its title.

> Well, you said it's fixed. Ok, so it actually can't get fixed. Simple misunderstanding. ;)

Yep, sorry. It was previously broken on all platform, now it works on linux and osx; Windows is still broken.

**Comment by ZeldaZach** [comment]
I'm fine having it as `Name (#number)`

What's the issue still with winderps?

**Comment by ctrlaltca** [comment]
> What's the issue still with winderps?

No cockatrice icon on floating widgets

**Comment by ZeldaZach** [comment]
Is that a big deal? Hasn't that been an issue for a long time now anyway (with popup alerts and such)?

**Comment by ctrlaltca** [comment]
Popup alerts can be fixed; in this case it seems more like of a specific decision of qt's windows theme.
We could "fix" this one, too reimplementing the dock widgets (or at least their style delegate), but imho it's a bit too much work.

**Comment by tooomm** [comment]
I just mentioned it, because I realized it. It's not too much of a deal... :+1: 
<br>
To go back to the titlebar names:
Another improvement would be to have the player count visible in the titlebar while docked *and* undocked. This would allow to easily keep track of the player count on a second monitor while you surf and wait for example. Another reason would be you can't really tell within a second (for rooms with high player counts) if it's 5,6 or 7 players at the moment.

I always run into this problem when playing drafts with 8 players and it's not high season and no new set just released... you easily wait 20-30min sometimes to find enough players. :(
Would be very helpful! And we keep track of his information in the game room list already.

<br>
It could look like this:

normal widgets (docked)
`WidgetName`
e.g. `Messages`

normal widgets (undocked)
`WidgetName | #GameNumber`
e.g. `Card Info | #158846`

player_list widget (docked)
`WidgetName (PlayerCount)`
e.g. `Player List (5/8)`

player_list widget (docked)
`WidgetName (PlayerCount) | #GameNumber`
e.g. `Player List (5/8) | #158846`

**Comment by ctrlaltca** [comment]
I'd commit this as it is, and postpone the titlebar fixes to a specific commit.

**Pull request merged**
