### PR TITLE
[WIP] update travis' docker target to fedora 30

### LINKED ISSUE #3712: Fedora 30 released / update travis docker image once reasonable
`Do not forget` `Keep track` issue

### PR DESCRIPTION
**Pull request by ebbit1q**
fix #3712 

if it builds, it builds, if it doesn't we patiently wait.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Looks like #3508 is striking again

**Comment by ebbit1q** [comment]
So, we wait.

**Comment by tooomm** [comment]
As reference: https://bugzilla.redhat.com/show_bug.cgi?id=1668865 is the filled bug we run into again.
We don't have to rush for another workaround again, let's wait a bit.

**Comment by tooomm** [comment]
from gitter:

>the fedora guys say that the problem in #3714 is a docker problem (that happens only in fedora?), and that since it never worked in fedora 30, they don't consider it a regression, so they won't supply a patch for it

>can you look into a workaround again?
you used a special qt version in Cockatrice/Cockatrice#3512 back then

>on fedora 29 we use the "latest working" version
on fedora 30 no known working version exists
a fedora guy on irc told me we'd better drop using docker (and.. travis?) and use some fedora-specific package build env
i'd go for drop using fedora at all :)

**Comment by ZeldaZach** [comment]
🤷‍♂ Not sure what to do with this for now.

**Pull request closed without merging**
