### PR TITLE
Realigned Icons

### PR DESCRIPTION
**Pull request by poixen**
Moved Icons to the top. You can now see all options.
Updated SVGs to all match.

Before:
before

After:
after

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Tested and very nice. Approved :+1:

**Comment by tooomm** [comment]
Is there a reason for the Messages icon not having this blue border/background?

**Comment by poixen** [comment]
No idea. That icon was made before my time. I might be able to add it in, depends if enough people want it.

**Comment by poixen** [comment]
@tooomm Added in the missing background. Also made the General icon background the same as the others,

**Comment by tooomm** [comment]
unified look :+1: 
(I would like it even more with the speech bubble not touching the outer lines, maybe just personal preference)

**Comment by poixen** [comment]
@Daenyth this is ready for merge.

**Comment by tooomm** [comment]
another find:

check out my image and yours from above:
settings slashes random direction

The slashes are facing in different directions. But path are working I guess.
Weird, that they are not the same in both of our images... yours are even more mixed up.

**Comment by poixen** [comment]
@tooomm 
I think this is why:
http://www.howtogeek.com/181774/why-windows-uses-backslashes-and-everything-else-uses-forward-slashes/

**Pull request merged**
