### PR TITLE
Migrate travis to use ubuntu 14 (trusty)

### PR DESCRIPTION
**Pull request by ctrlaltca**
Travis (finally!) permits the use of ubuntu 14 as a platform to test builds (http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/).
This PR moves our tests to this new platform.
I'm unsure wether it could be useful to keep building on ubuntu 12, too.
From a "test the code" perspective is just the same, only without the hassle of having to install third party packages from PPAs.
From a "get a redistributable package built" perspective, i hope people migrated away from 12lts to 14lts long time ago.

### CODE REVIEW

**Comment by Daenyth** [comment]
We should build both if possible. Ubuntu 14 is not an lts release - next one is 16.04

**Comment by Daenyth** [comment]
But I'm ok with dropping auto builds for 12 if it makes things easier

**Comment by ctrlaltca** [comment]
Closing by now; will include in another PR.

> Ubuntu 14 is not an lts release

huh? https://wiki.ubuntu.com/LTS

**Comment by Daenyth** [comment]
Derp I got it mixed up with 15

**Pull request closed without merging**
