### PR TITLE
save sets dialog size

### LINKED ISSUE #4778: Interface issue in `Manage sets...`
**System Information:**
Client Version: 2.8.1-beta.12 (2023-03-03)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.2
System Locale: en_GB
Install Mode: Standard

_______________________________________________________________________________________

When you change the order in the sets view, a hint is displayed, the buttons are pushed above the table and cover content:
grafik

_______________________________________________________________________________________

**Steps to reproduce:**
 - Open `Card Database` --> `Manage sets...`
 - Change ordering of sets with clicking on one column
 - Note appears and layout breaks

### PR DESCRIPTION
**Pull request by ebbit1q**
## Related Ticket(s)
- Fixes #4778

## Short roundup of the initial problem
the sets dialog can be resized wrong

## What will change with this Pull Request?
- don't set a minimum size of the list
- set a minimum size for the dialog
- save the dialog size in the settings
- save the header state in the settings
- allow the headers to be resized

### CODE REVIEW

**Comment by tooomm** [comment]
Btw, this was not an issue on 2.8.0

The result with your change seems ok for me and fixes the reported issue.

However, changes to ordering (like clicking on a column header to sort) are saved right away now, and confirming/clicking on the button is no longer needed.

**Comment by ebbit1q** [comment]
I absolutely did not change the behavior of ordering, are you sure?

**Comment by ebbit1q** [comment]
I noticed what was happening, the header state includes the _displayed_ sorting order, this might be a bit annoying. note that at no point this changed your actual saved sets order.

**Review by tooomm — APPROVED** [review]
Issue(s) solved for me

**Pull request merged**
