### PR TITLE
Increased server shutdown limit

### PR DESCRIPTION
**Pull request by poixen**
Added a max of 999 mins for the server shutdown to the gui.

### CODE REVIEW

**Comment by Daenyth** [comment]
Could we reuse the "ban duration" bit from the ban user dialog?

**Comment by ZeldaZach** [comment]
@Daenyth You're referring to using the Day Hour Minute thing for how long until the shutdown would be I assume?

**Comment by Daenyth** [comment]
Something like that

**Comment by tooomm** [comment]
A fixed time value when the shutdown should happen (e.g. 6am tomorrow), would be nice too.

**Comment by ZeldaZach** [comment]
With server times not always matching person time, I'd rather have something like the mod tools @tooomm

**Comment by poixen** [comment]
Jeez. Maybe in another commit. This was just a quick fix for wooger.

**Comment by woogerboy21** [comment]
Awesome, thanks for this.  Ill build a client now and get it tried out.

**Comment by Daenyth** [comment]
:shipit:

**Pull request merged**
