### PR TITLE
[WIP] Add Registration command and responses to protocol

### LINKED ISSUE #144: Protocol extension to support in-client registration
I thought I already noted this all down but maybe it was on the old github

New message
Command_Register
- username
- hashed password value
- email address

New responses
- User already registered
- Email required and not sent
- New username accepted & Activation email sent to $email
- Server does not use authentication

New response to login as unregistered
~~Server requires registered accounts to connect~~

Cockatrice needs a new UI pane for it and UI for when the server doesn't support registration

Servatrice needs to handle the message

### PR DESCRIPTION
**Pull request by Daenyth**
Fix #144 

Please scrutinize this. Consider edge cases and possible user workflows not discussed in 144

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Has anybody had a chance to look over this yet? :smile:

**Comment by Daenyth** [comment]
It's fairly stable but I have some tweaks in my other branch I want to
rebase in

**Comment by ZeldaZach** [comment]
@Daenyth Go for it when you get a chance

**Comment by ZeldaZach** [comment]
@Daenyth You think we can merge this, or is it still not ready?

**Comment by Daenyth** [comment]
It's still in progress

**Comment by ctrlaltca** [comment]
Closing in favor of #1101

**Pull request closed without merging**
