### PR TITLE
add ccache to docker compilation

### PR DESCRIPTION
**Pull request by ebbit1q**
Adds ccache to the docker image and shares travis' ccache dir with the image.

### CODE REVIEW

**Comment by ebbit1q** [comment]
This works, let the festivities begin.

**Comment by ebbit1q** [comment]
image
👌

**Comment by ctrlaltca** [comment]
Nice!

**Comment by tooomm** [comment]
That's so great. Down from ~9 minutes! The docker build (bionic on trusty base) is only 15s slower than on xenial directly.
Thank you @ebbit1q 😍 

However I've this concern with the cache: https://github.com/Cockatrice/Cockatrice/pull/3447#issuecomment-440450479
Let me know what you guys think!

**Pull request merged**
