### PR TITLE
Support <tablerow> for tokens; fix #232

### LINKED ISSUE #232: Support for <tablerow> in tokens.xml
Can we have support for `<tablerow>`; in tokens.xml?

Alternatively, can all tokens with `<pt>`; be assigned to row 2 and tokens without the tag to row 1?

Tokens that should be in row 1:
* Gold
* Land Mine
* Emblems
* Poison counter

### PR DESCRIPTION
**Pull request by ctrlaltca**
Token creation will respect the initial tablerow position defined in tokens.xml

### CODE REVIEW

**Comment by Psithief** [comment]
This seems to address the issue. Compiling it is beyond me, though.

I'm curious, what happens if `y` is outside the range 0 through 2?

**Comment by ctrlaltca** [comment]
:boom: 
Y will be set to a negative number, and i suppose the server will somehow sanitize it.
The same negative value can be achieved playing a normal card, so i'd better check it out.

**Comment by Psithief** [comment]
I'm trying this in a local game using `cards.xml`. `<tablerow>-5</tablerow>` doesn't draw the card. Same with `<tablerow>5</tablerow>`.
Non-numeric values seem to be converted to 0 just fine, though that's the land slot.

**Comment by ctrlaltca** [comment]
Cards that ends up being played in a row different from [0, 1, 2] just disappear, since the client doesn't draw those rows on the screen.
I'm not sure we want to force the number of table rows in the server, since other games could be using a different amount to tablerows. It should be configurable per-game on the client, but that's a long task (we currently miss any support for concurrent multiple games anyway).

**Comment by Daenyth** [comment]
Can the game scene be responsible for drawing wrong-N row values within its own bounds? If it itself knows that it has rows 0..2, then it can pick one as a default row for invalid numbers.

**Comment by ctrlaltca** [comment]
The last commits adds to tablezone a (const by now) variable defining the number of rows and a method that clamp a number between valid values. Card and token creation methods have been updated adding a call to the clamp() method.

Now, could someone use a modified cockatrice avoiding this constraint in order to cheat? Maybe.
For negative <tablerow>s, the played card just won't be painted anywhere. 
For positive <tablerow>s,  the player card is on your tablezone, but gets painted over the opponent's tablezone, some pixels off the correct position of a normal card of the opponent.

**Comment by Daenyth** [comment]
The chat line events should make people notice something is happening though.

**Comment by ZeldaZach** [comment]
Works as expected and I'm going to merge b/c we're about to publish a new build and I'd like this in.

Food for thought: When creating a custom token using the menu, maybe allow people to specify `tablerow` it should go into.

**Pull request merged**
