### PR TITLE
Added menu item to open custom image folder

### PR DESCRIPTION
**Pull request by poixen**
Needs to be tested on mac.

customimagefolder

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Does not work on Mac OS X 10.10.3.

When I use the button, finder opens to the default page (user directory, also known as `~`)

**Comment by tooomm** [comment]
I think it might fit even better in the "card database" menu.

there could be two buttons next to each path as well - `change` (the one we have right now)
and `open` or `go to`
open folder

**Comment by poixen** [comment]
Moved to the card database dropdown menu

**Comment by ZeldaZach** [comment]
Works on Mac OS X 10.10.3 now (thanks to me :smile: )

**Comment by ZeldaZach** [comment]
Works as expected on b68cf51 for Mac

**Pull request merged**
