### PR TITLE
add feature list requirement

### PR DESCRIPTION
**Pull request by ZeldaZach**
This adds the requirement for users to be pushed to the newest version. It's a temporary addition while the WW->RR transition occurs, as users need a bit of a 'push' to get off the links and we can disassociate WW from the program.

### CODE REVIEW

**Comment by skwerlman** [comment]
i wouldn't mind seeing a single, more general "minimum version" feature instead of simply adding a new protocol feature every time we want to do something like this.

**Comment by ZeldaZach** [comment]
This is a changeable field, which in itself I guess we can declare minimum version. I don't really have a lot of time to look into incorporating a full minimum version requirement setup and I want to do a release this weekend

**Comment by Daenyth** [comment]
@skwerlman The reason we went with feature list instead is because version number gets awkward if/when we have more than one client implementation (like the web client)

**Comment by ZeldaZach** [comment]
This good to merge?

**Pull request merged**
