### PR TITLE
allow specifying package generator on linux

### PR DESCRIPTION
**Pull request by skwerlman**
use like `cmake .. -DPACKAGE_GENERATOR=RPM`
defaults to DEB

I've never worked with cmake before, so there might be a better way to do this

valid generators are listed here: https://cmake.org/Wiki/CMake:CPackPackageGenerators

should help move #1746 forward

### CODE REVIEW

**Comment by ctrlaltca** [comment]
By now we force the use of the "DEB" package generator under linux because we only implemented the CPACK_DEBIAN_PACKAGE_* variables needed to generate a debian package.
In order to get RPM packages to work, you'll need to:
 * add the needed CPACK_RPM_PACKAGE_* variables (https://cmake.org/cmake/help/v3.0/module/CPackRPM.html)
 * drop line 177 https://github.com/Cockatrice/Cockatrice/pull/2351/files#diff-af3b638bc2a3e6c650974192a53c7291L177
 * there's no need to ad a new "PACKAGE_GENERATOR" variable, you can just `cmake .. -DCPACK_GENERATOR=RPM`

So, this PR is mostly useless.

**Comment by skwerlman** [comment]
Thanks for the info; I had no idea it needed those additional variables.
I'll fix and resubmit this.

**Comment by ctrlaltca** [comment]
You can somewhat autodetect if the linux distro is using rpm by checking for the existence of a specific path, eg:
```cmake
    find_file(PACKAGE_TYPE_RPM Packages PATHS /var/lib/rpm/)
    mark_as_advanced(PACKAGE_TYPE_RPM)

    if (PACKAGE_TYPE_RPM)
        set(CPACK_PACKAGE_TYPE RPM)
        # set all the basic CPACK_RPM_* variables
    else()
        set(CPACK_PACKAGE_TYPE DEB)
        # move all the CPACK_DEB_* variables here
    endif()
```

Probably mirroring the existing CPACK_DEB_* variables into their CPACK_RPM_* counterpart is a good start in order to get working packages including basic informations like a name, a version and the needed dependencies.

**Comment by skwerlman** [comment]
I'd like to avoid autodetection, especially in place of a manual flag, since its possible to have the tools for making both debs and rpms on one system.

**Comment by Daenyth** [comment]
I agree. I'd pick a default and let it be manually overridden.

**Comment by skwerlman** [comment]
re-submitted as #2373

**Pull request closed without merging**
