### PR TITLE
Update macOS Monterey app icon

### PR DESCRIPTION
**Pull request by Zarel**
## Short roundup of the initial problem

In macOS 12 (Monterey), Apple introduced iOS-style app icons, which are as of now basically universal. Any icons not in the modern format stick out a lot.

## What will change with this Pull Request?

This updates Cockatrice icons to the modern Monterey style.

## Screenshots

BEFORE:
image
AFTER:
image

### CODE REVIEW

**Comment by ebbit1q** [comment]
is this backwards compatible to macos 11?

**Comment by Zarel** [comment]
Short answer: Yes.

Long answer: It'll still look like the new icons in macOS 11, but every other app looks like this now, so it's not like it'll look out of place or anything.

**Comment by Zarel** [comment]
Short answer: Yes.

Long answer: It'll still look like the new icons in macOS 11, but every other app looks like this now, so it's not like it'll look out of place or anything.

**Comment by ebbit1q** [comment]
@ZeldaZach can you check if these look right?

**Pull request merged**
