### PR TITLE
Rework #838 commenting out c++11 usage

### PR DESCRIPTION
**Pull request by ctrlaltca**
Keeping the other two useful changes:
 * removal of a mutex
 * use of float instead of uint64.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
References:
 * #838 original PR by @JimMcMahon
 * #837 original issue
 * #127 c++11 support issue

**Comment by tooomm** [comment]
Can you check https://github.com/Cockatrice/Cockatrice/issues/475#issuecomment-80781026 as well please?

**Comment by ctrlaltca** [comment]
In #837 Jim made a nice review of our RNG and a comparison with different RNGs, and the conclusion is:
```
So, in the end, the entropy is good, there just seems to be room for speedup if it's worth having.
```

**Comment by tooomm** [comment]
Just for double checking:
Are [these comments](https://github.com/ctrlaltca/Cockatrice/blob/4e8ba699d2a003db734b134a51049fce3baecd39/common/rng_sfmt.cpp#L59-99) really not needed anymore?

There has been some more discussions about mutex and scaling within the shuffler in #59 by @VanNostrand and @MustyMustelidae .

**Comment by ctrlaltca** [comment]
Previously the code generated  uint64 random number and then sized it down to (min, max).
The comments were explaining the method used to complete such calculation.
The new code is generating a uint32 randmon number and using Isaku Wada's sfmt_to_real1() method to convert it to a float; then the float value is distributed (min, max).

Anyway, when looking again on the code, i see that the mutex is probably needed hen servatrice is configured to use a lot of threads, since we are using a single RNG_SFMT object and thus a single SFMT internal state.
I prefer ensured thread safety over speed, so i'll retire this PR.

**Pull request closed without merging**
