### PR TITLE
CPack DMG Installer with Background Image

### PR DESCRIPTION
**Pull request by SlightlyCircuitous**
## Related Ticket(s)
- Fixes https://github.com/Cockatrice/Cockatrice/issues/2256

## Short roundup of the initial problem
macOS 10.15/11 installer does not have a background image or drag to install functionality like a lot of modern packages for macOS.

## What will change with this Pull Request?
- Modifies CPack to build an installer for macOS with a background and drag to install functionality.

See https://github.com/Cockatrice/Cockatrice/issues/2256#issuecomment-1510028562 for detailed explanation of how this works. Essentially adds a background image and AppleScript to cockatrice/resources and modifies the CMakeLists file to point to those additions. The background image and AppleScript can really go anywhere as long as the CMakeLists points to the right place so they can be moved as needed if they are in the wrong place. 

Screenshot of built installer on macOS 11:
Screen Shot 2023-04-15 at 9 01 22 PM
(Yes, I know servatrice is misspelled here, it's fixed in the PR, I just don't have a screenshot of the new build with that fixed.)

### CODE REVIEW

**Comment by ebbit1q** [comment]
would it be possible to use a vector based image like svg for the background?

**Comment by SlightlyCircuitous** [comment]
GIMP won't export to svg, but I've changed it to a .eps, which is also vector. I started three separate build actions while editing so sorry about that.

**Comment by ebbit1q** [comment]
while eps can contain vector data it can also contain bitmaps, in this case gimp is only able to make bitmaps, if you're unable to it's fine as well.

**Comment by SlightlyCircuitous** [comment]
I could probably convert it using Inkscape or something similar, but it looks kinda fiddly, especially with multi-color images. I'll keep looking into it, but if its OK as is then maybe that could be a future PR.

**Comment by SlightlyCircuitous** [comment]
Checked the latest build and the background no longer shows up. Doubled checked that the file paths that I changed are correct so unless I missed something, it doesn't seem like .svg is an option.

**Comment by SlightlyCircuitous** [comment]
Trying to make a disk image manually on macOS 11 confirms that the View Options window simply does not accept .svg files for the background. I will revert this all back to the original .tiff.

**Comment by ebbit1q** [comment]
why is the image 3MB? that's rather big for such a simple image

**Comment by SlightlyCircuitous** [comment]
I think .tif files are just bigger because of the way they handle color information per pixel. I can make it a png (250 Kb) or a jpg (60 Kb) if you prefer. I don't think that the added color fidelity (?) is necessary here; I was just using .tif because that's what the cmake applescript example used.

**Comment by ebbit1q** [comment]
tif is a very flexible image format, it does not necessarily need to use 16 bit color, you can even use jpeg compression in tif files.

**Comment by ebbit1q** [comment]
either png or jpg would also suffice. if you think the jpg looks good enough then the small size is preferred. otherwise png would not have any artifacting.

**Comment by SlightlyCircuitous** [comment]
Ah, I see. I had missed GIMP's tif compression options previously. I've made one that is much smaller and it doesn't seem to have any artifacting on close inspection (the one I made using jpg compression did).

**Comment by ebbit1q** [comment]
background is a bit unclear as a filename, could you make it more specific like dmg background?

**Comment by SlightlyCircuitous** [comment]
I think I was overzealous on the rename. As far as I can tell from the documentation, the applescript/cpack expects the path to be .background:background.tif even if the filename is different. Seems like Cpack copies whatever is in CPACK_DMG_BACKGROUND_IMAGE to a new .backgrounds folder and then renames it. We'll see if I am right if the build works.

**Comment by ebbit1q** [comment]
cool, this seems ready, @ZeldaZach can you test it and see if you like the way this looks now?

**Comment by tooomm** [comment]
I like it 👍

Did you also try to have the "Cockatrice" title centered?

**Comment by SlightlyCircuitous** [comment]
Yes, I've tried the title centered and I don't think it looks particularly good with the rest of the arrangement, especially since that would put it right under the top bar with a centered 'Cockatrice'. Both the cmake example and the linked firefox example have it aligned left and I think it's a good look for this kind of thing.

**Comment by SlightlyCircuitous** [comment]
The raw .xcf that I used to create the background image is available [here](https://github.com/SlightlyCircuitous/image-storage) if anyone would like to edit the background in the future.

**Pull request merged**
