### PR TITLE
fixed wooger link not working

### PR DESCRIPTION
**Pull request by tooomm**
test description

### CODE REVIEW

**Comment by Daenyth** [comment]
@woogerboy21 it seems like this should work without the www

**Comment by ZeldaZach** [comment]
@woogerboy21 Told me he blocked the "direct root access" for some reason and it requires www... no idea why, but I don't really care

**Comment by woogerboy21** [comment]
Yes, I do not resolve my root domain (technically it does resolve but just not to were you think it should).  This way I can control the direction of traffic users take by cname usage in DNS.  This originally stemmed from not having static ip information.

**Comment by tooomm** [comment]
@woogerboy21 you want that changed back since you made it work without www now?

**Pull request merged**
