### PR TITLE
added <random> seed and cleaned up cdf, dropping the mutex.lock()

### PR DESCRIPTION
**Pull request by JimMcMahon**
Let me know if you think these changes are warranted. I posted issue #837 to show what the differences were, and the speed ups. I think if anything it's worth dropping  ```QDateTime::currentDateTime().toTime_t()``` for ```std::random_device```

### CODE REVIEW

**Comment by woogerboy21** [comment]
@Daenyth 
Looks like this is failing Qt4 builds in linux with this error:
```
/usr/include/c++/4.6/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.

In file included from /home/travis/build/Cockatrice/Cockatrice/common/rng_sfmt.cpp:1:0:

/home/travis/build/Cockatrice/Cockatrice/common/rng_sfmt.h:34:5: error: ‘random_device’ in namespace ‘std’ does not name a type
```

**Comment by JimMcMahon** [comment]
<random> requires the compiler flag to be set to c++11, I had assumed that was the case but never asked if there was a c++11 requirement. If the project hasn't started requiring c++11 i can drop the <standard> include in rng_sfmt.h and not use it to seed the random number generator.

**Comment by Daenyth** [comment]
Currently I believe we're on C++98

**Comment by ZeldaZach** [comment]
Well, that seems like we're *slightly* out of date then... can we potentially update the C++?

**Comment by Daenyth** [comment]
#127

**Comment by ZeldaZach** [comment]
Based on where we're at with the version of C++, I don't think this is a reasonable PR at this time.

Maybe when we get to updating C++ in #127, we can look into re-opening this PR for merging.

**Comment by ctrlaltca** [comment]
I think we could drop the usage of std::random_device but keep the the other changes related to dropping a mutex and speeding up the shuffling using floating point instead of uint64.

**Comment by ctrlaltca** [comment]
Upon further inspection (thank you @tooomm), it seems that removing the mutex could lead to problems when running servatrice as a multithreaded server, since all the threads share a single RNG object with a single smft state information.
I suppose we could just keep the code as it is by now. When #127 will be fixed, we could move to c++11's implementation of random and remove our SMFT code.

**Comment by ctrlaltca** [comment]
Closing until #127 will be addressed.

**Pull request closed without merging**
