### PR TITLE
Webatrice: improve prebuild steps and add .env configs

### PR DESCRIPTION
**Pull request by seavor**
Creates an `.env` file for server configuration.

### CODE REVIEW

**Comment by tooomm** [comment]
Take the version from package.json? The commit hash can be appended in brackets still?

**Comment by ebbit1q** [comment]
does this also handle setting the homepage?

**Comment by seavor** [comment]
> Take the version from package.json?

Autoincrementing the package.json::version is a bit more difficult, and we would still need to grab the value and place it in the .env file. Using the commit hash feels less user-error prone.

> does this also handle setting the homepage?

No, this is something i read today is required by create-react-app. I dont think there's anyway of knowing what the server's intended domain/homepage is.

**Comment by brentmclark** [comment]
If I'm reading this correctly, the `.env` file would be overwritten every time `prebuild` is ran regardless of the environment (dev, test, prod, etc.).  Am I reading that correctly?

If yes, how does this interact with CRA's support for environment-specific `.env` files such as `.env.production` or `.env.test`?

**Comment by ebbit1q** [comment]
instead of overwriting a .env file, wouldn't it make more sense to simply generate a `generated-version.json` file and .gitignore that?

**Comment by seavor** [comment]
> If yes, how does this interact with CRA's support for environment-specific `.env` files such as `.env.production` or `.env.test`?

After reading the docs, `.env` serves as the default level, and more specific env files like `.env.production` will run after and overwrite any identical variables.

**Comment by seavor** [comment]
> instead of overwriting a .env file, wouldn't it make more sense to simply generate a `generated-version.json` file and .gitignore that?

I think what I have here is fine for at least the first iteration, we can improve as the need arises.

**Comment by brentmclark** [comment]
I'm deeply suspicious about this implementation.  I think it will bite us at some point, but I can't cite anything specific at this time.

Given that this entire app is in active development with no actual users, I'm open to merging this PR anyway in the interest of progress.  I hope we continue to look for an alternative that can return the `.env` file to normal usage soon.

**Comment by seavor** [comment]
i have been moved by everyone's objections. Please see most recent changes.

**Review by ebbit1q — APPROVED** [review]
I like the new changes that merge the prebuild steps for the different systems into a crossplatform one

**Pull request merged**
