### PR TITLE
add rooster ranges, remove woogerworks

### PR DESCRIPTION
**Pull request by ZeldaZach**
Since WW is closing with the release of RR, I've changed all references over and added a clause to add it to the user's connection list if it does not already exist.

### CODE REVIEW

**Comment by Vafthrudnir** [comment]
If WW closes for good, shouldn't we remove it from the users' connection options btw?

**Comment by ZeldaZach** [comment]
I wasn’t sure how to remove WW, want to add to this PR? ❤️

**Comment by Vafthrudnir** [comment]
I'm not sure either, and working on an another issue rn. Maybe pull this PR as is, and create a new issue to remember to do it later?

**Comment by ZeldaZach** [comment]
I’ll see what I can come up with tonight

**Comment by ZeldaZach** [comment]
Figured out the remove and have implemented it. Feel free to re-test

**Comment by tooomm** [comment]
1) Are there any more details or background information? @woogerboy21 
It looks like you took the server over and re-branded it, Zach?

2) Is there a backup server etc. for RR, too?

3) With the build from this PR, `Woogerworks` is still in my `Connect` list:
connect list
I added the RR server manually before updating, so no idea if it would have added it correctly.

Looking at https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers @dev-id changed his server, too.
I never realized that in the connect dialog though. In code it's there (https://github.com/Cockatrice/Cockatrice/pull/3163/files#diff-601846fadf10ec28443e4b7013530e18R172), but I can still not select the server from the drop down in 2.5.1-beta as realized in the initial PR: https://github.com/Cockatrice/Cockatrice/pull/3051
Also, his old server got never deleted.

**Comment by skwerlman** [comment]
Why are the default servers hardcoded, and not stored in an XML? If they were in an XML, we could load them, then load known servers overwriting info from the XML in case of conflicts. We could have a field in the XML to mark a default as removed, which would cause the client to hide (but not forget!) settings from that site.
It'd have the same behavior from the user's perspective, but we wouldn't have to worry about all this fiddly stuff when one changes.

**Comment by Daenyth** [comment]
As with most questions about "why" trice does something some way; it's arbitrary - that's how it was written in the first pass and it hasn't changed.

I'd accept a change making it load known servers from xml

**Comment by Daenyth** [comment]
Or json. Please no more xml

**Comment by ZeldaZach** [comment]
Merging so I can work on my other PR

**Pull request merged**
