### PR TITLE
Webatrice: support hashed passwords in register and resetPassword

### PR DESCRIPTION
**Pull request by seavor**
## Related Ticket(s)
- Implements [HashedPassword for Register](https://trello.com/c/h5yNVMCx/21)
- Implements [HashedPassword for ResetPassword](https://trello.com/c/bOIpfKsZ/20)

### CODE REVIEW

**Review by ZeldaZach — APPROVED** [review]

**Review by ebbit1q — CHANGES_REQUESTED** [review]
I deployed this to beta but it seems to not use the hashed password field when registering while it does use the request salt command before

**Comment by ebbit1q** [comment]
actually, it doesn't seem to set the hashed password when logging in either

**Comment by ebbit1q** [comment]
it does use the hashed password when logging in normally by the way, just not immediately after registering

**Comment by seavor** [comment]
> it does use the hashed password when logging in normally by the way, just not immediately after registering

Good catch, it was set to use hashedPasswords for the register step, but not for the login post-activation step.

**Review by ZeldaZach — APPROVED** [review]

**Comment by ebbit1q** [comment]
while on master the subsequent login is now correctly hashed the registration event is not

logs from servatrice:
```
Mon Jan 31 22:04:56 2022 5575b08cf170 13 bytes [Command_RequestPasswordSalt.ext] { user_name: "aaaaaaaa" }
Mon Jan 31 22:04:56 2022 5575b08cf170 55 bytes [Command_Register.ext] { user_name: "aaaaaaaa" password: " ---value expunged--- " email: "aaaa@aaaa" real_name: "aaaaaaaa" clientid: "webatrice" }
Mon Jan 31 22:04:56 2022 Got register command:  "aaaaaaaa"
Mon Jan 31 22:04:56 2022 Accepted register command for user:  "aaaaaaaa"
Mon Jan 31 22:04:56 2022 Server::removeClient: removed 0x5575b08cf170 ; 0 clients;  0 users left
Mon Jan 31 22:04:56 2022 5575b08cf170 WebsocketServerSocketInterface destructor
Mon Jan 31 22:05:17 2022 Pool utilisation: QVector(0)
Mon Jan 31 22:05:17 2022 5575b094ff60 Incoming websocket connection: ::ffff:127.0.0.1 (::ffff:127.0.0.1)
Mon Jan 31 22:05:17 2022 5575b094ff60 13 bytes [Command_RequestPasswordSalt.ext] { user_name: "aaaaaaaa" }
Mon Jan 31 22:05:17 2022 5575b094ff60 42 bytes [Command_Activate.ext] { user_name: "aaaaaaaa" token: "+V8e1wQgxDUvRUpc" clientid: "webatrice" }
Mon Jan 31 22:05:17 2022 Accepted activation for user "aaaaaaaa"
Mon Jan 31 22:05:17 2022 5575b094ff60 344 bytes [Command_Login.ext] { user_name: "aaaaaaaa" clientid: "webatrice" clientver: "webclient-1.0 (2019-10-31)" clientfeatures: "client_id" clientfeatures: "client_ver" clientfeatures: "feature_set" clientfeatures: "room_chat_history" clientfeatures: "client_warnings" clientfeatures: "forgot_password" clientfeatures: "idle_client" clientfeatures: "mod_log_lookup" clientfeatures: "user_ban_history" clientfeatures: "websocket" clientfeatures: "2.7.0_min_version" clientfeatures: "2.8.0_min_version" hashed_password: " ---value expunged--- " }
Mon Jan 31 22:05:17 2022 Login accepted: password right
Mon Jan 31 22:05:17 2022 Server::loginUser: WebsocketServerSocketInterface(0x5575b094ff60) name= "aaaaaaaa"
```

**Pull request merged**
