### PR TITLE
Make server 12-factor compatible. 

### PR DESCRIPTION
**Pull request by basicer**
## Short roundup of the initial problem
- Hosting systems like heroku and dokku don't do well with config files.  Allow important settings to be changed via environmental variables. 

## What will change with this Pull Request?
- Some important variables can be set vie env variable.
- Add heroku compatible docker file.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
The change looks fine; if we merge it, we should document the usable env variables or at least add an example of how to use them in the wiki.

**Comment by ebbit1q** [comment]
There is a very clear advantage of sorting your package list, makes sure you don't have doubles :)

**Comment by ZeldaZach** [comment]
Nice catch @ebbit1q

**Comment by ZeldaZach** [comment]
@basicer When you get to documenting this on the wiki, ping me and i'll get this merged :)

**Comment by basicer** [comment]
### Hosting servatrice on PaaS platforms like Heroku

Servatrice will respect the `PORT` and `DATABASE_URL` environmental variables, using them instead of a config file if present.  When the `DATABASE_URL` variable is present, servatrice also assumes the `cockatrice` table prefix as well as `sql` mode for authentication and room creation.   `DATABASE_URL` should be a full mysql connection string: ex. `mysql://user:pass@host.com/databse`

**Pull request merged**
