### PR TITLE
[DO NOT MERGE] Theme manager - first part

### PR DESCRIPTION
**Pull request by ctrlaltca**
This is the first implementation of a theme manager.
By now it replaces the previous options for hand, table, stack, player, card background (only the one for invalid cards, currently being handled separately). 
The “zonebg” folder has been removed in favor of a “themes” folder where files have been reorganized in 5 different themes (one folder per theme).
The first time cockatrice will run with this patch, is will copy themes in place and setup the default theme.
This is the first part of the full implementation of a theme manager, that have been split to avoid making a giant, very hard to review commit.
Next parts will gradually include in the theme all the images and styles used in the UI in cockatrice.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Seems to be failing on Linux for a protocol of some kind.

I'll review this initial setup tomorrow and give my feedback

**Comment by woogerboy21** [comment]
The travis build threw this:
```
/home/travis/build/Cockatrice/Cockatrice/cockatrice/src/carddatabase.cpp:3:26: fatal error: themeManager.h: No such file or directory
```

**Comment by Daenyth** [comment]
Can we organize the images a bit? `Game/` folder, etc, to make it easier to
integrate other icons in later (user levels, counters)

**Comment by ctrlaltca** [comment]
I agree the images will need some organization when we'll move them all in the theme.
In reality, i don't see this like a good PR candidate for a merge, because i don't want to see an half baked theme support in the weekly builds (people complaining, etc).
I'd like to fix at least a thing before this gets into master: i imagine we'll add new images to cockatrice in the future, and will probably add them to the default theme. By now the bundled themes are copied to the user's profile directory only if the directory doesn't exists.
So, i'd like to find a way for cockatrice to understand when the bundled theme is newer than the copy in the user's profile directory, so that cockatrice will understand that the theme needs to be updated and copy the new resources.

**Comment by ctrlaltca** [comment]
So, the second version of this PR is ready.
Some explanations:
A theme is a folder in the $user_profile/themes folder. Themes can contain:
 * a version.txt file containing the version number (used for updates);
 * a style.css file that will be applied to the application (example usage: http://qt-project.org/doc/qt-4.8/stylesheet-examples.html );
 *  zones/ subfolder containing the zones background images;
 * one or more svg files that will be used in place of the resource they're named after (eg. a "genders/make.svg" file that will be used in place of the one we provide in cockatrice/resources)

Theme installation/update is handled this way:
 * cockatrice is shipped with some bundled themes (currently 5, an empty "default" and one for each old zone background)
 * when cockatrice is first run by an user, it will copy bundled themes into the user profile.
 * cockatrice checks if each bundled theme is installed, and will install only the missing ones, so if we add a new theme in the future it will get deployed to the user profile at the first run
 * each theme has a version number, cockatrice is able to check these numbers to determine if a bundled theme has been updated and install it over the old one in the user profile

My doubts:
 1. do we need to reorganize a bit better the existing images in cockatrice/resources?
 2. is supporting only svg files a problematic limit?

**Comment by ZeldaZach** [comment]
@ctrlaltca Is there a way to convert PNG/JPG's to SVG relatively easy? If so, maybe we can have a conversion tool online or something.

As for cockatrice/resources folder, I think we should only use that for things we don't want use customizable (such as the app icon, the arrows for the deck builder, etc) and move the rest over to a default theme option.

The default icons (the ones everyone uses as of now) should be moved to the "DEFAULT" theme folder and provide a small documentation (a README of some kind, can be short) to explain how to make themes and such to customize these around

**Comment by woogerboy21** [comment]
what is the reasoning behind copying the themes to the users home folder?

**Comment by Daenyth** [comment]
I'll try to test this soon

**Comment by ZeldaZach** [comment]
@Daenyth I really like how this is coming along

**Comment by ZeldaZach** [comment]
@ctrlaltca How is this coming along? It seems pretty awesome so far! :yum:

**Comment by ctrlaltca** [comment]
closing; will reopen a new PR when ready.

**Pull request closed without merging**
