### PR TITLE
[DO NOT MERGE] CMake: minimum requirements

### LINKED ISSUE #3259: raise qt minimum requirement in CMakeLists.txt
From https://github.com/Cockatrice/Cockatrice/pull/3258#issue-189923329:
>In CMakeLists.txt we require Qt 5.0.3, so we should probably raise that number, but i have no way to test all the old Qt versions on linux right now.

<br>

Linking https://github.com/Cockatrice/Cockatrice/issues/3005

### PR DESCRIPTION
**Pull request by tooomm**
## Related Ticket(s)
- Fixes #3259
- Related https://github.com/Cockatrice/Cockatrice/pull/3328 and #3005

## Short roundup of the initial problem
As mentioned in https://github.com/Cockatrice/Cockatrice/pull/3258#issue-189923329:
>Switched to the new methods. I'm unsure whether this will work on on ancient Qt version.
**EDIT:** it works with CMake >= 2.8.11 and Qt >= 5.1, so we should be fine.
In CMakeLists.txt we require Qt 5.0.3, so we should probably raise that number, but i have no way to test all the old Qt versions on linux right now.

## What will change with this Pull Request?
- Qt min req: 5.5.0
(Xenial has our lowest Qt version currently @ 5.5.1 / mac @ 5.11.1 / win @ 5.9.5 [5.11.1 possible])
Feature wise our min. requirement should be Qt5.4

- list (and maintain!) Qt and CMake (others too?) min. req. in README
**That's up for discussion**

---

This needs tests on older Qt versions!

### CODE REVIEW

**Comment by tooomm** [comment]
Former post in https://github.com/Cockatrice/Cockatrice/pull/3328

>Do we want to put all that min requirement hints in the README?
https://github.com/Cockatrice/Cockatrice/tree/tooomm-guards#build--
>
>We didn't have it before and we would need to maintain them...
Aren't the people compiling aware of such things or doesn't CMake etc. throws helpful error messages if
>- `cmake_minimum_required(VERSION 3.1)` 
https://github.com/Cockatrice/Cockatrice/blob/master/CMakeLists.txt#L9
>
>- or `FIND_PACKAGE(Qt5Core 5.0.3 REQUIRED)`
https://github.com/Cockatrice/Cockatrice/blob/master/CMakeLists.txt#L142
>
>are not matched?

**Comment by ZeldaZach** [comment]
My suggestion is CMAKE 3.1, QT 5.5

Not sure what you're asking

**Comment by tooomm** [comment]
>Not sure what you're asking

Do we want to put these min requirement hints in the README at all?

- We didn't have such an info before
- We need to maintain them which people will forget, and we end up with old/wrong info there again
- CMake tells the user at compilation time already what they need if they don't match it

**Comment by tooomm** [comment]
#3375 merged instead

**Pull request closed without merging**
