### PR TITLE
Allow URL redirects for card images

### LINKED ISSUE #1301: QUrl doesn't like redirects
It seems that if you're trying to download a card image from a URL and that URL then tries to redirect to where the image actually is, it will fail.

Example: I know the url `http://www.example.com/picture.php?card=Deep-Sea Terror&set=ORI` will redirect to `http://www.example.com/bingo/d/deep_sea_terror.jpg?m=1436903005` and if I have my custom URL set as `http://www.example.com/picture.php?card=!name!&set=!setcode!` then the following occurs:

```
Trying to load picture (set:  "ORI"  card:  "Deep-Sea Terror" )
Picture NOT found, trying to download (set:  "ORI"  card:  "Deep-Sea Terror" )
starting picture download: "Deep-Sea Terror" Url: QUrl("http://www.example.com/picture.php?card=Deep-Sea Terror&set=ORI")
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "ORI"  card:  "Deep-Sea Terror" )
```

### PR DESCRIPTION
**Pull request by ZeldaZach**
Fix #1301 

```
Trying to load picture (set:  "ORI"  card:  "Chandra's Ignition" )
Picture NOT found, trying to download (set:  "ORI"  card:  "Chandra's Ignition" )
starting picture download: "Chandra's Ignition" Url: QUrl("http://www.example.com?card=Chandra%27s Ignition&set=ORI")
following redirect: "Chandra's Ignition" Url: QUrl("http://www.example.com/c/chandras_ignition.jpg?m=1436902980")
```

Now follows the redirect for the card and loads appropriately.

Thanks @ctrlaltca for the help

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Has anybody tested this?

**Comment by ctrlaltca** [comment]
Sorry, had no time.. hopefully in a few hours.

**Comment by ZeldaZach** [comment]
Thanks :)

**Comment by ctrlaltca** [comment]
Tested and working :+1:

**Comment by Daenyth** [comment]
Nice work Zach!

**Pull request merged**
