### PR TITLE
remove numbers from the dice roll translatable strings

### LINKED ISSUE #1833: remove numbers from the dice roll translatable strings
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/messagelogwidget.cpp#L148

To prevent mistakes or make translators mix things up...
Basic dice functionality should be there in any case, and properly working!

### PR DESCRIPTION
**Pull request by tooomm**
fix #1833

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Looks good to me, will merge on completion

**Comment by ctrlaltca** [comment]
Just in time to break translations for every language 😍

**Comment by Daenyth** [comment]
I would have said leave this until after the release because of that. Too slow I suppose.

**Comment by tooomm** [comment]
Well, I was not aware that the fix is that simple (and more or less exactly the code that I already provided in the issue over two month ago) ;P

**Pull request merged**
