### PR TITLE
[WIP] Use QCommandLineParser instead of by-hand parsing.

### PR DESCRIPTION
**Pull request by Daenyth**
This will be more flexible for future CLI options

```
arg-parsing!Cockatrice/build *> ./servatrice/servatrice.app/Contents/MacOS/servatrice --help
Usage: ./servatrice/servatrice.app/Contents/MacOS/servatrice [options]

Options:
  -h, --help        Displays this help.
  -v, --version     Displays version information.
  --test-random     Test PRNG
  --test-hash       Test hash function
  --log-to-console  Write server logs to console
  --config <file>   Read server configuration from <file>
```

### CODE REVIEW

**Comment by Daenyth** [comment]
And apparently this class doesn't exist in Qt4...

So I think my options are:
- Scrap this completely
- ifdef for qt5 and maintain both parsing types
- Find a new dependency for qt4 that has decent parsing
- Make servatrice qt5 only.

**Comment by woogerboy21** [comment]
:+1:  for Qt5 only!

**Comment by ctrlaltca** [comment]
I agree servatrice can be qt5-only. This will remove also the dependence on libgcrypt.

**Comment by Daenyth** [comment]
Ok, I'll look at editing cmake for that

**Comment by ZeldaZach** [comment]
Any word on this?

**Comment by Daenyth** [comment]
I need to finish the CMake changes.

**Comment by ctrlaltca** [comment]
Shall we go ahed with the idea of a qt5-only servatrice? i can make the needed changed to cmake / CI scripts and prepare this PR for merging.

**Comment by Daenyth** [comment]
I don't object. Anyone else have comments before we do that?

**Comment by ctrlaltca** [comment]
Closed: see #1985

**Pull request closed without merging**
