### PR TITLE
readme - match new ts handling

### PR DESCRIPTION
**Pull request by tooomm**
Anything else that needs adjustments in this paragraph?

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Maybe we should remove also the "You should run this when contributing code that changes user messages." sentence, what do you think?

**Comment by tooomm** [comment]
I leave this to the heavy users. Not sure about the needed steps.
<br>
>`-DUPDATE_TRANSLATIONS=1` Configure `make` to update the translation .ts files for new strings in the source code. **Note: Running `make clean` will remove the .ts files.** You should run this when contributing code that changes user messages.

Which .ts files are removed? All? What's the use for this?
Is the last sentence referring to the clean command? Or to `-DUPDATE_TRANSLATIONS=1`?

**Comment by Daenyth** [comment]
It's referring to the make clean behavior when using update=1. It's not useful, it's a byproduct of how the make file is generated and used to update ts

**Comment by Daenyth** [comment]
And yes I'd remove the note about running it for pull requests

**Comment by tooomm** [comment]
removed

**Pull request merged**
