### PR TITLE
Contributing Doc Updates

### PR DESCRIPTION
**Pull request by ZeldaZach**

### CODE REVIEW

**Comment by ctrlaltca** [comment]
The fixes are good, i only see two debatable items here:
1. wether to advice CLion: i know it's good, but if you tell people to use it then they'll expect you to support it and help them fixing their problems with CLion;
2. the brace change: one brace per line is not the currently used style, do we really want to change it?

My personal opinion is:
 * no to item 1, unless the working is changed to something softer like eg. "some developers like to use.."
 * indifferent to item 2, it's just a matter of convenience on what style the current developers prefer to maintain.

@Daenyth your opinion is definitely needed here (others, too).

**Comment by ZeldaZach** [comment]
Updated based on feedback

**Comment by ZeldaZach** [comment]
@Daenyth I'll start looking into clang-format soon

**Comment by tooomm** [comment]
`clang-format` issue is https://github.com/Cockatrice/Cockatrice/issues/2183

**Pull request merged**
