### PR TITLE
Fix unbalanced save() restore() in cards painter.

### PR DESCRIPTION
**Pull request by basicer**
## Short roundup of the initial problem
There are thousands of spam lines in console saying `QPainter::end: Painter ended with 2 saved states`

## What will change with this Pull Request?
No more of that.

### CODE REVIEW

**Comment by tooomm** [comment]
Hmm, the debug log dialog windows seems to be negatively effected...
Does it still work for you @basicer ?

**Comment by ctrlaltca** [comment]
@tooomm i'm afraid the mess in the debug log is caused by #3567

**Comment by tooomm** [comment]
I guess it is ok to fix it up here?

Or do you want to open a separate PR and update this pr from master? @ctrlaltca

**Comment by ctrlaltca** [comment]
> Or do you want to open a separate PR and update this pr from master? @ctrlaltca

Done, #3572

**Pull request merged**
