### PR TITLE
added gender neutral and unspecified gender cases for each string

### PR DESCRIPTION
**Pull request by realityfabric**

### CODE REVIEW

**Comment by Daenyth** [comment]
Github won't even show me the diff - I'll have a look locally on my machine when I can. I know this was a ton of work, so thanks up front!

**Comment by realityfabric** [comment]
Should I have broken up the commits into smaller chunks so that GitHub would be able to manage it? I didn't realize that large commits would fail to display on GitHub

**Comment by Daenyth** [comment]
Nope, one commit is correct - github just doesn't like to display diffs that are large in a single file. It wouldn't display them collectively if you split commits either.

**Comment by Daenyth** [comment]
The idea being I think that generally changes like that are, for example, rewrites of svg files - the lines don't matter as much as the result.

**Comment by realityfabric** [comment]
Okay, makes sense. Let me know if I missed anything, I just focused on all the places where there was an isFemale function call

**Comment by Daenyth** [comment]
I think hitting that should cover them all.

**Comment by tooomm** [comment]
linking #487

**Comment by ZeldaZach** [comment]
Any word on the review of this? Travis said it failed, but I can't view the changes easily.

**Comment by Daenyth** [comment]
I haven't had much time for anything this week. Will get to this as soon as
I can. You can view the diff manually locally

**Comment by ctrlaltca** [comment]
The code seems ok; i also checked transifex, and it will show the gender disambiguation comment correctly. I see that the gender is correctly used to get a different translation for all the strings containing a pronoun (his/her/...).

It's also used in other strings where there's no pronoun involved (like line 43: You have joined game %1); Is this needed to support other languages, where the same sentence could have different translations depending on the gender of the user?
Some strings, instead, have no per-gender specific translation (eg. lines 695 and 698). Is this wanted or those lines have just been missed in the commit?

Another question: from a translator-specific point of view, what's the difference between "unspecified gender" and "gender neutral"?

Last, the logCreateArrow() handling is insane.. to bad qt offers no way to handle such cases.

**Comment by Daenyth** [comment]
Unspecified is for when the person hasn't selected anything. Neutral is for when they've selected neutral pronouns (common in the queer community if the person doesn't identify strictly along binary lines)

**Comment by ctrlaltca** [comment]
Thank you, i made some good readings on the queer topic and now understand the meaning of the neutral pronouns.

**Comment by ctrlaltca** [comment]
As @tooomm pointed out, https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/cardzone.cpp#L47 needs to be fixed, too.

**Comment by Psithief** [comment]
If you want to do this right, replace all instances of `female` with `feminine` and `male` with `masculine` as well.
`female`, `male` are sexes, not genders.

(I don't actually care about these issues, I just can't stop the QA)

**Comment by Daenyth** [comment]
Yes, that would be better.

**Comment by realityfabric** [comment]
While changing it to feminine and masculine are fine, and I don't want to get into heavy detail here because it's not really relevant to the project itself, Sex and Gender are not separate things, they are both social constructs, and there is no good reason to distinguish them from each other.

**Comment by Psithief** [comment]
Letting users choose a gender was unnecessary in the first place. :+1:

**Comment by Daenyth** [comment]
Yeah. It was added mostly for translation purposes I think. I wonder about
removing it entirely and just using neutral everywhere.

**Comment by ZeldaZach** [comment]
Can we do anything with this right now?

**Comment by Daenyth** [comment]
Honestly I'm wondering if it's not worth removing the option to set it and just go with neutral pronouns throughout as most software does. I haven't decided. Community feedback would be helpful perhaps.

**Comment by ZeldaZach** [comment]
I'm fine with going to genderless in game. It's irrelevant for the most part (and we can put all translations to masculine)

**Comment by Daenyth** [comment]
I'd leave it to the translators to decide how best to approach it at that point.

**Comment by Daenyth** [comment]
In any case, leaving this open for now won't hurt anything

**Comment by realityfabric** [comment]
It would definitely be easier, in English, to go genderless across the board. It would definitely cut down on the number of switches, and probably cut down on the amount of nested logic in general for messages.

**Comment by ctrlaltca** [comment]
:+1: for genderless anywhere

**Comment by tooomm** [comment]
it seems very reasonable to make things easier here. the benefit might not be worth the effort for such a small project. translations are bloated and difficult to handle for the ordinary player that just want to help a bit, too.

any problems we might run into with translations for other languages?
like special cases in some languages?

but in general, translators should be able to deal with language specialties:
>I'd leave it to the translators to decide how best to approach it at that point.

**Comment by ZeldaZach** [comment]
So what's the plan with this?

**Comment by Daenyth** [comment]
I think we can leave this open until either someone picks it up and updates it, or we decide on the path to removing selection in favor of all-neutral.

**Comment by Daenyth** [comment]
I appreciate the work that went into the PR but at this point I think we've decided to remove the pronoun code entirely to streamline translations - we'll just use exclusively default language from here.

**Pull request closed without merging**
