### PR TITLE
Refreshed the look of the default pawns

### PR DESCRIPTION
**Pull request by poixen**
+ Solid colors.
+ Could help with race issues now skin tone is removed.
+ Feels more modern

guy
guy2
users

### CODE REVIEW

**Comment by poixen** [comment]
For comparison we currently have:
r1
r2
r3

**Comment by ZeldaZach** [comment]
I'm happy with this and works as expected :)

**Comment by Daenyth** [comment]
Can we keep the white/black? I really like it...

**Comment by ZeldaZach** [comment]
We tried white/black and it looked very ugly...

**Comment by poixen** [comment]
Updated to use BW mod icon and star

**Comment by poixen** [comment]
Updated icons to be solid color, updated image examples

**Comment by Daenyth** [comment]
I'm not sure if this is intended or if it's a github display issue - it looks like the mod icon left side is transparent rather than white. Should we make it white or is it like this intentionally?

**Comment by poixen** [comment]
Good find, fixed it

**Comment by Daenyth** [comment]
Ready to merge, I'll leave it open for today in case anyone had more feedback

**Comment by ZeldaZach** [comment]
I'll try this out

**Comment by ZeldaZach** [comment]
I'm fine with this. I tried all levels and they seem sweet!

**Pull request merged**
