### PR TITLE
Updated filter svgs

### PR DESCRIPTION
**Pull request by poixen**
Now uses the same as in the deck editor

deckeditor

new filters

### CODE REVIEW

**Comment by Daenyth** [comment]
:+1:

**Comment by tooomm** [comment]
I don't like the clear filter logo... You can't really recognize anything, too similar and too overloaded. Simply the red circle would be better imo! (a bolder variant maybe)

**Comment by tooomm** [comment]
you updated the translation source as well inside this pr?!

cmake -DUPDATE_TRANSLATIONS=ON ?

**Comment by poixen** [comment]
Yea seems like I had it on. Shouldnt matter as the do a single remake of the translations each week?

**Comment by tooomm** [comment]
We have no strict schedule yet. @ctrlaltca did it every other week.
I don't mind if you want to update it.
But to avoid conflicts etc. you should make a separate pr and make sure to run it on the master branch.

We had already problems mixing it up with other commits.

**Comment by poixen** [comment]
Once the rest of my prs are in, i will make a build with translations on and PR it.

**Pull request merged**
