### PR TITLE
add a bunch of parents to dialogs

### LINKED ISSUE #998: missing 'trice icon for several dialog windows
https://github.com/Cockatrice/Cockatrice/pull/840#issuecomment-81722310

Maybe other dialog windows than the listed ones are affected as well:
- `Show this user's games`
  (as poixen mentioned in his comment, if you open this and close Cockatrice, the user's games window won't close with the app)
- `Load deck from server`
- `Create token`
- `Game information`
- `Manage sets...`
- `Edit tokens...`
- `Reveal top cards of library` the one, where you put the amount of cards you want to reveal
  (maybe other reveal/show dialogs as well or where you get asked about how many (dice e.g.))

no icon:
dialog window-noicon

should be:
dialog window-withicon

---
- `Die roll` got fixed: #1065

### LINKED ISSUE #3651: Dialogs created from play have improper modality on linux
All dialogs you create from play, like set counter and draw cards, behave differently from other modal dialogs, like settings and about.

These dialogs will, instead of blocking access to the main window, rapidly switch focus back to the dialog when focus is moved.

This problem is fixed by changing the dialog's parent to the main window instead of null-ing it.

Client Operating System: Ubuntu 18.04.2 LTS
DE: GNOME 3.28.3

I found this while testing #3646, it does not occur on windows or osx.

### PR DESCRIPTION
**Pull request by ebbit1q**
fixes #998 
fixes #3651 

Simply replaces a bunch of dialog's nullptrs with some proper values.

### CODE REVIEW

**Comment by tooomm** [comment]
Looks like this helps with https://github.com/Cockatrice/Cockatrice/issues/998 as well!

**Comment by ebbit1q** [comment]
Yes.

**Comment by tooomm** [comment]
From #988, `Manage sets...`, `Edit tokens...` and `Reveal top cards of library` dialogs are fixed so far with this PR.

**Comment by ebbit1q** [comment]
Any dialogs that still need fixing?

**Comment by tooomm** [comment]
- Show this user's games
- Load deck from server
- Create token
- Game information

**Comment by ebbit1q** [comment]
I don't know where the game info window is, this pr is ready for review now.

**Comment by tooomm** [comment]
I will try to go through all client tomorrow again. 👍 

<br>

>I don't know where the game info window is

When in a game, `Game` menu --> `Game Information`

**Comment by ebbit1q** [comment]
Those are the different modality settings.

**Comment by tooomm** [comment]
This fixes #998 now.
Does it also fix #3651 for you @ebbit1q?

clang-format is failing btw

**Pull request merged**
