### PR TITLE
Cards played face down always go untapped to main row.

### LINKED ISSUE #331: Shift-clicking to play a card face down reveals information about the card's type
When you use shift+click to play a card face down, the client automatically places it in its appropriate row on the battlefield, which reveals information about the card's type. (lands get placed in the back row, creatures in the front, instants and sorceries get played to the stack.) Given that you usually play things face down to hide the identity of the card, this is a bit of a problem. It would be best if shift-clicking on a card had a consistent result no matter the card type: playing the card to the front row face down. 

Specific examples of where this reveals information: hideaway lands, liliana discards, show and tell choices, and non-creature morphs (the placement of zoetic cavern and lumithread field reveals their types).

The current workaround is to shift+drag the card into play, but it would be nice if this were fixed.

### PR DESCRIPTION
**Pull request by Daenyth**
Fix #331

### CODE REVIEW

**Comment by ctrlaltca** [comment]
Tested the PR, and all the cards are put in the 2nd tablerow when played face-down, as expected :+1:
Anyway, there are still some problems:

1. When shift+double clicking a card that normally gets into play tapped, it still gets into play tapped facedown.
An additional fix needs to be applied to CardItem::playCard() or, as an alternative, the current fix in Player::actPlayFacedown() can be reverted and a more generic fix can be applied at Player::playCard():1595
```
cardToMove->set_tapped(faceDown ? false : tapped);
```

2. If you play 2 cards with the same name facedown, they gets stacked, so the opponent knows that those 2 cards are the same.

**Comment by Daenyth** [comment]
Thanks. Will look at those tonight

**Comment by ctrlaltca** [comment]
I unfortunately committed directly to your branch, sorry for that; anyway:
 * the "don't play facedown cards tapped" has been resolved as suggested previously;
 * the fix for "don't stack facedown cards with same same" requires modifications to the server code (that actually calculated cards coordinates). The changes can be tested in local game mode without the need of an updated server.

**Comment by Daenyth** [comment]
I'll have a look tonight

**Comment by ZeldaZach** [comment]
Any progress on this?

**Comment by Daenyth** [comment]
This looks ready to merge to me.

**Pull request merged**
