### PR TITLE
add ubuntu 20.04 to travis

### PR DESCRIPTION
**Pull request by ebbit1q**
Enables tests and debug on the newest ubuntu lts, we should keep 18.04 around until users migrate.

### CODE REVIEW

**Comment by ebbit1q** [comment]
what even is this
```
Setting up tzdata (2019c-3ubuntu1) ...

debconf: unable to initialize frontend: Dialog

debconf: (TERM is not set, so the dialog frontend is not usable.)

debconf: falling back to frontend: Readline

Configuring tzdata

------------------

Please select the geographic area in which you live. Subsequent configuration

questions will narrow this down by presenting a list of cities, representing

the time zones in which they are located.

  1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc

  2. America     5. Arctic     8. Europe    11. SystemV

  3. Antarctica  6. Asia       9. Indian    12. US

Geographic area: 
```
we need to give input?

**Comment by ebbit1q** [comment]
It's as I feared, the same error I get locally, a compile warning inside a qt header:
```
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qlocale.h:43,

                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h:46,

                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:49,

                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QDebug:1,

                 from /src/common/decklist.cpp:4:

/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h: In constructor 'QVariant::QVariant(QVariant&&)':

/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:275:25: error: implicitly-declared 'QVariant::Private& QVariant::Private::operator=(const QVariant::Private&)' is deprecated [-Werror=deprecated-copy]

  275 |     { other.d = Private(); }

      |                         ^

/usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:401:16: note: because 'QVariant::Private' has user-provided 'QVariant::Private::Private(const QVariant::Private&)'

  401 |         inline Private(const Private &other) Q_DECL_NOTHROW

      |                ^~~~~~~

cc1plus: all warnings being treated as errors

make[2]: *** [common/CMakeFiles/cockatrice_common.dir/build.make:76: common/CMakeFiles/cockatrice_common.dir/decklist.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....

make[1]: *** [CMakeFiles/Makefile2:1124: common/CMakeFiles/cockatrice_common.dir/all] Error 2

make: *** [Makefile:163: all] Error 2

The command "RUN --server --test --debug" exited with 2.
```

**Comment by ebbit1q** [comment]
https://codereview.qt-project.org/c/qt/qtbase/+/272258

**Comment by ZeldaZach** [comment]
Seems like that code review hasn't gone very far...

**Comment by ebbit1q** [comment]
This is ready, we can move testing to the latest lts at another time, when this bug in qt gets fixed probably, I'm not feeling much for adding a workaround in the cmake files.

**Comment by tooomm** [comment]
I don't like a workaround either.
Maybe put a comment regarding the issue (link to this pr or qt bug?) as reference and reminder.

**Pull request merged**
