### PR TITLE
Spell Out Entire Counter Names With First Letter Capitalized

### LINKED ISSUE #3991: Change colorless counter name from X to C
Initially reported by @Caledor in #3499

>Change counter name for colorless from `x` to `c` as per Oath of the Gatewatch rule update (colorless mana symbol introduced)

<br>

Note: This is a magic specific change, but in this part of the client we are magic related currently.
As long as there is no game plugin system etc. it might be worth the change (https://github.com/Cockatrice/Cockatrice/issues/1740).

### LINKED ISSUE #3992: Capitalize player counters
Player counters should be `W`, `U`, `B`, `R`, `G` and `C` (See https://github.com/Cockatrice/Cockatrice/issues/3991), as well as `Life` and `Storm`:

counter_cap

### PR DESCRIPTION
**Pull request by Rocangus**
## Related Ticket(s)
- Fixes #3992
- Fixes #3991 

## Short roundup of the initial problem
Player token names are displayed all lower case.

## What will change with this Pull Request?

- Counter "life" will display as "Life"
- Counter "w" will display as "White"
- Counter "u" will display as "Blue"
- Counter "b" will display as "Black"
- Counter "r" will display as "Red"
- Counter "g" will display as "Green"
- Counter "x" will display as "Colorless"
- Counter "storm" will display as "Other"

## Screenshots
cockatrice_ncWd0dHWCx

### CODE REVIEW

**Comment by ebbit1q** [comment]
I feel like the name CapitalizeCounterName no longer reflects what the class does, all it does is translate.

**Comment by Rocangus** [comment]
> I feel like the name CapitalizeCounterName no longer reflects what the class does, all it does is translate.

I suggest a renaming to TranslateCounterName to make the name reflect what is being done.

**Comment by tooomm** [comment]
It works and looks nice in the client!

Question:
What do you think about a more general, less mtg-centric, term for the "Storm" counter?
We could simply use `Other` for example. (Not server side yet, but user facing at least)

**Comment by Rocangus** [comment]
Using the term `Other` could be good even for MtG. For instance, if you use that counter to keep track of Commander tax while playing EDH format, such a name could work well. Besides, now that we have the class set up, any further changes will be easy to make since there is one place to edit these translations, at least currently.

**Pull request merged**
