### PR TITLE
improve provided info in "edit sets"

### PR DESCRIPTION
**Pull request by tooomm**
## Short roundup of the initial problem
 - Info text was just too much and not very well highlighted

## What will change with this Pull Request?
- Short phrasing
- Highlighted info about card art handling

## Screenshots
- before
editssets_before

- after
editsets_after

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I made some changes:
screenshot 2017-04-25 00 45 29

**Comment by BrierFox** [comment]
Hello guys,
I want to start off by saying that I am in no way a programmer, but just throwing an idea out there since you two are the closest I have found when asking a question that directly relates to the custom sets and their respective menu.

I am new to Cockatrice. I've obviously fallen in love with it since I've taken the steps to get here and find someone actually working on the coding, rather than just sitting in the lobby and saying, "I don't know." I have searched for several hours now, (and when you hear my point, you're going to say, "You could have just had it done by now.", but that's not the point. The point is to just get an idea to the people who have the know-how of possible making it happen... Assuming it can be done period, due to the possible merging of already written code, or even the opposite and requiring the deconstruction of the already established setup... (My apologies for the lengthy introduction. Just wanted to at least attempt to establish that effort has been put forth out of respect, nothing more. Remember, I know nothing of coding.)

Ok. When creating a new deck within the deck editor, there is already access to this "Edit Sets" menu, access to the "Set Code", and the ability to cherry-pick the desired individual sets,  by set name, that one would like to use when searching the card database. However, the lengthy process itself of  "Disable  All Sets" or "Enable All Sets"  comes to light when you become aware of the understandably large population of players that thrive on pointing out "illigal" cards within a Game Type's regulations.
Obviously jumping to the official Rules & Formats page, I realized how many sets where actually defined in each of the formats, and how many clicks of the mouse were just required of me to customize the "Edit Set" window so that I would ONLY HAVE the sets included in that specific Format. (Standard, Modern, Vintage, etc.. ).... I thought, "There's gotta be a filter I'm missing, or at the least be able to download something that would allow me access to a button/menu/something that resembled similar actions taken in the importation of .xml files." that could just separate these sets with a few clicks and be on my way..... I asked, searched, and rearranged all sorts of junk in hopes I would stumble across the Gotta-Be-There solution..... I failed.... 
(And yes, the hours of searching online, adding to it the creation of an account on GitHub and the writing of this email, could have instead been spent clicking each individual box of the "legal sets" that my format required........... I took the harder of the routes.)

I was also told by the community in the lobbies that they weren't aware of the possibility to do so, or if it even existed to begin with. Does it? Is it possible? How crazy do I actually sound? Do I need a beer at this point? I can only answer one of these questions.... The others are for you.

If you actually made it through my rambling, I thank you.
Just an observation that, for whatever reason, drove me to the compulsive completion of this ridiculously involved inquiry.

Here's to you guys... I'm going to pass out backwards over this chair now... My brain has frosted over.

~BrierFox
(Kyle Million)-WKM


...lol, that was actually a fun adventure. All the best to both of you!

**Comment by skwerlman** [comment]
@BrierFox That suggestion is already covered by #215.

**Comment by BrierFox** [comment]
@skwerlman Awesome. Thank you for the response! I read #215 and didn't see a conclusion in the discussion. Am I missing it, or was it resolved? I like how this had been brought up several times before. Definitely a bit demoralizing when people constantly yell at you over one or two cards every deck.

**Comment by skwerlman** [comment]
@BrierFox It hasn't been implemented yet, no. Originally, it wasn't done because it required a 36MB file because Oracle didn't yet have the ability to parse the zipped versions of MTGJSON. Now that Oracle can handle those files, it should be a more reasonable feature to implement.

Either way, further discussion should really happen in #215, to keep it in one place.

**Comment by tooomm** [comment]
@ZeldaZach yeah, why not...

**Pull request merged**
