### PR TITLE
Fixed image centering

### LINKED ISSUE #1202: Card images not centered proprely
When a card is in play i can see through the bottom part of the card.
cockatrice images

i know its not a major bug but i find it really annoying.

### PR DESCRIPTION
**Pull request by poixen**
Fix #1202

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Seems good to me. :shipit:

**Comment by woogerboy21** [comment]
:shipit:

**Comment by ZeldaZach** [comment]
Minor fix, not adding to release notes (unless you think it's necessary @poixen)

**Comment by poixen** [comment]
Nah.

**Pull request merged**
