### PR TITLE
Updated hand and table color

### PR DESCRIPTION
**Pull request by poixen**
Updated default colors, darker, more modern, slick. 
Great feedback from community!

dark

### CODE REVIEW

**Comment by tooomm** [comment]
I like it! :+1: 

Is the old look gone with this pr or still available if someone want to switch back?

**Comment by ZeldaZach** [comment]
I think it's very cool, just maybe it's a bit too dark

**Comment by poixen** [comment]
I just replaced the values. I guess I can make a dark mode switch in the settings.

**Comment by Daenyth** [comment]
These only apply to people with no board theme right?

**Comment by poixen** [comment]
yeah

**Comment by Daenyth** [comment]
Then I think it's fine

**Pull request merged**
