### PR TITLE
Hide non-existent card values in infowidget and cardframe

### LINKED ISSUE #2972: card preview in chat contains empty values
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
Version 2.4.1-custom_e12b508 (2017-12-18)

__________

When clicking on a linked `[[card name]]` in the chat this window will appear:
empty_values

It should not display any non-existent values!

### PR DESCRIPTION
**Pull request by berserkingyadis**
## Related Ticket(s)
- Fixes #2972

## Short roundup of the initial problem
When clicking on a card linked in the chat (or displaying it in the deck editor), it contains emtpy values. For example Power/Toughness for spells or mana cost for lands.
34120202-1c3c75d0-e425-11e7-89d1-f8c9eb152e78

## What will change with this Pull Request?
- Empty fields will be hidden in both the Infowidget (clicking on cards from chat) and the Deckeditor
- Cards without color will have the Color string "Colorless"

## Before
before
before2

## After
after
after2

### CODE REVIEW

**Comment by tooomm** [comment]
>Cards without color will have the Color string "Colorless"

That's also a nice addition! 👍

**Comment by berserkingyadis** [comment]
What about the CardinfoWidget which opens when clicking a card which does not exist? (Example: [[Gozilla]])

Currently its this

404before

i could change it to this (text hidden, only cardback)

404after

I realize this is not the most optimal solution but it could be done easily.

**Comment by ZeldaZach** [comment]
Make sure you run the `./clangify.sh` at the top level so your code gets formatted correctly! :)

**Comment by ZeldaZach** [comment]
I also like the idea of having a blank card / nothing show when you hover over a bad card (something that's not found in your local db)

**Comment by Daenyth** [comment]
I like the idea of having the "card missing" back image showing a label under the card back image showing "unknown card: $name"

**Comment by berserkingyadis** [comment]
Unknown cards now look like this in the CardInfoWidget

gozilla

This should be everything, someone please test this. This PR affects the cardframe in the deckbuilder, the cardinfowidget when clicking on a linked card and the cardframe in the game view (when hovering over a card for example).

**Comment by Daenyth** [comment]
Awesome! This is really exciting :)

**Comment by Daenyth** [comment]
@berserkingyadis Thanks so much for the contribution, and congrats on your first merge! :)

**Pull request merged**
