### PR TITLE
Restore xsd files removed in #1428

### PR DESCRIPTION
**Pull request by Daenyth**
ಠ_ಠ

### CODE REVIEW

**Comment by tooomm** [comment]
you mean #1432 ;)

What do we need them for?

**Comment by Daenyth** [comment]
They provide API documentation and a method of automated validity checking. You can run a tool using the xsd and it can determine whether a cards.xml or tokens.xml file is valid according to the schema or not

**Comment by Daenyth** [comment]
We could also adjust the card database so that instead of hand coded objects we could parse the xsd files to automatically generate the card classes.

**Comment by Daenyth** [comment]
One low-hanging fruit is adding a headless mode to oracle. We could then run it from travis. The XSD could be used to assert that oracle generates valid card databases.

**Pull request merged**
