### PR TITLE
skip all duplicate promos instead of just stars

### LINKED ISSUE #3964: [Ikoria] Wrong picture for many cards
Hello,

Many pictures downloaded with oracle for the “Ikoria” extension are not the default one.
There is even one in Japanese: Mysterious Egg
Many other cards are getting alternate art instead of the original one’s example: auspicious Starrix; Brokkos, Apex of Forever; cloudpiercer; glowstone recluse; ....
I have not check them all. Can you help us fixing this automatically instead of manually through the custom images?

Sincerely,

Danyfire

### PR DESCRIPTION
**Pull request by ebbit1q**
fix #3964
see #3904 which did this for all unique numbers, now this has been replaced with unique names because that's what we care about anyway and cards that have the isPromo field are added to it as well.

### CODE REVIEW

**Comment by ebbit1q** [comment]
Note this removes cards like godzilla entirely, so people that want these cards will have to use custom images instead. An alternative solution to this would be to automatically generate an additional set to hold these duplicate cards but the custom image folder is a better system for these people anyways as they only want some of these promos and not all of them.

**Comment by ebbit1q** [comment]
https://travis-ci.org/github/Cockatrice/Cockatrice/builds/678126222 ci competed but it's not reflected here :/

**Comment by ZeldaZach** [comment]
I'd like to see the cards split up on Cockatrice's end into separate internal sets. Removing godzillas entirely is a bleh thing. Will still merge if it addresses issues, but I'd like that fixed

**Comment by ebbit1q** [comment]
do you want godzilla to be an entirely separate card instead of an alt art for it's original card?

**Comment by ZeldaZach** [comment]
This goes along w/ the plan of changing how we load in specific cards. Should have a way for people to specify their art, even if local only. Maybe with a dropdown menu per-card saving in the cache?

**Comment by ebbit1q** [comment]
Apparently there is no original zilortha card so godzilla doesn't get removed, this pr only removes promos if they are duplicates of another card in the same set.

**Pull request merged**
