### PR TITLE
appveyor: use provided OpenSSL again

### PR DESCRIPTION
**Pull request by tooomm**
## Short roundup of the initial problem
External OpenSSL was used because of some former issues with bundling, see https://github.com/Cockatrice/Cockatrice/pull/3020.
These problems seems to be solved.

## What will change with this Pull Request?
- use OpenSSL from appveyor again to cut down on external dependencies: https://www.appveyor.com/docs/windows-images-software/#tools

### CODE REVIEW

**Comment by ctrlaltca** [comment]
I've tried downloading the resulting artifact from appveyor and looking at the imports of libeay32.dll and ssleay32.dll. They depends on msvcr120.dll, so they need the ms visual c++ 2013 redistributable, while the rest of cockatrice and its dlls depends on msvcr140.dll (msvc++ 2015/2017).
So, this is not going to work yet.

**Comment by tooomm** [comment]
Hmm, did you try it?
I only checked that the appveyor build passed and the logs say OpenSSL was found. I then installed it locally to run Oracle. I was able to download cards and tokens via two https links which should only work with OpenSSL?
https://mtgjson.com/json/AllSets.json.zip
https://raw.githubusercontent.com/Cockatrice/Magic-Token/master/tokens.xml
No debugging info though, since Oracle doesn't print to the `Debug Log` in Cockatrice.

Client Version: 2.6.1-custom(552c37a) (2018-10-28)
oracle-552c37a

**Comment by ctrlaltca** [comment]
Of course it works, it used to work also in the past.
It won't work only on computers where the needed msvcr120.dll is not available because nothing else installed that runtime version yet.

**Comment by tooomm** [comment]
Oh sure, got you. We definitely want to stick with one single msvcr dependency!
Regarding all the issues user brought up to us with that. :)

Thank you for clarification @ctrlaltca!

**Comment by tooomm** [comment]
Any idea if using the even newer `OpenSSL 1.1.0i ` Appveyor provides as well has the same issue? @ctrlaltca 

https://www.appveyor.com/docs/windows-images-software/#tools

**Pull request closed without merging**
