### PR TITLE
Increased default pixmap cache

### PR DESCRIPTION
**Pull request by poixen**
From 256 -> 2047

### CODE REVIEW

**Comment by Daenyth** [comment]
@masscraziness you have a VM right? Can you try setting cache to max with the VM limited to 1gb ram?

**Comment by poixen** [comment]
I dont have a VM at home right now. Im also pretty messed up so dont want any heavy projects.

**Comment by ZeldaZach** [comment]
I see no issues bumping this up to 2047 as that's the maximum limit, and it's what I use

**Comment by tooomm** [comment]
@ZeldaZach check #729 too

**Comment by MassCraziness** [comment]
Sure @Daenyth I'll do it in a bit when I get on

**Comment by woogerboy21** [comment]
i believe the reason the whole memory configuration option was created was for lower memory based computers.  What is a good starting point for the setting could be up for debate though.  To me 2048 is to high.

**Comment by MassCraziness** [comment]
I think 512 is a fair starting point.

**Comment by woogerboy21** [comment]
I was thinking either 512 or 1024.  Nothing says a user cant lower it as well.

**Pull request merged**
