### PR TITLE
Sounds on buddy login & logout.

### LINKED ISSUE #1764: Add sound category for buddy connecting/disconnecting to the server
Were there ever any thoughts on custom sounds for when Buddied users enter?

### PR DESCRIPTION
**Pull request by Fizztastic**
Fix #1764 
Add Files: buddy_join.wav; buddy_leave.wav

### CODE REVIEW

**Comment by Daenyth** [comment]
Code looks reasonable. :shipit: once tested.

Can you amend the commit to include a "fixes #n" for github?

**Comment by Fizztastic** [comment]
Do you mean add Fix #1764 to the title? Because the text already has it.

**Comment by Daenyth** [comment]
No, I mean the commit message itself - just `git commit --amend`, include that text and then `git push --force` on this branch

**Comment by ctrlaltca** [comment]
Code is ok and works just fine.

**Comment by Daenyth** [comment]
Can someone update the wiki to note the new sound theme option?

**Comment by Fizztastic** [comment]
Done.
> Can someone update the wiki to note the new sound theme option?

**Comment by Daenyth** [comment]
Thanks!

**Pull request merged**
