### PR TITLE
Append last commit date to version string; fix #1036

### LINKED ISSUE #1036: ascending versioning instead of random hashes
You can never tell, just from viewing the hash in the about dialog, how old a client is.
This makes bug reports etc. more difficult. Users can't easily compare their versions or know when they should upgrade, too.

Did some quick research and found these links, hope they help:
- http://brianmilco.blogspot.de/2012/11/cmake-automatically-use-git-tags-as.html
- http://eatmyrandom.blogspot.de/2010/06/automate-version-numbering-using-git.html
- http://pukkaone.github.io/2010/12/19/build-number-git-repository.html
- http://stackoverflow.com/questions/1435953/how-can-i-pass-git-sha1-to-compiler-as-definition-using-cmake

An alternative/addition would be to add a build date next to/below our actual version hash.

---
- [x] Added **commit date** to `About` dialog next to the commit hash (#1046)
- [ ] implement some kind of version numbering, style could be: www.semver.org

### PR DESCRIPTION
**Pull request by ctrlaltca**
Shown in “about” dialog and used in windows packages name.
schermata 2015-05-02 alle 19 11 53

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I really like the idea, just some people will get confused if they read it as YYYY-DD-MM instead of YYYU-MM-DD

**Comment by Daenyth** [comment]
Ydm if never used. With year first it's always ymd. The confusion is
between dmy/mdy

**Comment by ZeldaZach** [comment]
Didn't know that @daenyth. Thanks for the info!

I think this is good to go :)

**Comment by tooomm** [comment]
Commit date is even better than build date. 

http://en.wikipedia.org/wiki/Calendar_date
YYYY-MM-DD is fine.

I like it! :+1:

**Comment by ZeldaZach** [comment]
This works for Mac and is good to go

**Pull request merged**
