### PR TITLE
set mins for dialog

### LINKED ISSUE #2494: Issues with settings window
<b>OS:</b>
Win 10 64bit (1366x768)

<b>Cockatrice version:</b>
a8a4557 (2017-03-16)

___
<br>

Related PR: #2472

As posted in https://github.com/Cockatrice/Cockatrice/pull/2472#issuecomment-287470961, I experience issues with changes in this PR.

My settings windows has shrunk too much and you can't properly read all information now.

### PR DESCRIPTION
**Pull request by ZeldaZach**
## Related Ticket(s)
- Fixes #2494 

## Screenshots
screenshot 2017-03-18 21 50 13

### CODE REVIEW

**Comment by Daenyth** [comment]
cc @tooomm can you test?

**Comment by tooomm** [comment]
@Daenyth so, so. While on the first page mostly everything is readable and seem to be even bigger than before, there are some issues:
s2
s1

Shortcuts are also affected. In general it just feels not very uniform with small parts in one settings tab and big ones in others. I liked the legacy version without any changes and fixes best.
Is there another way or approach to fix low res users on mac (see https://github.com/Cockatrice/Cockatrice/issues/2471)?
We just need to get it working on like min 1280x800 on mac, nobody is using like 1024x768... on win with just 768 pixel in height it was working perfectly before all the changes!

This is all working and looks uniform and pretty on mac? Hard to believe that it's that different actually... :)

A word on this with low res on mac? @JineteDV

**Comment by ZeldaZach** [comment]
I'm fine with reverting to prior state, but we'd have to figure out how to solve the ticket

**Comment by tooomm** [comment]
>I'm fine with reverting to prior state, but we'd have to figure out how to solve the ticket

Regarding to your initial pr https://github.com/Cockatrice/Cockatrice/pull/2472
"The size cannot go above 2/3'rds the size of the screen by default according to the function"
Did you try with e.g. just 4/5 instead? Or even 7/8?

**But actually looking at the code there is just a fix px number - what!? 🤔 **

**Comment by ZeldaZach** [comment]
@tooomm The function adjustSize() says max 2/3'rds of the screen size in the documentation

**Comment by tooomm** [comment]
Can we change that?

**Comment by ZeldaZach** [comment]
I'll try and look into it again sometime today or tomorrow

**Pull request merged**
