### PR TITLE
Message log

### PR DESCRIPTION
**Pull request by ctrlaltca**
Implements message logging to database as requested in #469 
Most of the reference for this implementation is in the issue at this comment: https://github.com/Cockatrice/Cockatrice/issues/469#issuecomment-65955174
This is the dump of the "log" table filled with example data:
```
--
-- Table structure for table `cockatrice_log`
--

DROP TABLE IF EXISTS `cockatrice_log`;
CREATE TABLE `cockatrice_log` (
  `log_time` datetime NOT NULL,
  `sender_id` int(7) unsigned DEFAULT NULL,
  `sender_name` varchar(35) NOT NULL,
  `sender_ip` varchar(255) NOT NULL,
  `log_message` text NOT NULL,
  `target_type` enum('room','game','chat') DEFAULT NULL,
  `target_id` int(7) DEFAULT NULL,
  `target_name` varchar(50) NOT NULL,
  KEY `sender_name` (`sender_name`),
  KEY `sender_ip` (`sender_ip`),
  KEY `target_type` (`target_type`),
  KEY `target_id` (`target_id`),
  KEY `target_name` (`target_name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `cockatrice_log`
--

INSERT INTO `cockatrice_log` VALUES
('2015-01-01 16:40:00',1,'ctrlaltca','127.0.0.1','message from a REGISTERED user to a room','room',0,'General room'),
('2015-01-01 16:40:23',1,'ctrlaltca','127.0.0.1','message from a REGISTERED user to a game','game',6,'test game'),
('2015-01-01 16:40:58',NULL,'Player_1','127.0.0.1','message from an UNREGISTRED user to a room','room',0,'General room'),
('2015-01-01 16:41:05',NULL,'Player_1','127.0.0.1','message from an UNREGISTRED user to a game','game',6,'test game'),
('2015-01-01 16:41:23',NULL,'Player_1','127.0.0.1','message from an UNREGISTRED user to a REGISTERED user (chat)','chat',1,'ctrlaltca'),
('2015-01-01 16:41:33',1,'ctrlaltca','127.0.0.1','message from an REGISTRED user to a UNREGISTERED user (chat)','chat',NULL,'Player_1');
```

In servatrice.ini new configuration options have been added to enable/disable logging of room messages, game messages, private chat messages and messages coming from other servers (ISL)

### CODE REVIEW

**Comment by ZeldaZach** [comment]
The PHP asset I built is fully functional... but I don't see how we can test this build without setting up a new server completely and having a few users test it. @woogerboy21 Would you like to possibly try this option?

**Comment by Daenyth** [comment]
Yeah, I'd like to see the impact of this running on the server before we merge to mainline

**Comment by woogerboy21** [comment]
I have it running on the testing box i stood up.  @Daenyth  what load testing and were would you prefer it to take place.  The only real user based testing that could occur is on main since no one seems to really use the backup.

**Comment by woogerboy21** [comment]
Also @ctrlaltca 
I haven't had a moment to look at the code but how does this impact the logging to file functionality?  If the logging enabled/disabled flag is set does it disable the db logging or do they just not interact with one another?  If it's not clearly explained in the .ini example file comments we may want to add it.

**Comment by woogerboy21** [comment]
FYI, I now have this up and running on the backup server along with the testing server.

**Comment by ZeldaZach** [comment]
Checking it out now

**Comment by ctrlaltca** [comment]
File logging and database logging doesn't interact: you can disable database logging and keep file logging enabled or viceversa.

**Comment by Daenyth** [comment]
@ZeldaZach this is ready to go right? I believe you tested it with your viewer php code and it's running on the server, @woogerboy21 ?

**Comment by ZeldaZach** [comment]
We're good to go on this. The PHP aspect is functional, but I'm improving upon it. That can quickly be rebuilt at any point, so we should merge :+1:

**Pull request merged**
