### PR TITLE
About dialog: better quality trice logo 

### LINKED ISSUE #3469: App icon in "About" window has very low quality
<b>System Information:</b>
Client Version: 2.6.1-custom(af3a00c) (2018-12-02)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: de_DE
__________________________________________________________________________________________

about_logo

I think that was not always the case?

### PR DESCRIPTION
**Pull request by ctrlaltca**
## Related Ticket(s)
- Fixes #3469

## Short roundup of the initial problem
The original image in svg format was scaled using the fast but quirky alg.

## What will change with this Pull Request?
The image is now scaled using the smoother alg.

### CODE REVIEW

**Comment by ZeldaZach** [comment]
screenshot 2019-02-08 01 45 52

Any reason Mac doesn't show the icon? QT 5.11.2

**Comment by ctrlaltca** [comment]
No idea, its working here (up: old, down: new):

schermata 2019-02-08 alle 09 00 59

**Comment by tooomm** [comment]
With wich qt version did you compile? @ctrlaltca

Looking good on Windows

**Comment by ctrlaltca** [comment]
5.12.1

**Pull request merged**
