### PR TITLE
Added shortcut to reveal top card or lib

### PR DESCRIPTION
**Pull request by poixen**
+ Ctrl + N

### CODE REVIEW

**Comment by Daenyth** [comment]
I'm not sure I like this sequence for such a rarely used action. It seems like it will be hot by accident more often

**Comment by ZeldaZach** [comment]
I agree with @Daenyth as it sounds like it's bound for failure and people already know how to do it by right clicking

**Comment by poixen** [comment]
Gotta disagree with you both. I know that Dae is a vintage player and Zach plays a lot random formats. Those formats don't tend to have revealing effects. 

I play a lot of std, modern and commander. Which are also the majority of fame types. These formats are currently riddled with revealing the top card. Goblin guide, corser ... I find I am constantly right clicking over and over to reveal the top card. It can happen 8+ times in a game. 

I'm trying to reduce the clicks needed to perform actions.

**Comment by Daenyth** [comment]
That's fair, we're probably biased. It'll all get easier when we
tackle key bindings later.

With that in mind, :+1:

**Comment by tooomm** [comment]
(not 100% related to the shortcut, more to the general feature)

Revealed cards on top of lib stay revealed after you stop revealing them until you draw for the next time for example. Top card should flip immediately.

**Comment by poixen** [comment]
I know about this, its super annoying, its on the list.

**Pull request merged**
