### PR TITLE
Fix volume control

### LINKED ISSUE #1528: Volume issues on Windows 7
Using the latest weekly (from ead6ab3), the sound is behaving strangely. For values of 0 and 1, the volume is entirely off &mdash; no sound can be heard. For values between 2 and 100, the volume is at what seems to be maximum.

### PR DESCRIPTION
**Pull request by ctrlaltca**
fix #1528

### CODE REVIEW

**Comment by ZeldaZach** [comment]
The issue still seems to be present on OS X 10.10.5 for me

**Comment by ZeldaZach** [comment]
This issue seems to be fixed on OS X 10.11 (El Capitan) so it was probably an issue in my build environment. :shipit:

**Comment by Daenyth** [comment]
Can we make a packaged build for the folks in #1528 to try?

**Comment by ctrlaltca** [comment]
I'm quite confident on this one.. it just fixes a miscalculation introduced here: https://github.com/Cockatrice/Cockatrice/pull/1498/files#diff-51b32c35f453129126156f5d53a775d5L72

**Comment by Daenyth** [comment]
:shipit:

**Pull request merged**
