### PR TITLE
Enable admin features by default

### PR DESCRIPTION
**Pull request by poixen**
Dont mind if this doesnt get merged, is there any reason we dont want
the feature unlocked when logging in?

### CODE REVIEW

**Comment by woogerboy21** [comment]
I personally vote no.  Currently with the limited number of options in the admin section it seems like more work than needs to be when you want to ban some one but as features are added I would prefer to have the admins/moderators have to enable something before having elevated privileges before being able to use the commands.  This way they know for sure that they are doing something they mean to do.

Now I can see maybe having some features enabled by default but others requiring either an enabling or some type of warning when trying to do.  Like the banning features enabled, but the shutdown server feature ask you "are you really sure?".

**Comment by ZeldaZach** [comment]
The shutdown commands and such are admin-only at this point and I don't see a real reason to limit the rest. Mods usually know when they want to ban somebody as an entire ban dialog appears up they have to fill out.

**Comment by poixen** [comment]
Main reason I made this is that I am always opening and closing the app for work. This helps me out. Thought I would share.

**Comment by Daenyth** [comment]
Maybe we can make it remember your settings?

I strongly prefer it locked by default because it prevents you from unintentionally abusing your mod powers - unlocked means you can ignore people's passwords, buddy restrictions, etc.

**Pull request closed without merging**
