### PR TITLE
Updated grammar based on #932

### PR DESCRIPTION
**Pull request by poixen**
Based on #932 I have added pronouns the the graveyard and hand, and also
changed "from play" to "from battlefield"

### CODE REVIEW

**Comment by ZeldaZach** [comment]
@Psithief Can you see if there are any other inconsistencies within the code base before we merge this?

**Comment by poixen** [comment]
I dont think we need him to scour the app. If anything else is found we can PR it separately.

**Comment by ZeldaZach** [comment]
Yeah, true. I'll see how this performs in a bit :)

**Comment by Psithief** [comment]
Wait, I wanted consistency between "from table" and "into play". Changing *table* to *(the) battlefield* doesn't fix that.

It would be easiest to just replace `from table` with `from play`.

**Comment by tooomm** [comment]
@Psithief adressed two things in 932:
Inconsistant names regarding the battlefield and owned zones

@poixen this pr fixes owned zones for graveyard **(but still missing hand!)**

Second issue about the battlefield naming:
From a log right now:
>a puts *Island* **into play** from the top of his library.
a moves *Island* **from table** to hand.

The same zone (battlefield/table/play) has two different names in client.

Should be: (his suggestion)
>a puts *Island* **into play** from the top of his library.
a moves *Island* **from play** to hand.

**Comment by poixen** [comment]
@tooomm my bad, was missing some checks.

I have changed it to "play".

Can you try it again?

**Comment by poixen** [comment]
@tooomm if you think this is ok, then I will merge.

**Comment by tooomm** [comment]
think so :+1: 

#932 can get closed after merge

**Pull request merged**
