### PR TITLE
Set to download HQ images by default

### PR DESCRIPTION
**Pull request by poixen**
Setting by defualt to be on.

### CODE REVIEW

**Comment by tooomm** [comment]
Does this influence the picture cache? So do we need to increase the default picture cache size to avoid problems with the user experience of the average players?

**Comment by ctrlaltca** [comment]
Indeed, HQ images requires a lot of more space to be cached.

**Comment by Daenyth** [comment]
We should default the cache to max size..

**Comment by ctrlaltca** [comment]
That way we'll end up with the old behavior of the client crashing/being killed when the system goes OOM; not every pc has 2.7Gb of ram.

**Comment by Daenyth** [comment]
Most computers should have 2gb

**Comment by ctrlaltca** [comment]
Not everyone lives in the first world. Anyway, i'm fine with trying this approach, with a "best quality" default and then letting people lower the default value if they have problems with cockatrice crashing.

**Comment by poixen** [comment]
I dont think its been mentioned *why* we are doing this.
It mainly to:
+ allow users to have better image quality by default
+ prevent issues downloading card images when gatherer is down.

**Comment by tooomm** [comment]
If we default to a value that maybe causes a crash that's a bad user experience and people start talking/complaining/asking... if the pictures just need to refresh more often that should be fine in the first place. Everybody is still free to change settings and adjust to their needs/RAM, but the default should be crash free for the average user.

***

I made a short analysis. :)

We get the HQ images from: mtgimage.com, correct?
To quote their site: "Most card images are in 480x680 resolution and come from CCGHQ. Lower resolution images are provided until a higher resolution is available."
*Just to make this clear, CCGHQ provides way better images in real HQ (300dpi scans) but mtgimage just sticks to normal quality in higher resolution for their "hq images".*

test with older set THS:
non-HQ: 227 files / 8,8MB / jpg, 24bit, 96dpi, 223x310
HQ: 226 files / 17.6MB / jpg, 24bit, 96dpi, 480x680
(the one file missing was a missing ths bird token, don't know why - doesn't matter)

same test with newest set FRF:
non-HQ: 184 files / 22,4MB / png, 32bit, 223x311
HQ: 184 files / 8,44MB / jpg, 24bit 96dpi, 265x370
(no higher resolution available right now, so mtgimage sticks to low resolution)
(if we get non-hq pics from gatherer they changed their format and make their files bigger size while keeping the same low quality -> checked gatherer and approved)

==> observation:
- gatherer has downtimes sometimes / mtgimage is stable as far as i know
- gatherer increased the picture size heavily without any improvement, drawback for users

==> conclusion:
- switch to mtgimage is good, no reason at all to stay with gatherer
- maybe rename hq to high resolution since the quality isn't higher...
- we need to increase the picture cache by x2 at least, if we want to offer the same user experiance without crashes (cardsize is roughly doubled for mtgimage hq resolution)

Feel free to make some more tests on older editions.

***

I think we are good to go with 512 or 768MB as default value (from 256 right now).
So even old machines with just 1GB should work fine and there is still enough cache for most games with high resolution pictures.

I'm also not sure what happens if Firefox (or Photoshop, or...) is already using a huge amount of memory. For example a PC has 1GB of RAM, the value is set to 1GB in Cockatrice as well. Firefox is using 500MB and I play some games with many cards and hit 500MB of picture cache size within Cockatrice. Will the client crash because it tries to use more RAM than there is available right now? In theory it could use 1GB, but there are other programs using the RAM too...

**Comment by ctrlaltca** [comment]
Operating system typically use swap file or partitions as an alternative to RAM when there's no RAM free anymore. So when the RAM is all used, you should see your disk led blinking like it's mad (the os unloading RAM pages to the disk to free up space). Once the swap is full, too, two things can happen:
 * a malloc() call from cockatrice fails: 99% crash.
 * the operating system's OOM killer decides to kill cockatrice to avoid freezing the pc.

Cockatrice is using QPixmaps to store images. Even if images are compressed (jpeg), a QPixmap takes roughly (width * height * depth)/8 bytes of memory. (source here: http://qt-project.org/doc/qt-4.8/qpixmapcache.html)
Cockatrice stores both the fullsize image (as loaded from the disk) and the lower-resolution thumbnails used for card images in the game (cards on table, card preview on the right pane, etc..)
All of these pixmaps are stored in RAM in a QPixmapCache, and will grow up eating as much RAM as defined in the settings. When the maximum size is reached, it will start freeing RAM unloading images, choosing them among the the less recently used ones and the bigger ones (the full size images).

**Pull request merged**
