### PR TITLE
Updated tab Icon

### PR DESCRIPTION
**Pull request by poixen**
i

### CODE REVIEW

**Comment by Daenyth** [comment]
I like it!

I'll leave this open a bit so others can give feedback

**Comment by poixen** [comment]
Here is another option, thoughts?
alert

**Comment by Daenyth** [comment]
I think it's a little too busy. Is there a gradient on it? Plus the multiple color transitions.

**Comment by Daenyth** [comment]
I like it

**Comment by MassCraziness** [comment]
This looks like it'd draw more attention on most tabs, though on the server tab I feel it looks a bit too similar to what it already looks like. Perhaps a different color? Or maybe it's just me

**Comment by Daenyth** [comment]
The server tab is weird, you're right. I don't know

**Comment by poixen** [comment]
@Daenyth what if I change the server tab orb from that soft green gradient to a green tick?

**Comment by poixen** [comment]
untitled
Made it a little thinner, felt like the dot was too small, thoughts?

**Comment by Daenyth** [comment]
The orange/yellow one gives me a strange visceral "gross" reaction.

What if we refresh the ! image and just make it a little cleaner?

**Comment by MassCraziness** [comment]
I like the idea of making the "!" look a bit nicer. :+1: @Daenyth

**Comment by poixen** [comment]
ex1
ex2

**Comment by ctrlaltca** [comment]
What about a blue circle with a white "i" (the classic icon for "information")?

**Comment by Daenyth** [comment]
@poixen I think you deleted your comment, but the orb is the same thing that shows your connection status - it's used in the game view as well, I don't think we should change it

**Comment by poixen** [comment]
Its also updated in real time for ping. Hence why I removed the comment.

**Comment by Daenyth** [comment]
I figured as much

**Comment by poixen** [comment]
i
@ctrlaltca s idea. Im using a magic styled font for the 'i'.

**Comment by Daenyth** [comment]
It looks weird on OSX
screen shot 2015-02-11 at 10 22 15 pm

**Comment by MassCraziness** [comment]
Yeah that happened on Linux too @Daenyth

**Comment by tooomm** [comment]
( connecting this two things in case someone is up for changing it, the Oracle - "O" - Issue: #665 )

**Comment by poixen** [comment]
Can someone try this again now?

**Comment by poixen** [comment]
Closing, please see #733

**Pull request closed without merging**
