### PR TITLE
Add country code to user info box.

### PR DESCRIPTION
**Pull request by Daenyth**
People might not know all the flags

userinfo

### CODE REVIEW

**Comment by LethalPigeon7** [comment]
Capital letters would look nicer IMO.

**Comment by Daenyth** [comment]
Done

**Comment by ZeldaZach** [comment]
Looks good to me

**Comment by Daenyth** [comment]
Good catch, I didn't test it after that change.

**Comment by Daenyth** [comment]
@ZeldaZach updated, try again.

**Comment by ZeldaZach** [comment]
Good to merge

**Comment by tooomm** [comment]
@Daenyth 

Just tested from build 0c32cfa:
country code in details

My suggestions:
 - add a space between flag and "(xx)"
 - if there is no flag set, don't display "()", or make it e.g. "(not set)"

**Comment by Daenyth** [comment]
Can you report in a new ticket, this is already merged

**Comment by tooomm** [comment]
Thanks @ZeldaZach for taking care. ;)

But a general git question:
It doesn't make sense to post related observations into the merged pr because you can't add a commit and fix/adjust things?

**Comment by Daenyth** [comment]
It doesn't make sense because closed PRs don't show up under "open"
issues, so the only people who will see your comment are people who
have followed this ticket

**Pull request merged**
