### PR TITLE
Force black text color on deck list

### LINKED ISSUE #1289: Deck list is hard to read with dark UI theme
I use a GTK theme which has a dark background and light text. This, combined with the white, green, and gray coloring in the deck editor makes the deck list extremely hard to read.

One possible solution would be to ensure that the text in the deck list is always black, rather than just assuming that the default will be readable.

Another option would be to make the deck list colors change with the theme.

Screenshot:

### PR DESCRIPTION
**Pull request by ctrlaltca**
fix #1289

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Seems fine to me, but I'd like @skwerlman to possibly test this before we merge it

**Comment by ctrlaltca** [comment]
I'd like @skwerlman to test this if possible, too.
I tested it with Xfce 4.12 using a dark theme, here's a screenshot:
black

**Comment by ZeldaZach** [comment]
Based on your test I'm fine with merging this. I didn't have a dark-end to test with so it was awkward for me.

**Comment by skwerlman** [comment]
Looks good!

**Pull request merged**
