### PR TITLE
add pauper to the list of checked formats in search

### LINKED ISSUE #3900: Pauper Legality Does Not Exist
<b>System Information:</b>

Client Version: 2.7.2-custom(unknown) (unknown)
Client Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
Build Architecture: 64-bit
Qt Version: 5.9.9
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/home/danny/.local/share/Cockatrice/Cockatrice/cards.xml"
PictureLoader: cache fail for "_trice_card_back_253446"
Attempting auto-connect...
link path1214 hasn't been detected!
link path1563 hasn't been detected!
link path1563 hasn't been detected!
[CardDatabase] loadCardDatabase(): Path = "/home/danny/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20563 Sets= 472
[CockatriceXml4Parser] Trying to parse:  "/home/danny/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/danny/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21016 Sets= 472
[CardDatabase] loadCardDatabase(): Path = "/home/danny/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21016 Sets= 472
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "_____"  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "_____"  set:  "UNH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "_____"  set:  "UNH" ]: Trying to download picture from url: "https://api.scryfall.com/cards/5aa90ab6-2686-4462-8725-5d4370c05437?format=image&face=front"
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://api.scryfall.com/cards/5aa90ab6-2686-4462-8725-5d4370c05437?format=image&face=front")
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Trying to load picture
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Abbey Gargoyles"  set:  "ME2" ]: Trying to load picture
PictureLoader: [card:  "Abbey Gargoyles"  set:  "ME2" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Akron Legionnaire"  set:  "ME3" ]: Trying to load picture
PictureLoader: [card:  "Akron Legionnaire"  set:  "ME3" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "_____"  set:  "UNH" ]: following redirect: "https://img.scryfall.com/cards/large/front/5/a/5aa90ab6-2686-4462-8725-5d4370c05437.jpg?1562488395"
PictureLoader: [card:  "Battlegate Mimic"  set:  "HOP" ]: Trying to load picture
PictureLoader: [card:  "Battlegate Mimic"  set:  "HOP" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "_____"  set:  "UNH" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/5/a/5aa90ab6-2686-4462-8725-5d4370c05437.jpg?1562488395"
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Trying to download picture from url: "https://api.scryfall.com/cards/d3f10f07-7cfe-4a6f-8de6-373e367a731b?format=image&face=front"
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: following redirect: "https://img.scryfall.com/cards/large/front/d/3/d3f10f07-7cfe-4a6f-8de6-373e367a731b.jpg?1565887966"
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/d/3/d3f10f07-7cfe-4a6f-8de6-373e367a731b.jpg?1565887966"
PictureLoader: [card:  "Abbey Gargoyles"  set:  "ME2" ]: Trying to download picture from url: "https://api.scryfall.com/cards/8d80663b-ea3f-4f7a-bff1-8fde04c05bce?format=image&face=front"
PictureLoader: [card:  "Abbey Gargoyles"  set:  "ME2" ]: following redirect: "https://img.scryfall.com/cards/large/front/8/d/8d80663b-ea3f-4f7a-bff1-8fde04c05bce.jpg?1562869525"
PictureLoader: [card:  "Abbey Gargoyles"  set:  "ME2" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/8/d/8d80663b-ea3f-4f7a-bff1-8fde04c05bce.jpg?1562869525"
PictureLoader: [card:  "Akron Legionnaire"  set:  "ME3" ]: Trying to download picture from url: "https://api.scryfall.com/cards/b3e10240-8a4f-410f-a9b2-5df89d7038df?format=image&face=front"
PictureLoader: [card:  "Akron Legionnaire"  set:  "ME3" ]: following redirect: "https://img.scryfall.com/cards/large/front/b/3/b3e10240-8a4f-410f-a9b2-5df89d7038df.jpg?1562932965"
PictureLoader: [card:  "Akron Legionnaire"  set:  "ME3" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/b/3/b3e10240-8a4f-410f-a9b2-5df89d7038df.jpg?1562932965"
PictureLoader: [card:  "Battlegate Mimic"  set:  "HOP" ]: Trying to download picture from url: "https://api.scryfall.com/cards/c330f44c-0479-472d-81ed-16445d182c37?format=image&face=front"
PictureLoader: [card:  "Battlegate Mimic"  set:  "HOP" ]: following redirect: "https://img.scryfall.com/cards/large/front/c/3/c330f44c-0479-472d-81ed-16445d182c37.jpg?1562842884"
PictureLoader: [card:  "Battlegate Mimic"  set:  "HOP" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/c/3/c330f44c-0479-472d-81ed-16445d182c37.jpg?1562842884"
PictureLoader: [card:  "\"Rumors of My Death . . .\""  set:  "UST" ]: Trying to load picture
PictureLoader: [card:  "\"Rumors of My Death . . .\""  set:  "UST" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Rumors of My Death . . ."  set:  "UST" ]: Trying to download picture from url: "https://api.scryfall.com/cards/cb3587b9-e727-4f37-b4d6-1baa7316262f?format=image&face=front"
PictureLoader: [card:  "\"Rumors of My Death . . .\""  set:  "UST" ]: following redirect: "https://img.scryfall.com/cards/large/front/c/b/cb3587b9-e727-4f37-b4d6-1baa7316262f.jpg?1562937945"
PictureLoader: [card:  "\"Rumors of My Death . . .\""  set:  "UST" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/c/b/cb3587b9-e727-4f37-b4d6-1baa7316262f.jpg?1562937945"
PictureLoader: [card:  "Absorb"  set:  "PRNA" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Absorb"  set:  "PRNA" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Absorb"  set:  "PRNA" ]: Trying to load picture
PictureLoader: [card:  "Absorb"  set:  "PRNA" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Absorb"  set:  "PRNA" ]: Trying to download picture from url: "https://api.scryfall.com/cards/513997c3-a754-4160-9b22-67cfe2953851?format=image&face=front"
PictureLoader: [card:  "Absorb"  set:  "PRNA" ]: following redirect: "https://img.scryfall.com/cards/large/front/5/1/513997c3-a754-4160-9b22-67cfe2953851.jpg?1570827663"
PictureLoader: [card:  "Absorb"  set:  "PRNA" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/5/1/513997c3-a754-4160-9b22-67cfe2953851.jpg?1570827663"

_______________________________________________________________________________________

Context: The search help includes commands f: (format) and legal: (legality). It even includes legal:pauper as an example of how to use legal. This has happened to be moth on the prebuilt binary of Cockatrice available on flathub and when building Cockatrice from source.

What happened: typing legal:pauper into the search bar indicates that there are no valid cards to play in pauper. f:pauper behaves identically. Other formats (f:commander or legal:standard) work fine, I just think that the pauper legality/ban list got dropped from cockatrice at some point.

What should've happened: I should've been shown all cards which are legal to play in pauper.

### PR DESCRIPTION
**Pull request by ebbit1q**
note that l:p remains reserved for pioneer

## Related Ticket(s)
- Fixes #3900

## Short roundup of the initial problem
pauper was forgotten to be added to the list of formats checked by the parser which should in all honesty be able to take any value.

## What will change with this Pull Request?
- pauper simply gets added to the list of regular expressions

### CODE REVIEW

**Comment by ebbit1q** [comment]
This does not work yet as expected because of the weird hacks in this function.

**Comment by ebbit1q** [comment]
this now throws away the hardcoded formats in the regular expression and performs the search on any inserted string, I don't really notice any performance difference.

**Comment by tooomm** [comment]
>note that l:p remains reserved for pioneer

Wouldn't it be better to remove l:p completely. Or have l:pi and l:pa instead?

**Comment by ebbit1q** [comment]
less changes, please preserve the current entropy in this world.

**Comment by ZeldaZach** [comment]
Looks like a reasonable change to me, just we don't have a single letter short cut for pauper. 🤷‍♂

**Pull request merged**
