### PR TITLE
fix #3500

### LINKED ISSUE #3500: Fix "reveal top cards" message in the log
When using "reveal top cards", the message shown in the log is always "reveals the top card" cause logRevealCards doesn't take the number of cards revealed `cardList.size()` as a parameter

https://github.com/Cockatrice/Cockatrice/blob/273d5d89b74afd2ad5cb88e7a14a6f0edf276fdb/cockatrice/src/player.cpp#L1870

### PR DESCRIPTION
**Pull request by ebbit1q**
fixes #3500
Please don't reveal the top 0 cards.

### CODE REVIEW

**Comment by ctrlaltca** [comment]
> NOBODY SAW THAT

That missing semicolon :D

**Comment by ebbit1q** [comment]
NOOOO

**Comment by tooomm** [comment]
Too bad the 3rd party never knows how much cards are being revealed between the other players.
That would be the perfect, transparent solution between all players.

**Comment by ebbit1q** [comment]
That would require changes on the server side, this is a good solution without changing that.

**Pull request merged**
